- type: job
  id: TownMayor
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-townmayor
  description: job-description-townmayor
  playTimeTracker: TownMayor
  requirements:
    # Forge-Change-Del - !type:CharacterSpeciesRequirement
      # Forge-Change-Del species:
      # Forge-Change-Del - Human
      # Forge-Change-Del - Ghoul
    # Forge-Change-Del - !type:CharacterDepartmentTimeRequirement
      # Forge-Change-Del department: Townsfolk
      # Forge-Change-Del min: 36000 # 10 hours
  # Forge-Change-Start
  - !type:CharacterSpeciesRequirement
    species:
    - Human
    - Ghoul
  - !type:CharacterDepartmentTimeRequirement
    department: Townsfolk
    min: 36000 # 10 hours
  # Forge-Change-End
  startingGear: TownMayorGear
  icon: "JobIconTownMayor" # Forge-Change
  # Forge-Change-Del supervisors: job-supervisors-townsfolk
  # Forge-Change
  supervisors: job-supervisors-town-mayor # Forge-Chang
  alwaysUseSpawner: true # Forge-Change
  access:
  - RadioBroadcast
  accessGroups:
  - Townie
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - Townsfolk

- type: startingGear
  id: TownMayorGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCheckered
    back: N14ClothingBackpackExplorer # Forge-Change
    shoes: N14ClothingShoesBrown
    id: N14IDBadgeTownMayor
    pocket1: RadioHandheld
    belt: N14WalletLottaCash
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelMayorFilled
  duffelbag: N14ClothingBackpackDuffelMayorFilled
  storage: # Forge-Change
    back:
    - N14BoxPlasticFilledWastelander

- type: playTimeTracker
  id: TownMayor
