- type: job
  id: BoSWestScribe
  setPreference: true
  name: job-name-bos-west-scribe
  description: job-description-bos-west-scribe
  playTimeTracker: BoSWestScribe
  requirements:
    # Forge-Change-Del - !type:CharacterSpeciesRequirement
      # Forge-Change-Del species:
      # Forge-Change-Del - Human
    # Forge-Change-Del - !type:CharacterDepartmentTimeRequirement
      # Forge-Change-Del department: BrotherhoodWest
      # Forge-Change-Del min: 18000 # 5 hours
  # Forge-Change-Start
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterDepartmentTimeRequirement
    department: BrotherhoodWest
    min: 18000 # 5 hours
  # Forge-Change-End
  startingGear: BoSWestScribeGear
  alwaysUseSpawner: true
  icon: "JobIconBosMScriptor"
  supervisors: job-supervisors-bos-west
  access:
  - BoSWest
  - WestScribe
  - WestKnight
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWest
          - Wastelander
      - type: CPRTraining

- type: startingGear
  id: BoSWestScribeGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSWestScribe
    back: N14ClothingBackpackSatchelMilitary
    shoes: N14ClothingBootsLeather
    pocket1: BoSWesternScribeKits
    id: N14IDBrotherhoodWestHolotag
    ears: N14ClothingHeadsetBOSWest
  storage:
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSWestScribe
