- type: loadout
  id: LoadoutBoSMidwestUnknown
  category: Outer
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
  items:
    - N14ClothingOuterPowerArmorMidwest

- type: loadout
  id: LoadoutBoSMidwestUnknown2
  category: Outer
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
  items:
    - N14ClothingOuterPowerArmorMidwestCommander

- type: loadout
  id: LoadoutClothingOuterBOSInquisitorBlackCoat
  category: Outer
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidInquisitor
      min: 216000 # 60 hours
  items:
    - N14ClothingOuterBOSInquisitorBlackCoat

- type: loadout
  id: LoadoutClothingOuterBOSInquisitorBattleArmor
  category: Outer
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidInquisitor
      min: 72000 # 20 hours veterancy unlock
  items:
    - N14ClothingOuterBOSInquisitorBattleArmor

- type: loadout
  id: LoadoutClothingHeadHatBoSInquisitorHat
  category: Head
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
  items:
    - N14ClothingHeadHatBoSInquisitorHat

- type: loadout
  id: LoadoutClothingHeadHatBoSInquisitorBlackHat
  category: Head
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidInquisitor
      min: 216000 # 60 hours
  items:
    - N14ClothingHeadHatBoSInquisitorBlackHat

- type: loadout
  id: LoadoutClothingHeadHatBoSInquisitorBattleHelmet
  category: Head
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidInquisitor
      min: 72000 # 20 hours veterancy unlock
  items:
    - N14ClothingHeadHatBoSInquisitorBattleHelmet

- type: loadout
  id: LoadoutClothingHeadHatBoSInquisitorBattleHelmetHood
  category: Head
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidInquisitor
      min: 72000 # 20 hours veterancy unlock
  items:
    - N14ClothingHeadHatBoSInquisitorBattleHelmetHood

- type: loadout
  id: LoadoutMaskBoSMidwestLiner
  category: Mask
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
        - BoSMidPaladin
        - BoSMidKnight
        - BoSMidSquire
        - BoSWashingtonCommander
        - BoSWashingtonPaladin
        - BoSWashingtonKnight
        - BoSWashingtonInitiate
        - BoSWestElderCommander
        - BoSWestPaladin
        - BoSWestKnight
        - BoSWestGunsmith
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodMidwest
          min: 18000
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodWashington
          min: 18000
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodWest
          min: 18000
  items:
    - N14ClothingMaskLiner

- type: loadout
  id: LoadoutMaskBoSMidwestLinerBlack
  category: Mask
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
        - BoSMidPaladin
        - BoSMidKnight
        - BoSWashingtonCommander
        - BoSWashingtonPaladin
        - BoSWashingtonKnight
        - BoSWashingtonInitiate
        - BoSWestElderCommander
        - BoSWestPaladin
        - BoSWestKnight
        - BoSWestGunsmith
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodMidwest
          min: 36000
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodWashington
          min: 36000
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodWest
          min: 36000
  items:
    - N14ClothingMaskLinerBlack

- type: loadout
  id: LoadoutMaskBoSMidwestLinerElite
  category: Mask
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
        - BoSMidPaladin
        - BoSWashingtonCommander
        - BoSWashingtonPaladin
        - BoSWestElderCommander
        - BoSWestPaladin
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodMidwest
          min: 36000
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodWashington
          min: 36000
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodWest
          min: 36000
  items:
    - N14ClothingMaskLinerElite

- type: loadout
  id: LoadoutClothingNeckMWBSShoulderPadFlag
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
  items:
    - N14ClothingNeckMWBSShoulderPadFlag

- type: loadout
  id: LoadoutClothingNeckMWBSKnightShoulderPad
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidKnight
  items:
    - N14ClothingNeckMWBSKnightShoulderPad

- type: loadout
  id: LoadoutClothingNeckMWBSSeniorKnightShoulderPad
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidKnight
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidKnight
      min: 144000
  items:
    - N14ClothingNeckMWBSSeniorKnightShoulderPad

- type: loadout
  id: LoadoutClothingNeckMWBSCommanderKnightShoulderPad
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidKnight
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidKnight
      min: 216000
  items:
    - N14ClothingNeckMWBSKnightCommanderShoulderPad

- type: loadout
  id: LoadoutClothingNeckMWBSPaladintShoulderPad
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
  items:
    - N14ClothingNeckMWBSPaladinShoulderPad

- type: loadout
  id: LoadoutN14ClothingNeckCloakTentBOS
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
        - BoSMidPaladin
        - BoSMidKnight
        - BoSMidSquire
  items:
    - N14ClothingNeckCloakTentBOS
