- type: loadout
  id: LoadoutClothingOuterWBoSReconBattleArmor
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSWashingtonPaladin
      min: 96000
  items:
    - N14ClothingOuterWBoSReconBattleArmor

- type: loadout
  id: LoadoutClothingOuterWBoSKnightBattleArmorKilt
  category: Roles
  cost: 6
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonKnight
    - !type:CharacterPlaytimeRequirement
      tracker: BoSWashingtonKnight
      min: 96000
  items:
    - N14ClothingOuterWBoSKnightBattleArmorKilt

- type: loadout
  id: LoadoutClothingHeadHatWBoSBeret
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSWashingtonKnight
        - BoSWashingtonPaladin
  items:
    - N14ClothingHeadHatWBoSBeret