using Content.Client.UserInterface.Controls;
using Content.Shared.Magnits.QuestInstance;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Magnits.QuestInstance;

[GenerateTypedNameReferences]
public sealed partial class QuestBoardWindow : FancyWindow
{
    // Fired when the player presses Easy / Medium / Hard or the Join button.
    public event Action<QuestDifficulty>? OnDifficultySelected;

    public QuestBoardWindow()
    {
        RobustXamlLoader.Load(this);

        EasyButton.OnPressed   += _ => OnDifficultySelected?.Invoke(QuestDifficulty.Easy);
        MediumButton.OnPressed += _ => OnDifficultySelected?.Invoke(QuestDifficulty.Medium);
        HardButton.OnPressed   += _ => OnDifficultySelected?.Invoke(QuestDifficulty.Hard);
        // Join always sends Easy — server ignores difficulty when instance exists.
        JoinButton.OnPressed   += _ => OnDifficultySelected?.Invoke(QuestDifficulty.Easy);
    }

    /// <summary>Refreshes the window layout to reflect the latest BUI state.</summary>
    public void UpdateState(QuestBoardBoundUserInterfaceState state)
    {
        if (state.HasActiveInstance)
        {
            CreateBox.Visible = false;
            JoinBox.Visible   = true;

            var minutes = state.RemainingSeconds / 60;
            var seconds = state.RemainingSeconds % 60;
            StatusLabel.Text = Loc.GetString(
                "quest-board-status-active",
                ("players", state.ParticipantCount),
                ("minutes", minutes),
                ("seconds", seconds));
        }
        else
        {
            CreateBox.Visible = true;
            JoinBox.Visible   = false;
            StatusLabel.Text  = Loc.GetString("quest-board-status-idle");
        }
    }
}
