- type: job
  id: BoSWashingtonCommander
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: true
  name: job-name-bos-washington-commander
  description: job-description-bos-washington-commander
  playTimeTracker: BoSWashingtonCommander
  requirements:
    # Forge-Change-Del - !type:CharacterSpeciesRequirement
      # Forge-Change-Del species:
      # Forge-Change-Del - Human
    # Forge-Change-Del - !type:CharacterPlaytimeRequirement # Forge-Add
      # Forge-Change-Del tracker: BoSWashingtonCommander
      # Forge-Change-Del min: 1080000 # (Admin Only Test)
    # Forge-Change-Del - !type:CharacterDepartmentTimeRequirement
      # Forge-Change-Del department: BrotherhoodWashington
      # Forge-Change-Del min: 72000 #20 hours
    # Forge-Change-Del - !type:CharacterWhitelistRequirement # Forge-Add
  # Forge-Change-Start
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterDepartmentTimeRequirement
    department: BrotherhoodWashington
    min: 72000 #20 hours
  - !type:CharacterPlaytimeRequirement # Forge-Add
    tracker: BoSWashingtonCommander
    min: 1080000 # (Admin Only Test)
  - !type:CharacterWhitelistRequirement # Forge-Add
  # Forge-Change-End
  startingGear: BoSWashingtonCommanderGear
  alwaysUseSpawner: true
  icon: "JobIconbosWCommander"
  supervisors: job-supervisors-bos-wash-commander
  requireAdminNotify: true
  access:
  - RadioBroadcast
  accessGroups:
  - BOSWashington
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - BrotherhoodWashington

- type: startingGear
  id: BoSWashingtonCommanderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitWBoSLord # Forge-Change
    back: N14ClothingBackpackMilitary # Forge-Change
    shoes: N14ClothingBootsCombatMK2Filled # Forge-Change
    gloves: N14ClothingHandsGlovesCombat # Forge-Change
    outerClothing: N14ClothingOuterWBoSLordBattleArmor # Forge-Change
    head: N14ClothingHeadHatWBoSLordHelmet # Forge-Add
    id: N14IDBrotherhoodWashingtonHolotagCommander
    ears: N14ClothingHeadsetBOSWashington
    belt: ClothingBeltBoSWebbing
    pocket1: BoSWashingtonLordKits # Forge-Change
  storage: # Forge-Change
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSWashingtonCommander
