- type: job
  id: BoSWashingtonInitiate
  setPreference: true
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-bos-washington-initiate
  description: job-description-bos-washington-initiate
  playTimeTracker: BoSWashingtonInitiate
  requirements:
    # Forge-Change-Del - !type:CharacterLogicOrRequirement
      # Forge-Change-Del requirements:
        # Forge-Change-Del - !type:CharacterSpeciesRequirement
          # Forge-Change-Del species:
            # Forge-Change-Del - Human
            # Forge-Change-Del - Ghoul
    # Forge-Change-Del - !type:CharacterOverallTimeRequirement
      # Forge-Change-Del min: 21600 # Forge-Change (6 hours)
  # Forge-Change-Start
  - !type:CharacterOverallTimeRequirement
    min: 21600 # Forge-Change (6 hours)
  - !type:CharacterLogicOrRequirement
    requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
  # Forge-Change-End
  startingGear: BoSWashingtonInitiateGear
  alwaysUseSpawner: true
  icon: "JobIconbosWSquire"
  supervisors: job-supervisors-bos-wash-initiate
  access:
  - WashingtonInitiate
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - BrotherhoodWashington

- type: startingGear
  id: BoSWashingtonInitiateGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitWBoSAcolyte # Forge-Change
    back: N14ClothingBackpackMilitary # Forge-Change
    shoes: N14ClothingBootsLeatherFilled
    id: N14IDBrotherhoodWashingtonHolotagInitiate
    outerClothing: N14ClothingOuterWBoSAcolyteCoat # Forge-Change
    belt: ClothingBeltRope # Forge-Change
    pocket1: BoSWashingtonInitSet
  storage: # Forge-Change
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSWashingtonInitiate
