using Content.Shared.Audio.Jukebox;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Nuclear14.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class PipBoyRadioUiFragment : BoxContainer
{
    public event Action<string>? OnSongSelected;
    public event Action? OnPlay;
    public event Action? OnPause;
    public event Action? OnStop;
    public event Action? OnPrevious;
    public event Action? OnNext;
    public event Action<float>? OnVolumeChanged;

    private readonly Dictionary<string, string> _songs = new();
    private readonly Dictionary<string, Button> _songButtons = new();

    private IPrototypeManager? _prototypeManager;

    public PipBoyRadioUiFragment()
    {
        RobustXamlLoader.Load(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        PreviousButton.OnPressed += _ =>
            OnPrevious?.Invoke();

        NextButton.OnPressed += _ =>
            OnNext?.Invoke();

        PlayButton.OnPressed += _ =>
            OnPlay?.Invoke();

        PauseButton.OnPressed += _ =>
            OnPause?.Invoke();

        VolumeSlider.OnValueChanged += args =>
        {
            UpdateVolumeLabel(args.Value);
            OnVolumeChanged?.Invoke(args.Value / 100f);
        };

        StopButton.OnPressed += _ =>
            OnStop?.Invoke();
    }

    public void SetPrototypeManager(
        IPrototypeManager prototypeManager)
    {
        _prototypeManager = prototypeManager;
    }

    private void UpdateVolumeLabel(float percent)
    {
        VolumeLabel.Text = Loc.GetString("pipboy-radio-volume", ("volume", (int) MathF.Round(percent)));
    }

    private void LoadSongs(
        IEnumerable<ProtoId<JukeboxPrototype>> songIds)
    {
        SongContainer.RemoveAllChildren();

        _songs.Clear();
        _songButtons.Clear();

        if (_prototypeManager == null)
            return;

        foreach (var songId in songIds)
        {
            if (!_prototypeManager.TryIndex(
                    songId,
                    out var song))
                continue;

            var id = song.ID;
            var name = song.Name;

            _songs[id] = name;

            var button = new Button
            {
                Text = name,
                HorizontalExpand = true
            };

            button.OnPressed += _ =>
                OnSongSelected?.Invoke(id);

            _songButtons[id] = button;
            SongContainer.AddChild(button);
        }
    }

    public void UpdateState(
        IReadOnlyList<ProtoId<JukeboxPrototype>> songIds,
        string? selectedSong,
        bool playing,
        bool paused,
        float volume)
    {
        if (!VolumeSlider.Grabbed)
        {
            VolumeSlider.SetValueWithoutEvent(volume * 100f);
            UpdateVolumeLabel(VolumeSlider.Value);
        }

        if (_songButtons.Count == 0)
            LoadSongs(songIds);
        foreach (var (id, button) in _songButtons)
        {
            var name = _songs[id];

            button.Text =
                id == selectedSong
                    ? $"▶ {name}"
                    : name;
        }

        if (selectedSong != null &&
            _songs.TryGetValue(
                selectedSong,
                out var selectedName))
        {
            CurrentTrack.Text =
                Loc.GetString(
                    "pipboy-radio-current-track",
                    ("track", selectedName));
        }
        else
        {
            CurrentTrack.Text =
                Loc.GetString("pipboy-radio-no-track");
        }

        Status.Text =
            playing
                ? Loc.GetString("pipboy-radio-status-playing")
                : paused
                    ? Loc.GetString("pipboy-radio-status-paused")
                    : Loc.GetString("pipboy-radio-status-stopped");
    }
}
