using System.Linq;
using Content.Shared.Audio.Jukebox;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Nuclear14.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class PipBoyRadioUiFragment : BoxContainer
{
    public event Action<string>? OnSongSelected;
    public event Action? OnPlay;
    public event Action? OnPause;
    public event Action? OnStop;
    public event Action? OnPrevious;
    public event Action? OnNext;

    private readonly Dictionary<string, string> _songs = new();
    private readonly Dictionary<string, Button> _songButtons = new();

    public PipBoyRadioUiFragment()
    {
        RobustXamlLoader.Load(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        PreviousButton.OnPressed += _ =>
            OnPrevious?.Invoke();

        NextButton.OnPressed += _ =>
            OnNext?.Invoke();

        PlayButton.OnPressed += _ =>
            OnPlay?.Invoke();

        PauseButton.OnPressed += _ =>
            OnPause?.Invoke();

        StopButton.OnPressed += _ =>
            OnStop?.Invoke();
    }

    public void LoadSongs(
        IPrototypeManager prototypeManager)
    {
        SongContainer.RemoveAllChildren();

        _songs.Clear();
        _songButtons.Clear();

        foreach (var song in prototypeManager
                     .EnumeratePrototypes<JukeboxPrototype>()
                     .OrderBy(song => song.Name))
        {
            var id = song.ID;
            var name = song.Name;

            _songs[id] = name;

            var button = new Button
            {
                Text = name,
                HorizontalExpand = true
            };

            button.OnPressed += _ =>
                OnSongSelected?.Invoke(id);

            _songButtons[id] = button;
            SongContainer.AddChild(button);
        }
    }

    public void UpdateState(
        string? selectedSong,
        bool playing,
        bool paused)
    {
        foreach (var (id, button) in _songButtons)
        {
            var name = _songs[id];

            button.Text =
                id == selectedSong
                    ? $"▶ {name}"
                    : name;
        }

        if (selectedSong != null &&
            _songs.TryGetValue(
                selectedSong,
                out var selectedName))
        {
            CurrentTrack.Text =
                $"ТРЕК: {selectedName}";
        }
        else
        {
            CurrentTrack.Text = "ТРЕК: ---";
        }

        Status.Text =
            playing
                ? "СТАТУС: ИГРАЕТ"
                : paused
                    ? "СТАТУС: ПАУЗА"
                    : "СТАТУС: ОСТАНОВЛЕНО";
    }
}
