using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Newspapers;
using Content.Shared._Forge.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Robust.Shared.Timing;
using System.Linq;
using Robust.Client.Graphics;
using Robust.Shared.Configuration;
using Content.Client.Stylesheets;

namespace Content.Client._Forge.Newspapers;

[GenerateTypedNameReferences]
public sealed partial class NewspaperDeskWindow : FancyWindow
{
    private NewspaperDeskUiState? _state;
    private NewspaperEdition _draft = new();
    private readonly List<NewspaperTemplatePrototype> _starters;
    private bool _loading;
    private bool _published;
    private bool _layout;
    private bool _layoutEditorEnabled;
    private bool _pageSettings;
    private Button? _armedReplacement;
    private string? _armedReplacementText;
    private bool _armedReplacementHadDangerStyle;
    private TimeSpan _armedUntil;
    private NewspaperEdition? _checkpoint;
    private readonly List<NewspaperEdition> _undo = new();
    private readonly List<NewspaperEdition> _redo = new();
    private bool _restoring;
    private bool _closeAfterSave;
    private bool _discardOnClose;
    private bool _closeWarning;
    private bool _typingChange;
    private int _typingBlock = -1;
    private TimeSpan _typingUntil;
    private string? _captionNotice;
    private static readonly StyleBox GallerySelectionStyle = new StyleBoxFlat
    {
        BackgroundColor = Color.FromHex("#233847"), BorderColor = Color.FromHex("#55B7F3"),
        BorderThickness = new Thickness(2),
        ContentMarginLeftOverride = 6, ContentMarginRightOverride = 6,
        ContentMarginTopOverride = 2, ContentMarginBottomOverride = 2,
    };
    private int _zoom = 75;
    private int _page;
    private int _selectedBlockIndex = -1;
    private int _selectedTemplateIndex;
    private int _selectedArchiveId;
    private int _printCount = 1;
    private NewspaperPaper _printPaper = NewspaperPaper.White;
    private readonly NewspaperPhotos _photos = new();
    private readonly NewspaperPhotoQueue _photoRequests = new();
    private readonly IGameTiming _timing = IoCManager.Resolve<IGameTiming>();
    private readonly IConfigurationManager _config = IoCManager.Resolve<IConfigurationManager>();
    public event Action<NewspaperEdition>? OnSave;
    public event Action<NewspaperEdition>? OnSaveTemplate;
    public event Action<NewspaperEdition>? OnPublish;
    public event Action<int, int, NewspaperPaper>? OnPrint;
    public event Action<int, int>? OnImageRequested;
    public event Action<int>? OnSelectPhoto;
    public event Action<int>? OnForgetPhoto;
    public event Action<NewspaperEdition, int, string>? OnSwitchPublication;

    public NewspaperDeskWindow()
    {
        RobustXamlLoader.Load(this);
        InitializePublicationAndPreviewActions();
        _starters = IoCManager.Resolve<IPrototypeManager>().EnumeratePrototypes<NewspaperTemplatePrototype>().OrderBy(p => p.Order).ThenBy(p => p.ID).ToList();
        InitializeBlockEditor();
        InitializeTemplateAndPrintActions();
        _config.OnValueChanged(NewspaperCVars.LayoutEditorEnabled, OnLayoutEditorEnabledChanged, true);
    }

    private void InitializePublicationAndPreviewActions()
    {
        PublicationList.OnItemSelected += args =>
        {
            if (args.Id != _draft.PublicationId && _save.Pending == null && !_save.Conflict)
                OnSwitchPublication?.Invoke(_draft.Clone(), args.Id, "");
        };
        NewPublicationButton.OnPressed += _ => OpenNewPublication();
        CancelPublicationButton.OnPressed += _ =>
        {
            NewPublicationToolbar.Visible = false;
            Refresh();
        };
        NewPublicationName.OnTextChanged += _ =>
        {
            if (!_loading) Refresh();
        };
        CreatePublicationButton.OnPressed += _ => CreatePublication();
        DraftModeButton.OnPressed += _ => SetMode(false, false);
        PhotoBufferButton.OnPressed += _ =>
        {
            ClearReplacementConfirmation();
            Refresh();
        };
        ChoosePhotoButton.OnPressed += _ => ChoosePhotoForSelectedBlock();
        BlockSettingsButton.OnPressed += _ =>
        {
            _pageSettings = false;
            Refresh();
        };
        PageSettingsButton.OnPressed += _ =>
        {
            _pageSettings = true;
            Refresh();
        };
        RenamePublicationButton.OnPressed += _ => OpenRename();
        ApplyNameButton.OnPressed += _ => ApplyPublicationName();
        CloseNameButton.OnPressed += _ =>
        {
            PublicationNameToolbar.Visible = false;
            NameField.Text = _draft.Name;
            Refresh();
        };
        BackToBlockButton.OnPressed += _ =>
        {
            PhotoBufferButton.Pressed = false;
            Refresh();
        };
        InsertPhotoButton.OnPressed += _ => EditBlock(b =>
        {
            if (b.Kind == NewspaperBlockKind.Photo && _state!.BufferedPhotos.Contains(_selectedGalleryPhotoId)) b.PhotoId = _selectedGalleryPhotoId;
        });
        PhotoTargetList.OnItemSelected += args => SelectPhotoTarget(args.Id);
        TextAppearanceButton.OnPressed += _ => Refresh();
        UndoButton.OnPressed += _ => RestoreHistory(_undo, _redo);
        RedoButton.OnPressed += _ => RestoreHistory(_redo, _undo);
        ZoomButton.AddItem(Loc.GetString("newspaper-fit-page"), 0);
        foreach (var zoom in new[] { 50, 75, 100, 125 }) ZoomButton.AddItem($"{zoom}%", zoom);
        ZoomButton.SelectId(_zoom);
        foreach (var paper in Enum.GetValues<NewspaperPaper>())
            PaperQualityButton.AddItem(Loc.GetString($"newspaper-paper-{paper.ToString().ToLowerInvariant()}"), (int)paper);
        PaperQualityButton.OnItemSelected += args => SelectPrintPaper((NewspaperPaper)args.Id);
        ZoomButton.OnItemSelected += args =>
        {
            _zoom = args.Id;
            ZoomButton.SelectId(args.Id);
        };
        FindOverflowButton.OnPressed += _ => FindOverflowBlock();
        LinkCaptionButton.OnPressed += _ => LinkSelectedCaption();
        // Registered before the BUI close handler so the save is sent while the UI is still open.
        OnClose += () => { if (!_discardOnClose) SaveIfChanged(); };
        BindReplacement(DiscardCloseButton, () => { _discardOnClose = true; base.Close(); }, "newspaper-close-discard-tip");
    }

    private void InitializeTemplateAndPrintActions()
    {
        TemplateList.OnItemSelected += args =>
        {
            ClearReplacementConfirmation();
            _selectedTemplateIndex = args.Id;
            TemplateList.SelectId(args.Id);
            Refresh();
        };
        BindReplacement(LoadTemplateButton, LoadSelectedTemplate);
        BindReplacement(BlankButton, () => SetDraft(_layout
            ? new NewspaperEdition { Width = _draft.Width, Height = _draft.Height, Pages = _draft.Pages, Name = _draft.Name, PublicationId = _draft.PublicationId }
            : NewspaperLayout.ClearContents(_draft)));
        BindReplacement(DemoButton, LoadSelectedExample);
        ModeButton.OnPressed += _ => SetMode(true, false);
        SideButton.OnPressed += _ =>
        {
            _page = (_page + 1) % Displayed.Pages;
            Refresh();
        };
        RotateButton.OnPressed += _ =>
        {
            (_draft.Width, _draft.Height) = (_draft.Height, _draft.Width);
            ClampBlocks();
            Refresh();
        };
        SnapButton.OnToggled += _ => Refresh();
        SaveTemplateButton.OnPressed += _ => SaveCurrentTemplate();
        BindReplacement(RemovePhotoButton, () => EditBlock(b => b.PhotoId = -1), "newspaper-confirm-block-photo");
        BindReplacement(ForgetPhotoButton, ForgetSelectedPhoto, "newspaper-photo-forget-confirm");
        SaveButton.OnPressed += _ => SaveIfChanged();
        BindReplacement(ReloadDraftButton, ReloadServerDraft, "newspaper-reload-confirm");
        BindReplacement(DeleteArchiveButton, () => { if (_selectedArchiveId > 0) OnDeleteEdition?.Invoke(_selectedArchiveId); }, "newspaper-archive-delete-confirm");
        PublishButton.OnPressed += _ => PublishDraft();
        PrintButton.OnPressed += _ =>
        {
            if (_published && _selectedArchiveId > 0) OnPrint?.Invoke(_printCount, _selectedArchiveId, _printPaper);
        };
        DecreaseButton.OnPressed += _ =>
        {
            _printCount = Math.Max(1, _printCount - 1);
            Refresh();
        };
        IncreaseButton.OnPressed += _ =>
        {
            _printCount = Math.Min(10, _printCount + 1);
            Refresh();
        };
        NameField.OnTextChanged += _ =>
        {
            if (!_loading) Refresh();
        };
        TemplateNameField.OnTextChanged += _ => { if (!_loading) { _draft.TemplateName = TemplateNameField.Text; Refresh(); } };
        PreviewModeButton.OnPressed += _ => SetMode(false, true);
        ArchiveButton.OnItemSelected += args =>
        {
            ClearReplacementConfirmation();
            _selectedArchiveId = args.Id;
            ArchiveButton.SelectId(args.Id);
            _published = true;
            Refresh();
        };
        PageView.OnSelected += SelectPageBlock;
        PageView.OnChanged += Refresh;
    }

    private void OpenNewPublication()
    {
        NewPublicationName.Text = _state?.Publications.Length == 1 && string.IsNullOrEmpty(_state.Draft.Name) ? _draft.Name : "";
        NewPublicationToolbar.Visible = true;
        NewPublicationName.GrabKeyboardFocus();
        Refresh();
    }

    private void CreatePublication()
    {
        if (_save.Pending != null || _save.Conflict || !NewNameAvailable(NewPublicationName.Text) || !DraftIsValid()) return;
        OnSwitchPublication?.Invoke(_draft.Clone(), 0, NewPublicationName.Text);
        NewPublicationToolbar.Visible = false;
        NewPublicationName.Text = "";
    }

    private void ApplyPublicationName()
    {
        if (_save.Pending != null || _save.Conflict || !DraftIsValid() || !NameAvailable(NameField.Text)) return;
        _draft.Name = NameField.Text.Trim();
        PublicationNameToolbar.Visible = false;
        SaveIfChanged();
        Refresh();
    }

    private void SelectPrintPaper(NewspaperPaper paper)
    {
        if (_loading || !_published) return;
        _printPaper = paper;
        Refresh();
    }

    private NewspaperBlock? Selected => !_published && _selectedBlockIndex >= 0 && _selectedBlockIndex < _draft.Blocks.Count ? _draft.Blocks[_selectedBlockIndex] : null;
    private NewspaperEdition? Archived => _state?.Editions.FirstOrDefault(e => e.ArchiveId == _selectedArchiveId);
    private NewspaperEdition Displayed => _published && _selectedArchiveId > 0
        ? _loadedArchiveId == _selectedArchiveId && _loadedEdition != null ? _loadedEdition : Archived ?? _draft : _draft;

    private void SetMode(bool layout, bool archive)
    {
        ClearReplacementConfirmation();
        _pageSettings = false;
        _layout = layout && _layoutEditorEnabled; _published = archive;
        PublicationNameToolbar.Visible = NewPublicationToolbar.Visible = false;
        Refresh();
    }

    private void OnLayoutEditorEnabledChanged(bool enabled)
    {
        _layoutEditorEnabled = enabled;
        ModeButton.Visible = enabled;
        if (!enabled)
        {
            _layout = false;
            _pageSettings = false;
            ClearReplacementConfirmation();
        }
        Refresh();
    }

    private bool DraftIsValid() => NewspaperLayout.IsValid(_draft) && (_state == null ||
        !_state.Publications.Any(p => p.Id != _draft.PublicationId &&
            string.Equals(p.Name, _draft.Name.Trim(), StringComparison.OrdinalIgnoreCase)));

    private void SaveIfChanged()
    {
        if (_save.Pending != null || _save.Conflict || _state == null || !DraftIsValid() || _save.Saved != null && SameDraft(_save.Saved, _draft)) return;
        _save.Prepare(_draft, _timing.RealTime);
        OnSave?.Invoke(_draft.Clone());
        Refresh();
    }

    private void BindReplacement(Button button, Action action, string tooltip = "newspaper-replace-repeat-tip")
    {
        button.ToolTip = Loc.GetString(tooltip);
        button.OnPressed += _ =>
        {
            if (ConfirmButton(button, tooltip == "newspaper-replace-repeat-tip" ? null : Loc.GetString(tooltip))) action();
        };
    }

    private bool ConfirmButton(Button button, string? warning = null)
    {
        var confirmed = _armedReplacement == button && _timing.RealTime <= _armedUntil;
        ClearReplacementConfirmation();
        if (confirmed) return true;
        _armedReplacement = button;
        _armedReplacementText = button.Text;
        _armedReplacementHadDangerStyle = button.StyleClasses.Contains(StyleBase.ButtonDanger);
        _armedUntil = _timing.RealTime + TimeSpan.FromSeconds(5);
        button.AddStyleClass(StyleBase.ButtonDanger);
        ConfirmationHintLabel.SetMessage((warning == null ? "" : warning + " ") + Loc.GetString("newspaper-confirm-action", ("action", _armedReplacementText ?? "")));
        ConfirmationHintLabel.Visible = true;
        return false;
    }

    private void ClearReplacementConfirmation()
    {
        if (_armedReplacement != null)
        {
            if (!_armedReplacementHadDangerStyle) _armedReplacement.RemoveStyleClass(StyleBase.ButtonDanger);
        }
        _armedReplacement = null; _armedReplacementText = null;
        ConfirmationHintLabel.Visible = false;
    }

    private void RestoreHistory(List<NewspaperEdition> source, List<NewspaperEdition> target)
    {
        _typingBlock = -1;
        if (_published || source.Count == 0) return;
        target.Add(_draft.Clone());
        var draft = source[^1]; source.RemoveAt(source.Count - 1);
        draft.PhotoId = _draft.PhotoId; // Physical attachments are owned by the server, not layout history.
        if (_state != null) NewspaperStorage.RemoveUnavailablePhotos(draft, _state.BufferedPhotos.Concat(_state.Draft.PhotoIds));
        _restoring = true;
        SetDraft(draft);
        _restoring = false;
    }

    private static NewspaperEdition CreateStarter(NewspaperTemplatePrototype prototype, bool demo)
    {
        var layout = prototype.Layout.Clone();
        layout.TemplateName = Loc.GetString(prototype.Name);
        layout.Name = demo ? Loc.GetString("newspaper-demo-name") : "";
        foreach (var block in layout.Blocks)
        {
            block.IsLabel |= block.TextKey != null;
            block.Text = block.TextKey != null ? Loc.GetString(block.TextKey) : demo && block.DemoKey != null ? Loc.GetString(block.DemoKey) : block.Text;
        }
        return layout;
    }

    public void UpdateState(NewspaperDeskUiState state)
    {
        var initial = _state == null;
        var archiveChanged = initial || !_state!.Editions.Select(e => e.ArchiveId).SequenceEqual(state.Editions.Select(e => e.ArchiveId));
        var archiveAdded = initial || state.Editions.Any(e => !_state!.Editions.Any(old => old.ArchiveId == e.ArchiveId));
        if (archiveChanged) ClearReplacementConfirmation();
        var publicationChanged = initial || _state!.Draft.PublicationId != state.Draft.PublicationId;
        var photosOnly = !initial && state.Revision != _state!.Revision &&
            NewspaperStorage.IsPhotoRemoval(_state.Draft, state.Draft, state.BufferedPhotos.Concat(state.Draft.PhotoIds));
        var accept = NewspaperDraftSync.CanApply(_save.Saved, _draft, initial, _save.Pending != null);
        if (photosOnly)
        {
            _save.AdvanceRevision(state.Revision);
            if (_save.Saved != null) NewspaperStorage.RemoveUnavailablePhotos(_save.Saved, state.BufferedPhotos.Concat(state.Draft.PhotoIds));
        }
        if (!initial && state.Revision != _save.Revision && !accept && _save.Pending == null)
            _save.MarkConflict();
        _state = state;
        if (accept)
        {
            _save.AcceptBaseline(state.Draft, state.Revision);
            var draft = initial && state.Draft.Blocks.Count == 0
                ? CreateStarter(_starters.FirstOrDefault(p => p.Default) ?? _starters[0], false) : state.Draft.Clone();
            draft.Name = state.Draft.Name; draft.PublicationId = state.Draft.PublicationId;
            if (!SameDraft(_draft, draft)) SetDraft(draft);
            if (initial || publicationChanged)
            {
                _undo.Clear(); _redo.Clear(); _checkpoint = _draft.Clone();
                _selectedBlockIndex = -1;
                PublicationNameToolbar.Visible = false;
            }
        }
        if (_draft.PublicationId == state.Draft.PublicationId)
            NewspaperStorage.RemoveUnavailablePhotos(_draft, state.BufferedPhotos.Concat(state.Draft.PhotoIds));
        TemplateList.Clear();
        var id = 0;
        foreach (var starter in _starters) TemplateList.AddItem(Loc.GetString(starter.Name), id++);
        foreach (var template in state.Templates) TemplateList.AddItem(template.TemplateName, id++);
        _selectedTemplateIndex = Math.Clamp(_selectedTemplateIndex, 0, Math.Max(0, id - 1));
        if (initial || publicationChanged)
        {
            var names = _starters.Select(p => Loc.GetString(p.Name)).Concat(state.Templates.Select(t => t.TemplateName)).ToArray();
            var current = Array.IndexOf(names, _draft.TemplateName);
            if (current >= 0) _selectedTemplateIndex = current;
        }
        TemplateList.SelectId(_selectedTemplateIndex);
        PublicationList.Clear();
        foreach (var publication in state.Publications)
            PublicationList.AddItem(string.IsNullOrEmpty(publication.Name) ? Loc.GetString("newspaper-publication-unnamed") : publication.Name, publication.Id);
        PublicationList.TrySelectId(_draft.PublicationId);
        PublicationList.Disabled = _save.Pending != null || _save.Conflict;
        ArchiveButton.Clear();
        var archive = state.Editions.Select(edition => (Edition: edition, Index: edition.ArchiveId))
            .Where(e => e.Edition.PublicationId == _draft.PublicationId).ToArray();
        foreach (var entry in archive)
            ArchiveButton.AddItem(Loc.GetString("newspaper-archive-entry", ("edition", entry.Edition.Number), ("headline", ShortText(EditionHeadline(entry.Edition), 48))), entry.Index);
        if (publicationChanged || !archive.Any(e => e.Index == _selectedArchiveId) || archiveAdded && archive.LastOrDefault().Index > _selectedArchiveId)
            _selectedArchiveId = archive.LastOrDefault().Index;
        if (_selectedArchiveId > 0) ArchiveButton.SelectId(_selectedArchiveId);
        Refresh();
        if (_save.DeferredResult != null && state.Revision >= _save.DeferredResult.Revision) ReceiveResult(_save.DeferredResult);
        if (_closeAfterSave && _save.Saved != null && SameDraft(_save.Saved, _draft))
        {
            _closeAfterSave = false;
            base.Close();
        }
    }

    private static bool SameDraft(NewspaperEdition a, NewspaperEdition b, bool comparePhotos = true) =>
        NewspaperStorage.SameContent(a, b, comparePhotos);

    private void SetDraft(NewspaperEdition draft)
    {

        ClearReplacementConfirmation();
        _draft = draft; _published = false; _page = 0; _selectedBlockIndex = -1;
        _loading = true;
        NameField.Text = draft.Name;
        TemplateNameField.Text = draft.TemplateName;
        _loading = false;
        var templateNames = _starters.Select(p => Loc.GetString(p.Name)).Concat(_state?.Templates.Select(t => t.TemplateName) ?? Enumerable.Empty<string>()).ToArray();
        var templateIndex = Array.IndexOf(templateNames, draft.TemplateName);
        if (templateIndex >= 0) _selectedTemplateIndex = templateIndex;
        RefreshBlockList(); Refresh();
    }

    private void RefreshBlockList()
    {
        BlockList.Clear();
        BlockList.AddItem(Loc.GetString("newspaper-block-none"), -1);
        for (var i = 0; i < _draft.Blocks.Count; i++)
        {
            var b = _draft.Blocks[i];
            BlockList.AddItem(BlockDescription(b), i);
        }
        BlockList.SelectId(_selectedBlockIndex);
    }

    private void ClampBlocks()
    {
        _page = Math.Min(_page, _draft.Pages - 1);
        foreach (var b in _draft.Blocks)
        {
            b.Width = Math.Min(b.Width, _draft.Width); b.Height = Math.Min(b.Height, _draft.Height);
            b.X = Math.Min(b.X, _draft.Width - b.Width); b.Y = Math.Min(b.Y, _draft.Height - b.Height);
            b.Page = Math.Min(b.Page, _draft.Pages - 1);
        }
        RefreshBlockList();
    }

    private void FormatSelection(string tag)
    {
        if (_published || Selected?.Kind != NewspaperBlockKind.Text) return;
        _typingBlock = -1;
        var text = Rope.Collapse(TextField.TextRope);
        var start = TextField.SelectionLower.Index;
        var end = TextField.SelectionUpper.Index;
        var formatted = NewspaperTypography.ToggleStyle(text, start, end, tag);
        var updated = formatted.Text;
        if (updated.Length > NewspaperLayout.MaxTextLength) return;
        TextField.TextRope = new Rope.Leaf(updated);
        Selected.Text = updated;
        TextField.CursorPosition = TextField.CursorPosition with { Index = formatted.End };
        TextField.SelectionStart = TextField.SelectionStart with { Index = formatted.Start };
        TextField.GrabKeyboardFocus();
        Refresh();
        _typingBlock = -1;
    }

    private void Refresh()
    {
        if (_loading || _state == null) return;
        _loading = true;
        NewspaperLayout.ResolvePhotoCaptions(_draft);
        if (!_restoring && _checkpoint != null && !SameDraft(_checkpoint, _draft))
        {
            _closeAfterSave = false;
            ClearReplacementConfirmation();
            if (_selectedBlockIndex >= 0 && _selectedBlockIndex < _draft.Blocks.Count && _selectedBlockIndex < _checkpoint.Blocks.Count &&
                _checkpoint.Blocks[_selectedBlockIndex].CaptionFor != null && _draft.Blocks[_selectedBlockIndex].CaptionFor == null)
                _captionNotice = _draft.Blocks[_selectedBlockIndex].Id;
            if (!_typingChange || _typingBlock != _selectedBlockIndex || _timing.RealTime >= _typingUntil)
            {
                _undo.Add(_checkpoint); if (_undo.Count > 64) _undo.RemoveAt(0);
            }
            _typingBlock = _typingChange ? _selectedBlockIndex : -1;
            _typingUntil = _timing.RealTime + TimeSpan.FromMilliseconds(750);
            _redo.Clear();
        }
        _checkpoint = _draft.Clone();
        _draft.Number = _state.Publications.FirstOrDefault(p => p.Id == _draft.PublicationId)?.NextNumber
            ?? NewspaperLayout.NextEditionNumber(_state.Editions, _draft.PublicationId);
        var shown = Displayed;
        PaperQualityButton.SelectId((int)_printPaper);
        PaperQualityButton.Disabled = !_published || _selectedArchiveId == 0;
        PageView.SurfaceAppearance = _published
            ? new PaperSurfaceAppearance { Seed = 1, Profile = NewspaperLayout.PaperProfile(_printPaper) } : null;
        _page = Math.Min(_page, shown.Pages - 1);
        PageView.Editable = !_published;
        PageView.LayoutMode = _layout;
        PageView.Selected = _selectedBlockIndex;
        PageView.Snap = SnapButton.Pressed;
        PageView.Page = _page;
        var photoKeys = VisiblePhotoKeys();
        _photos.Retain(photoKeys);
        PageView.SetContent(shown, photoResolver: id => _photos.Get(id, photoKeys.GetValueOrDefault(id)));
        RefreshBlockEditor();
        TemplateSelectionToolbar.Visible = !_published;
        TemplateToolbar.Visible = _layout && !_published;
        ArchiveToolbar.Visible = _published && _selectedArchiveId > 0;
        ArchiveEmptyLabel.Visible = _published && _selectedArchiveId == 0;
        PageViewport.Visible = !_published || _selectedArchiveId > 0 && _loadedArchiveId == _selectedArchiveId;
        ArchiveLoadingLabel.Visible = _published && _selectedArchiveId > 0 && _loadedArchiveId != _selectedArchiveId;
        DraftActions.Visible = !_published;
        PrintActions.Visible = _published;
        DraftModeButton.Pressed = !_published && !_layout;
        ModeButton.Pressed = !_published && _layout;
        PreviewModeButton.Pressed = _published;
        UndoButton.Visible = RedoButton.Visible = !_published;
        UndoButton.Disabled = _undo.Count == 0;
        RedoButton.Disabled = _redo.Count == 0;
        DemoButton.Disabled = _selectedTemplateIndex >= _starters.Count;
        DemoButton.ToolTip = Loc.GetString("newspaper-replace-repeat-tip");
        SaveTemplateButton.ToolTip = Loc.GetString("newspaper-template-content-tip");
        SidebarModeToolbar.Visible = _layout && !_published;
        BlockSettingsButton.Pressed = !_pageSettings;
        PageSettingsButton.Pressed = _pageSettings;
        BlockList.Visible = BlockListLabel.Visible = !_published && (!_layout || !_pageSettings);
        BlockProperties.Visible = Selected != null && (!_layout || !_pageSettings);
        BordersButton.Visible = _layout;
        GeometryFields.Visible = _layout;
        PageProperties.Visible = _layout && !_published && _pageSettings;
        BlockList.Disabled = _published || _draft.Blocks.Count == 0;
        NameField.Editable = TemplateNameField.Editable = !_published;
        LoadTemplateButton.Disabled = BlankButton.Disabled = _published;
        DemoButton.Disabled = _published || _selectedTemplateIndex >= _starters.Count;
        RenamePublicationButton.Disabled = _published;
        SideLabel.Text = Loc.GetString("newspaper-side-status", ("page", _page + 1), ("pages", shown.Pages));
        SideButton.Visible = shown.Pages > 1;
        SideButton.Text = Loc.GetString(_page == 1 ? "newspaper-show-front" : "newspaper-show-back");
        PreviewLabel.Text = Loc.GetString(_published ? "newspaper-published-preview" : "newspaper-draft-preview");
        ArchiveButton.Disabled = _selectedArchiveId == 0;
        DeleteArchiveButton.Disabled = !_published || Archived == null;
        PhotoBufferButton.Disabled = _published;
        PhotoBufferToolbar.Visible = PhotoBufferButton.Pressed && !_published;
        RemovePhotoButton.Disabled = _published || Selected?.Kind != NewspaperBlockKind.Photo || _draft.PhotoFor(Selected) < 0;
        RefreshPhotoGallery();
        ForgetPhotoButton.Disabled = _published || !_state.BufferedPhotos.Contains(_selectedGalleryPhotoId);
        var valid = DraftIsValid();
        var dirty = _save.Saved == null || !SameDraft(_save.Saved, _draft);
        SaveButton.Disabled = _published || !valid || !dirty || _save.Pending != null || _save.Conflict;
        SaveStatusLabel.Text = Loc.GetString(_published ? "newspaper-archive-status" : !valid ? "newspaper-save-invalid" :
            _save.Pending != null ? "newspaper-saving" : dirty ? "newspaper-unsaved" : "newspaper-saved");
        SaveStatusLabel.ToolTip = Loc.GetString("newspaper-close-save-tip");
        SaveTemplateButton.Disabled = _published || !valid || string.IsNullOrWhiteSpace(_draft.TemplateName);
        OverflowToolbar.Visible = !_published && !PageView.ContentFits;
        if (OverflowToolbar.Visible)
            OverflowLabel.SetMessage(Loc.GetString(_layout ? "newspaper-block-overflow" : "newspaper-block-overflow-fill", ("block", PageView.OverflowBlock + 1)));
        var contentValid = valid && NewspaperLayout.IsValid(_draft, true);
        var latest = _state.Editions.LastOrDefault(e => e.PublicationId == _draft.PublicationId);
        var lastEdition = _loadedEdition?.PublicationId == _draft.PublicationId && _loadedEdition.Number == latest?.Number ? _loadedEdition : null;
        var alreadyPublished = _state.DraftPublished && SameDraft(_state.Draft, _draft) || lastEdition != null && SameDraft(lastEdition, _draft);
        PublishButton.Disabled = _published || _save.Publishing || _save.Pending != null || _save.Conflict || alreadyPublished || !contentValid || !PageView.ContentFits;
        PublishButton.ToolTip = Loc.GetString(alreadyPublished ? "newspaper-publish-unchanged-tip" : !contentValid ? "newspaper-publish-content-tip" : !PageView.ContentFits ? "newspaper-publish-overflow-tip" : "newspaper-publish-tip");
        PrintButton.ToolTip = Loc.GetString(_selectedArchiveId == 0 ? "newspaper-archive-empty" : _state.PaperCount < _printCount ? "newspaper-print-paper-tip" : "newspaper-print-tip");
        CaptionLinkLabel.Visible = (!_layout || !_pageSettings) && (Selected?.CaptionFor != null || Selected != null && Selected.Id == _captionNotice);
        CaptionLinkLabel.Text = Loc.GetString(Selected?.CaptionFor != null ? "newspaper-caption-linked" : "newspaper-caption-unlinked");
        LinkCaptionButton.Visible = _layout && !_pageSettings && Selected is { Kind: NewspaperBlockKind.Text, CaptionFor: null } &&
            _draft.Blocks.Any(b => b.Kind == NewspaperBlockKind.Photo && b.Page == Selected.Page);
        PrintButton.Disabled = !_published || _selectedArchiveId == 0 || _state.PaperCount < _printCount;
        PrintButton.Text = Archived != null ? Loc.GetString("newspaper-print-edition", ("edition", Archived.Number)) : Loc.GetString("newspaper-print");
        PaperLabel.Text = Loc.GetString("newspaper-paper-count", ("count", _state.PaperCount));
        CountLabel.Text = _printCount.ToString();
        RefreshFeedback(valid, dirty, alreadyPublished);
        _loading = false;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_armedReplacement != null && (_timing.RealTime > _armedUntil || _armedReplacement.Disabled || !_armedReplacement.VisibleInTree || _published && _armedReplacement != DeleteArchiveButton))
            ClearReplacementConfirmation();
        if (_save.TryTimeout(_timing.RealTime))
        {
            if (_closeAfterSave)
            {
                _closeWarning = true;
                _published = false;
            }
            _closeAfterSave = false;
            Refresh();
        }
        RefreshEmphasis();
        if (_state != null && PageViewport.Width > 0 && PageViewport.Height > 0)
        {
            var shown = Displayed;
            PageView.PreviewScale = _zoom == 0
                ? Math.Clamp(Math.Min((PageViewport.Width - 20) / shown.Width, (PageViewport.Height - 20) / shown.Height), 0.1f, 1f)
                : _zoom / 100f;
        }
        if (VisibleInTree && _state != null)
        {
            PollVisibleGallery();
            if (_published && _selectedArchiveId > 0 && _loadedArchiveId != _selectedArchiveId &&
                (_requestedArchiveId != _selectedArchiveId || _timing.RealTime - _archiveRequestTime > TimeSpan.FromSeconds(2)))
            {
                _requestedArchiveId = _selectedArchiveId; _archiveRequestTime = _timing.RealTime;
                OnArchiveRequested?.Invoke(_selectedArchiveId);
            }
            if (_photos.Poll()) Refresh();
            var ids = Displayed.PhotoIdsForPage(_page);
            if (PhotoBufferToolbar.Visible) ids = ids.Concat(_visibleGalleryPhotos);
            if (_photoRequests.TryRequest(ids, _published ? _selectedArchiveId : 0, _timing.RealTime, _photos.IsResolved, out var id))
                OnImageRequested?.Invoke(_published ? _selectedArchiveId : 0, id);
        }
    }

    public void ReceivePhoto(int photoId, byte[] data, string photoKey = "")
    {
        var keys = VisiblePhotoKeys();
        if (!keys.TryGetValue(photoId, out var key) || photoKey.Length > 0 && photoKey != key) return;
        if (_photos.Get(photoId, key, data) != null) Refresh();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _config.UnsubValueChanged(NewspaperCVars.LayoutEditorEnabled, OnLayoutEditorEnabledChanged);
            ClearReplacementConfirmation();
            _photos.Dispose();
        }
        base.Dispose(disposing);
    }
}
