using Robust.Client.UserInterface.CustomControls;
using Content.Shared._Forge.Newspapers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using System.Numerics;
using Robust.Client.Graphics;
using Robust.Shared.Timing;
using System.Linq;

namespace Content.Client._Forge.Newspapers;

[GenerateTypedNameReferences]
public sealed partial class NewspaperCopyWindow : BaseWindow
{
    private bool _back;
    private NewspaperEdition? _edition;
    private readonly NewspaperPhotoQueue _photoRequest = new();
    private readonly IGameTiming _timing = IoCManager.Resolve<IGameTiming>();
    private readonly NewspaperPhotos _photos = new();
    private Dictionary<int, string> _photoKeys = new();
    private Texture? Photo(int id) => _photos.Get(id, _photoKeys.GetValueOrDefault(id));
    public event Action<int>? OnImageRequested;

    public NewspaperCopyWindow()
    {
        RobustXamlLoader.Load(this);
        CloseButton.OnPressed += _ => Close();
        SideButton.OnPressed += _ =>
        {
            _back = !_back;
            PageView.Page = _back ? 1 : 0;
            RefreshPage();
            SideButton.Text = Loc.GetString(_back ? "newspaper-show-front" : "newspaper-show-back");
        };
    }

    public void UpdateState(NewspaperCopyUiState state)
    {
        _edition = state.Edition;
        _photoKeys = state.PhotoKeys;
        PageView.SurfaceAppearance = state.Surface;
        SideButton.Visible = state.Edition.Pages > 1;
        var available = Parent?.Size ?? new Vector2(1280, 900);
        var zoom = Math.Clamp(Math.Min((available.X - 64) / state.Edition.Width,
            (available.Y - 96) / state.Edition.Height), 0.1f, 1f);
        SetSize = new Vector2(state.Edition.Width * zoom + 8, state.Edition.Height * zoom + 40);
        PageView.Page = _back ? 1 : 0;
        RefreshPage();
    }

    private Dictionary<int, string> VisiblePhotoKeys() => _edition == null ? new() :
        _edition.PhotoIdsForPage(PageView.Page).Where(_photoKeys.ContainsKey).ToDictionary(id => id, id => _photoKeys[id]);

    private void RefreshPage()
    {
        if (_edition == null) return;
        _photos.Retain(VisiblePhotoKeys());
        PageView.SetContent(_edition, photoResolver: Photo);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_edition != null && _photos.Poll()) RefreshPage();
        if (_edition != null && ScrollingContents.Width > 0 && ScrollingContents.Height > 0)
            PageView.PreviewScale = FitPageButton.Pressed
                ? Math.Clamp(Math.Min(ScrollingContents.Width / _edition.Width, ScrollingContents.Height / _edition.Height), 0.1f, 1f)
                : 1f;
        if (VisibleInTree && _edition != null && _photoRequest.TryRequest(_edition.PhotoIdsForPage(PageView.Page), 0, _timing.RealTime, _photos.IsResolved, out var id))
            OnImageRequested?.Invoke(id);
    }

    public void ReceivePhoto(int id, byte[] data)
    {
        if (!VisiblePhotoKeys().TryGetValue(id, out var key)) return;
        _photos.Get(id, key, data);
        RefreshPage();
    }

    protected override DragMode GetDragModeFor(Vector2 position)
    {
        const int edge = 12;
        var mode = DragMode.None;
        if (position.X < edge) mode |= DragMode.Left;
        else if (position.X > Width - edge) mode |= DragMode.Right;
        if (position.Y < edge) mode |= DragMode.Top;
        else if (position.Y > Height - edge) mode |= DragMode.Bottom;
        return mode == DragMode.None ? DragMode.Move : mode;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _photos.Dispose();
        base.Dispose(disposing);
    }
}
