using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.FactionResearch;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._Misfits.FactionResearch.UI;

[GenerateTypedNameReferences]
public sealed partial class FactionResearchMenu : FancyWindow
{
    public event Action<string>? OnPrint;
    public event Action<NetEntity>? OnConvert;
    public event Action<int>? OnWithdrawDisk;

    private static readonly (Button Button, int Amount)[] DiskButtons = new (Button, int)[4];

    public FactionResearchMenu()
    {
        RobustXamlLoader.Load(this);

        DiskButtons[0] = (Disk500, 500);
        DiskButtons[1] = (Disk1000, 1000);
        DiskButtons[2] = (Disk2500, 2500);
        DiskButtons[3] = (Disk5000, 5000);

        foreach (var (button, amount) in DiskButtons)
        {
            var value = amount;
            button.OnPressed += _ => OnWithdrawDisk?.Invoke(value);
        }
    }

    public void UpdateState(FactionResearchBoundInterfaceState state)
    {
        PointsLabel.Text = Loc.GetString("faction-research-points", ("faction", state.Faction), ("points", state.Points));

        foreach (var (button, amount) in DiskButtons)
        {
            button.Disabled = state.Points < amount;
        }

        PrintList.Children.Clear();
        var lastHeader = string.Empty;
        var lastTier = -1;
        foreach (var print in state.Prints.OrderBy(t => t.Category).ThenBy(t => t.Tier).ThenBy(t => t.Name))
        {
            var header = string.IsNullOrEmpty(print.Category) ? Loc.GetString("faction-research-prints") : print.Category;
            if (header != lastHeader)
            {
                lastHeader = header;
                lastTier = -1;
                PrintList.AddChild(new Label { Text = header, StyleClasses = { "LabelHeading" } });
            }

            if (print.Tier != lastTier)
            {
                lastTier = print.Tier;
                PrintList.AddChild(new Label { Text = Loc.GetString("faction-research-tier", ("tier", print.Tier)) });
            }

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            row.AddChild(new Label
            {
                Text = $"{print.Name} - {print.Cost}",
                HorizontalExpand = true,
            });

            var button = new Button
            {
                Text = Loc.GetString("faction-research-buy"),
                Disabled = !print.Available,
            };
            var id = print.Id;
            button.OnPressed += _ => OnPrint?.Invoke(id);
            row.AddChild(button);

            PrintList.AddChild(row);
        }

        ConvertList.Children.Clear();
        foreach (var convertible in state.Convertibles)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            row.AddChild(new Label
            {
                Text = $"{convertible.Name} - {convertible.Points}",
                HorizontalExpand = true,
            });

            var button = new Button { Text = Loc.GetString("faction-research-convert-button") };
            var ent = convertible.Item;
            button.OnPressed += _ => OnConvert?.Invoke(ent);
            row.AddChild(button);

            ConvertList.AddChild(row);
        }
    }
}
