using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.QuestInstance;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Forge.QuestInstance;


[GenerateTypedNameReferences]
public sealed partial class QuestBoardWindow : FancyWindow
{
    public QuestBoardWindow()
    {
        RobustXamlLoader.Load(this);

        EasyButton.OnPressed += _ => OnDifficultySelected?.Invoke(QuestDifficulty.Easy);
        MediumButton.OnPressed += _ => OnDifficultySelected?.Invoke(QuestDifficulty.Medium);
        HardButton.OnPressed += _ => OnDifficultySelected?.Invoke(QuestDifficulty.Hard);
        JoinButton.OnPressed += _ => OnDifficultySelected?.Invoke(QuestDifficulty.Easy);
    }

    public event Action<QuestDifficulty>? OnDifficultySelected;

    public void UpdateState(QuestBoardBoundUserInterfaceState state)
    {
        if (state.HasActiveInstance)
        {
            CreateBox.Visible = false;
            JoinBox.Visible = true;
            StatusLabel.FontColorOverride = Color.FromHex("#ead2a2");

            var minutes = state.RemainingSeconds / 60;
            var seconds = state.RemainingSeconds % 60;
            StatusLabel.Text = Loc.GetString(
                "quest-board-status-active",
                ("players", state.ParticipantCount),
                ("minutes", minutes),
                ("seconds", seconds));
        }
        else
        {
            CreateBox.Visible = true;
            JoinBox.Visible = false;
            StatusLabel.FontColorOverride = Color.FromHex("#c7ae81");
            StatusLabel.Text = Loc.GetString("quest-board-status-idle");
        }
    }
}


