# Syndicate Operative Plasmaman outfit
- type: startingGear
  abstract: true
  id: BaseSyndicatePlasmamanGear
  requirements:
  - !type:CharacterSpeciesRequirement
    species: [ Plasmaman ]
  equipment:
    jumpsuit: ClothingUniformEnvirosuitOperative
    head: ClothingHeadEnvirohelmOperative
    mask: ClothingMaskGasSyndicate
    # No envirogloves, some starting gear might have combat gloves

- type: startingGear
  id: InhandTankGear
  subGear:
  - InhandOxygenTankGear
  - InhandPlasmaTankGear
  requirements:
  - !type:CharacterSpeciesRequirement
    species: [ Plasmaman ]

- type: startingGear
  id: InhandOxygenTankGear
  requirements:
  - !type:CharacterSpeciesRequirement
    inverted: true
    species: [ Plasmaman ]
  inhand:
    - AirTankFilled

- type: startingGear
  id: InhandPlasmaTankGear
  requirements:
  - !type:CharacterSpeciesRequirement
    species: [ Plasmaman ]
  inhand:
    - PlasmaTankFilled

