- type: job
  id: VaultEngineer
  name: job-name-vault-engineer
  description: job-description-vault-engineer
  # Forge-Change-Start
  setPreference: true
  overrideConsoleVisibility: true
  canBeAntag: false
  playTimeTracker: VaultEngineer
  # Forge-Change-End
  requirements:
  # Forge-Change-Del - !type:MinPlayersRequirement
    # Forge-Change-Del min: 20 # Forge-Change
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterDepartmentTimeRequirement
    department: Vault
    min: 7200 # 2 hours
  # Forge-Change-Del setPreference: true
  # Forge-Change-Del overrideConsoleVisibility: true
  # Forge-Change-Del canBeAntag: false
  # Forge-Change-Del playTimeTracker: VaultEngineer
  # Forge-Change-Start
  - !type:MinPlayersRequirement
    min: 20 # Forge-Change
  # Forge-Change-End
  startingGear: VaultEngineerGear
  alwaysUseSpawner: true
  icon: "JobIconVaultEngineer" # Forge-Change
  supervisors: job-supervisors-vault
  access:
  - VaultDweller
  - VaultEngineer
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - Vault

- type: startingGear
  id: VaultEngineerGear
  equipment:
    head: ClothingHeadHatHardhatYellow
    jumpsuit: N14ClothingUniformJumpsuitVault14
    back: N14ClothingBackpackVaultBlue # Forge-Change
    shoes: N14ClothingBootsBlack
    outerClothing: ClothingOuterVestHazard
    id: N14VaultEngineerPDA
    belt: N14ClothingBeltUtilityFilled
    ears: N14ClothingHeadsetVaultDweller
    gloves: ClothingHandsGlovesColorYellow # Forge-Change
  storage: # Forge-Change
    back:
    - N14CleanGauze10
    - N14CurrencyPrewarMoney100

- type: playTimeTracker
  id: VaultEngineer
