using System.Linq;
using Content.Client._NC.Trade.Controls;
using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Trade;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._NC.Trade;


[GenerateTypedNameReferences]
public sealed partial class NcStoreMenu : FancyWindow
{
    private const string CatIdReady = "nc.internal.category.ready";
    private const string CatIdCrate = "nc.internal.category.crate";
    private readonly Dictionary<string, int> _balancesByCurrency = new();
    private readonly UiStateBinder _binder;
    private readonly NcCategoryBar _buyCategoryBar;
    private readonly List<string> _buyCats = new();
    private readonly NcListingGrid _buyGrid;
    private readonly List<StoreListingStaticData> _catalog = new();
    private readonly Dictionary<string, int> _crateUnitsById = new();
    private readonly List<StoreListingData> _items = new();
    private readonly Dictionary<string, int> _massSellTotals = new();
    private readonly Dictionary<string, int> _ownedById = new();
    private readonly IPrototypeManager _proto;
    private readonly Dictionary<string, int> _remainingById = new();
    private readonly HashSet<string> _scratchAvailableIds = new();
    private readonly HashSet<string> _scratchBuyCatSet = new();
    private readonly List<StoreListingData> _scratchReadyItems = new();
    private readonly HashSet<string> _scratchSellCatSet = new();
    private readonly NcCategoryBar _sellCategoryBar;
    private readonly List<string> _sellCats = new();
    private readonly NcListingGrid _sellGrid;
    private readonly List<string> _visibleBuyIds = new();
    private readonly List<string> _visibleSellIds = new();
    private readonly HashSet<string> _visibleUnionScratch = new();
    private int _lastVisibleIdsSig;
    private readonly SpriteSystem _sprites;
    private string _buyCat = string.Empty;
    private bool _disposed;
    private bool _hasBuyTab;
    private bool _hasContractsTab;
    private bool _hasSellTab;
    private string _search = string.Empty;
    private string _searchLower = string.Empty;
    private string _sellCat = string.Empty;
    private Control? _tabBuy;
    private Control? _tabContracts;
    private bool _tabsCaptured;
    private Control? _tabSell;
    public Action<string>? OnContractClaim;
    private const int CategoryPanelMin = 180;
    private const int CategoryPanelMax = 360;
    private const float ApproxCharPx = 7.5f;
    private const int ExtraPaddingPx = 46;


    public NcStoreMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        TabContainer.SetTabTitle(TabBuy, Loc.GetString("nc-store-tab-buy"));
        TabContainer.SetTabTitle(TabSell, Loc.GetString("nc-store-tab-sell"));
        TabContainer.SetTabTitle(TabContracts, Loc.GetString("nc-store-tab-contracts"));
        _sprites = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
        _proto = IoCManager.Resolve<IPrototypeManager>();

        Header.BindServices(_proto, _sprites);

        _buyGrid = new(StoreMode.Buy, _proto, _sprites);
        _sellGrid = new(StoreMode.Sell, _proto, _sprites);

        _buyGrid.VisibleIdsChanged += ids =>
        {
            _visibleBuyIds.Clear();
            _visibleBuyIds.AddRange(ids);
            EmitVisibleListingIdsChanged();
        };

        _sellGrid.VisibleIdsChanged += ids =>
        {
            _visibleSellIds.Clear();
            _visibleSellIds.AddRange(ids);
            EmitVisibleListingIdsChanged();
        };

        _buyCategoryBar = new();
        _sellCategoryBar = new();

        _buyCategoryBar.Configure(GetCategoryDisplayName, GetCategoryToolTip);
        _sellCategoryBar.Configure(GetCategoryDisplayName, GetCategoryToolTip);

        _buyCategoryBar.OnSelectedChanged += catId =>
        {
            if (_disposed)
                return;

            _buyCat = catId;
            _buyGrid.ResetPaging();
            RefreshListings();
        };

        _sellCategoryBar.OnSelectedChanged += catId =>
        {
            if (_disposed)
                return;

            _sellCat = catId;
            _sellGrid.ResetPaging();
            RefreshListings();
        };

        _buyGrid.HorizontalExpand = true;
        _sellGrid.HorizontalExpand = true;

        BuyListingsContainer.Children.Clear();
        BuyListingsContainer.AddChild(_buyGrid);

        BuyCategoryListContainer.Children.Clear();
        BuyCategoryListContainer.AddChild(_buyCategoryBar);

        SellListingsContainer.Children.Clear();
        SellListingsContainer.AddChild(_sellGrid);

        SellCategoryListContainer.Children.Clear();
        SellCategoryListContainer.AddChild(_sellCategoryBar);

        Header.OnSearchChanged += text =>
        {
            if (_disposed)
                return;

            _search = text;
            _searchLower = text.ToLowerInvariant();
            _buyGrid.ResetPaging();
            _sellGrid.ResetPaging();
            OnSearchChanged?.Invoke(_search);
            RefreshListings();
        };

        MassSellPulledCrateButton.Disabled = true;
        MassSellPulledCrateButton.ClipText = true;
        MassSellPulledCrateButton.Text = Loc.GetString("nc-store-mass-sell-button");
        MassSellPulledCrateButton.ToolTip = Loc.GetString("nc-store-mass-sell-tooltip");
        MassSellPulledCrateButton.OnPressed += _ => OnMassSellPulledCrate?.Invoke();

        _binder = new(this);
    }

    private string GetCategoryDisplayName(string catId) =>
        catId switch
        {
            CatIdReady => Loc.GetString("nc-store-cat-ready-short"),
            CatIdCrate => Loc.GetString("nc-store-cat-crate-short"),
            _ => catId
        };

    private string GetCategoryToolTip(string catId) =>
        catId switch
        {
            CatIdReady => Loc.GetString("nc-store-cat-ready-full"),
            CatIdCrate => Loc.GetString("nc-store-cat-crate-full"),
            _ => catId
        };

    public event Action<string>? OnSearchChanged;
    public event Action<StoreListingData, int>? OnBuyPressed;
    public event Action<StoreListingData, int>? OnSellPressed;
    public event Action? OnMassSellPulledCrate;
    public event Action<string[]>? OnVisibleListingIdsChanged;

    private void EmitVisibleListingIdsChanged()
    {
        if (OnVisibleListingIdsChanged == null)
            return;

        _visibleUnionScratch.Clear();

        for (var i = 0; i < _visibleBuyIds.Count; i++)
        {
            var id = _visibleBuyIds[i];
            if (!string.IsNullOrWhiteSpace(id))
                _visibleUnionScratch.Add(id);
        }

        for (var i = 0; i < _visibleSellIds.Count; i++)
        {
            var id = _visibleSellIds[i];
            if (!string.IsNullOrWhiteSpace(id))
                _visibleUnionScratch.Add(id);
        }

        var arr = _visibleUnionScratch.ToArray();
        Array.Sort(arr, static (a, b) => string.CompareOrdinal(a, b));

        var sig = 17;
        for (var i = 0; i < arr.Length; i++)
            sig = unchecked(sig * 31 + arr[i].GetHashCode());

        if (sig == _lastVisibleIdsSig)
            return;

        _lastVisibleIdsSig = sig;
        OnVisibleListingIdsChanged(arr);
    }

    private int GetBalanceForCurrency(string currencyId)
    {
        if (string.IsNullOrWhiteSpace(currencyId))
            return 0;

        return _balancesByCurrency.GetValueOrDefault(currencyId, 0);
    }

    public void SetBalancesByCurrency(Dictionary<string, int> balances)
    {
        _balancesByCurrency.Clear();

        foreach (var (cur, amt) in balances)
        {
            if (string.IsNullOrWhiteSpace(cur))
                continue;

            _balancesByCurrency[cur] = amt;
        }

        Header.SetBalances(_balancesByCurrency);
    }


    public void SetMassSellTotals(Dictionary<string, int> totals)
    {
        _massSellTotals.Clear();
        foreach (var (cur, amt) in totals)
            _massSellTotals[cur] = amt;
        MassSellPulledCrateButton.Text = Loc.GetString("nc-store-mass-sell-button");
        MassSellPulledCrateButton.ClipText = true;

        if (_massSellTotals.Count == 0)
        {
            MassSellPulledCrateButton.ToolTip = Loc.GetString("nc-store-mass-sell-tooltip");
            MassSellPulledCrateButton.Disabled = true;
            return;
        }

        MassSellPulledCrateButton.Disabled = false;

        var parts = _massSellTotals
            .Where(p => p.Value > 0 && !string.IsNullOrWhiteSpace(p.Key))
            .Select(p => Loc.GetString(
                "nc-store-currency-format",
                ("amount", p.Value),
                ("currency", CurrencyName(p.Key))))
            .ToList();

        var full = parts.Count > 0 ? string.Join(", ", parts) : "—";

        MassSellPulledCrateButton.ToolTip = Loc.GetString("nc-store-mass-sell-tooltip-with-reward", ("reward", full));
    }

    private void CaptureTabsIfNeeded()
    {
        if (_tabsCaptured)
            return;

        _tabsCaptured = true;

        _tabBuy = TabBuy;
        _tabSell = TabSell;
        _tabContracts = TabContracts;
    }


    private void EnsureTab(Control? tab, bool shouldExist)
    {
        if (Tabs == null || tab == null)
            return;

        var exists = Tabs.Children.Contains(tab);

        if (shouldExist && !exists)
            Tabs.AddChild(tab);
        else if (!shouldExist && exists)
            Tabs.RemoveChild(tab);
    }


    private void ApplyTabsVisibility()
    {
        if (Tabs == null)
            return;

        CaptureTabsIfNeeded();

        EnsureTab(_tabBuy, _hasBuyTab);
        EnsureTab(_tabSell, _hasSellTab);
        EnsureTab(_tabContracts, _hasContractsTab);

        var count = Tabs.ChildCount;
        if (count <= 0)
            return;

        var curIndex = Tabs.CurrentTab;
        if (curIndex < 0 || curIndex >= count)
            Tabs.CurrentTab = 0;
    }


    public void PopulateCatalog(
        List<StoreListingStaticData> listings,
        bool hasBuyTab,
        bool hasSellTab,
        bool hasContractsTab
    ) =>
        _binder.PopulateCatalog(listings, hasBuyTab, hasSellTab, hasContractsTab);


    private void UpdateHeaderVisibility() => Header.Visible = _hasBuyTab || _hasSellTab;

    private void RebuildCategoriesFromCatalog()
    {
        _buyCats.Clear();
        _sellCats.Clear();

        _scratchBuyCatSet.Clear();
        _scratchSellCatSet.Clear();

        for (var i = 0; i < _catalog.Count; i++)
        {
            var it = _catalog[i];
            if (string.IsNullOrWhiteSpace(it.Category))
                continue;

            if (it.Mode == StoreMode.Buy)
                _scratchBuyCatSet.Add(it.Category);
            else if (it.Mode == StoreMode.Sell)
                _scratchSellCatSet.Add(it.Category);
        }

        _buyCats.AddRange(_scratchBuyCatSet);
        _sellCats.AddRange(_scratchSellCatSet);

        _buyCats.Sort(static (a, b) => string.Compare(a, b, StringComparison.CurrentCulture));
        _sellCats.Sort(static (a, b) => string.Compare(a, b, StringComparison.CurrentCulture));

        if (!_buyCats.Contains(_buyCat))
            _buyCat = string.Empty;
        if (!_sellCats.Contains(_sellCat))
            _sellCat = string.Empty;

        BuildCategoryButtons();
    }

    private void UpdateVirtualSellCategories()
    {
        var hasReady = false;
        var hasCrate = false;

        for (var i = 0; i < _items.Count; i++)
        {
            var it = _items[i];

            if (!hasReady && it is { Mode: StoreMode.Sell, Category: CatIdReady, })
                hasReady = true;

            if (!hasCrate && it is { Mode: StoreMode.Sell, Category: CatIdCrate, })
                hasCrate = true;

            if (hasReady && hasCrate)
                break;
        }

        _sellCats.Remove(CatIdReady);
        _sellCats.Remove(CatIdCrate);

        var insertIndex = 0;
        if (hasReady)
            _sellCats.Insert(insertIndex++, CatIdReady);

        if (hasCrate)
            _sellCats.Insert(insertIndex, CatIdCrate);

        if (!_sellCats.Contains(_sellCat))
            _sellCat = string.Empty;

        BuildCategoryButtons();
    }

    public void ApplyDynamicState(
        Dictionary<string, int> balancesByCurrency,
        Dictionary<string, int> remainingById,
        Dictionary<string, int> ownedById,
        Dictionary<string, int> crateUnitsById,
        Dictionary<string, int> massTotals,
        bool hasBuyTab,
        bool hasSellTab,
        bool hasContractsTab,
        List<ContractClientData> contracts
    ) =>
        _binder.ApplyDynamicState(
            balancesByCurrency,
            remainingById,
            ownedById,
            crateUnitsById,
            massTotals,
            hasBuyTab,
            hasSellTab,
            hasContractsTab,
            contracts);


    private void RebuildItemsFromCatalogAndDynamic()
    {
        _items.Clear();

        for (var i = 0; i < _catalog.Count; i++)
        {
            var s = _catalog[i];

            var remaining = _remainingById.GetValueOrDefault(s.Id, -1);
            var owned = _ownedById.GetValueOrDefault(s.Id, 0);

            _items.Add(
                new(
                    s.Id,
                    StoreListingFlavor.Base,
                    s.ProductEntity,
                    s.BasePrice,
                    s.Category,
                    s.CurrencyId,
                    s.Mode,
                    owned,
                    remaining,
                    s.UnitsPerPurchase));
        }

        var baseCount = _items.Count;
        _scratchReadyItems.Clear();

        for (var i = 0; i < baseCount; i++)
        {
            var d = _items[i];
            if (d.Mode != StoreMode.Sell)
                continue;

            if (d.Owned <= 0)
                continue;

            if (d.Remaining == 0)
                continue;

            _scratchReadyItems.Add(
                new(
                    d.ListingId,
                    StoreListingFlavor.Ready,
                    d.ProductEntity,
                    d.Price,
                    CatIdReady,
                    d.CurrencyId,
                    d.Mode,
                    d.Owned,
                    d.Remaining,
                    d.UnitsPerPurchase));
        }

        if (_scratchReadyItems.Count > 0)
            _items.AddRange(_scratchReadyItems);

        if (_crateUnitsById.Count > 0)
        {
            for (var i = 0; i < _catalog.Count; i++)
            {
                var s = _catalog[i];
                if (s.Mode != StoreMode.Sell)
                    continue;

                if (!_crateUnitsById.TryGetValue(s.Id, out var take) || take <= 0)
                    continue;

                var remaining = _remainingById.GetValueOrDefault(s.Id, -1);

                _items.Add(
                    new(
                        s.Id,
                        StoreListingFlavor.Crate,
                        s.ProductEntity,
                        s.BasePrice,
                        CatIdCrate,
                        s.CurrencyId,
                        StoreMode.Sell,
                        take,
                        remaining,
                        s.UnitsPerPurchase));
            }
        }

        _scratchAvailableIds.Clear();
        for (var i = 0; i < _items.Count; i++)
            _scratchAvailableIds.Add(_items[i].Id);

        _buyGrid.SyncAvailableIds(_scratchAvailableIds);
        _sellGrid.SyncAvailableIds(_scratchAvailableIds);
    }

    public void PopulateContracts(List<ContractClientData>? list)
    {
        var contractList = ContractList;
        if (contractList == null)
            return;

        contractList.RemoveAllChildren();

        if (list == null || list.Count == 0)
        {
            contractList.AddChild(
                new Label
                {
                    Text = Loc.GetString("nc-store-contracts-empty"),
                    HorizontalAlignment = HAlignment.Center,
                    Margin = new(0, 8, 0, 0)
                });

            ApplyTabsVisibility();
            return;
        }

        var ordered = list
            .OrderBy(x => x.Difficulty switch
            {
                "Easy" => 0,
                "Medium" => 1,
                "Hard" => 2,
                _ => 99
            })
            .ThenBy(x => x.Name)
            .ThenBy(x => x.Id)
            .ToList();

        foreach (var c in ordered)
        {
            var card = new NcContractCard(c, _proto, _sprites, IoCManager.Resolve<IEntityManager>());
            card.OnClaim += id => OnContractClaim?.Invoke(id);
            contractList.AddChild(card);
        }

        ApplyTabsVisibility();
    }

    private void RefreshListings()
    {
        var hasSearch = !string.IsNullOrWhiteSpace(_search);

        var buyCount = _buyGrid.Refresh(
            _items,
            _buyCat,
            _searchLower,
            GetBalanceForCurrency,
            (d, qty) => OnBuyPressed?.Invoke(d, qty));

        var sellCount = _sellGrid.Refresh(
            _items,
            _sellCat,
            _searchLower,
            _ => int.MaxValue,
            (d, qty) => OnSellPressed?.Invoke(d, qty));

        BuyCategoryHeader.Visible = !string.IsNullOrEmpty(_buyCat) || hasSearch;
        SellCategoryHeader.Visible = !string.IsNullOrEmpty(_sellCat) || hasSearch;

        if (BuyCategoryHeader.Visible)
        {
            BuyCategoryHeader.Text = !string.IsNullOrEmpty(_buyCat)
                ? GetCategoryDisplayName(_buyCat)
                : Loc.GetString("nc-store-search-results-buy", ("count", buyCount));
        }
        else
            BuyCategoryHeader.Text = string.Empty;

        if (SellCategoryHeader.Visible)
        {
            SellCategoryHeader.Text = !string.IsNullOrEmpty(_sellCat)
                ? GetCategoryDisplayName(_sellCat)
                : Loc.GetString("nc-store-search-results-sell", ("count", sellCount));
        }
        else
            SellCategoryHeader.Text = string.Empty;
    }

    private void BuildCategoryButtons()
    {
        _buyCategoryBar.SetCategories(_buyCats, _buyCat);
        _sellCategoryBar.SetCategories(_sellCats, _sellCat);
    }

    private string CurrencyName(string? currencyId)
    {
        if (string.IsNullOrWhiteSpace(currencyId))
            return string.Empty;

        if (_proto.TryIndex<StackPrototype>(currencyId, out var stackProto) &&
            _proto.TryIndex<EntityPrototype>(stackProto.Spawn, out var currencyEnt))
            return currencyEnt.Name;

        return currencyId;
    }

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        _disposed = true;
        _buyGrid.ClearCaches();
        _sellGrid.ClearCaches();
        _catalog.Clear();
        _items.Clear();

        base.Dispose(disposing);
    }
}
