using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Trade;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;


namespace Content.Client._NC.Trade;


[GenerateTypedNameReferences]
public sealed partial class NcStoreMenu : FancyWindow
{
    private const int SearchDebounceMs = 120;
    private const string CatIdReady = "__READY__";
    private const string CatIdCrate = "__CRATE__";
    private static readonly Color CatSelected = new(0xD9, 0xA4, 0x41);
    private static readonly Color CatIdle = new(0x7C, 0x66, 0x24);
    private readonly Dictionary<string, int> _balancesByCurrency = new();
    private readonly Dictionary<string, Button> _buyCatButtons = new();
    private readonly List<string> _buyCats = new();
    private readonly NcListingGrid _buyGrid;
    private readonly List<StoreListingStaticData> _catalog = new();
    private readonly Dictionary<string, int> _crateUnitsById = new();
    private readonly TextureRect? _currencyIcon;
    private readonly BoxContainer? _headerBar;
    private readonly List<StoreListingData> _items = new();
    private readonly Dictionary<string, int> _massSellTotals = new();
    private readonly Dictionary<string, int> _ownedById = new();
    private readonly IPrototypeManager _proto;
    private readonly Dictionary<string, int> _remainingById = new();
    private readonly Dictionary<string, Button> _sellCatButtons = new();
    private readonly List<string> _sellCats = new();
    private readonly NcListingGrid _sellGrid;
    private readonly SpriteSystem _sprites;
    private readonly Dictionary<string, StoreListingStaticData> _staticById = new();
    private int _balance;
    private string _buyCat = string.Empty;
    private bool _disposed;
    private bool _hasBuyTab;
    private bool _hasContractsTab;
    private bool _hasSellTab;
    private string _search = string.Empty;
    private string _searchLower = string.Empty;
    private int _searchToken;
    private string _sellCat = string.Empty;
    private Control? _tabBuy;
    private Control? _tabContracts;
    private bool _tabsCaptured;
    private Control? _tabSell;
    public Action<string>? OnContractClaim;


    public NcStoreMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        TabContainer.SetTabTitle(TabBuy, Loc.GetString("nc-store-tab-buy"));
        TabContainer.SetTabTitle(TabSell, Loc.GetString("nc-store-tab-sell"));
        TabContainer.SetTabTitle(TabContracts, Loc.GetString("nc-store-tab-contracts"));
        _currencyIcon = FindControl<TextureRect>("CurrencyIcon");
        _headerBar = FindControl<BoxContainer>("HeaderBar");
        _sprites = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
        _proto = IoCManager.Resolve<IPrototypeManager>();

        _buyGrid = new(StoreMode.Buy, _proto, _sprites);
        _sellGrid = new(StoreMode.Sell, _proto, _sprites);

        _buyGrid.HorizontalExpand = true;
        _sellGrid.HorizontalExpand = true;

        BuyListingsContainer.Children.Clear();
        BuyListingsContainer.AddChild(_buyGrid);

        SellListingsContainer.Children.Clear();
        SellListingsContainer.AddChild(_sellGrid);

        SearchBar.OnTextChanged += _ =>
        {
            if (_disposed)
                return;

            _search = SearchBar.Text.Trim();
            _searchLower = _search.ToLowerInvariant();
            var token = ++_searchToken;

            Timer.Spawn(
                TimeSpan.FromMilliseconds(SearchDebounceMs),
                () =>
                {
                    if (token != _searchToken)
                        return;

                    if (_disposed)
                        return;

                    _buyGrid.ResetPaging();
                    _sellGrid.ResetPaging();
                    OnSearchChanged?.Invoke(_search);
                    RefreshListings();
                });
        };

        BalanceInfo.SetMarkup("[font size=14][color=yellow]0[/color][/font]");

        MassSellPulledCrateButton.Disabled = true;
        MassSellPulledCrateButton.ClipText = true;
        MassSellPulledCrateButton.Text = Loc.GetString("nc-store-mass-sell-button");
        MassSellPulledCrateButton.ToolTip = Loc.GetString("nc-store-mass-sell-tooltip");
        MassSellPulledCrateButton.OnPressed += _ => OnMassSellPulledCrate?.Invoke();
    }

    private string GetCategoryDisplayName(string catId) =>
        catId switch
        {
            CatIdReady => Loc.GetString("nc-store-cat-ready-short"),
            CatIdCrate => Loc.GetString("nc-store-cat-crate-short"),
            _ => catId
        };

    private string GetCategoryToolTip(string catId) =>
        catId switch
        {
            CatIdReady => Loc.GetString("nc-store-cat-ready-full"),
            CatIdCrate => Loc.GetString("nc-store-cat-crate-full"),
            _ => catId
        };

    public event Action<string>? OnSearchChanged;
    public event Action<StoreListingData, int>? OnBuyPressed;
    public event Action<StoreListingData, int>? OnSellPressed;
    public event Action? OnMassSellPulledCrate;


    public void SetBalance(int balance)
    {
        _balance = balance;
        BalanceInfo.SetMarkup($"[font size=14][color=yellow]{balance}[/color][/font]");
    }

    private int GetBalanceForCurrency(string currencyId)
    {
        if (string.IsNullOrWhiteSpace(currencyId))
            return 0;

        return _balancesByCurrency.GetValueOrDefault(currencyId, 0);
    }

    private void UpdateBalanceHeader()
    {
        if (_balancesByCurrency.Count == 0)
        {
            SetBalance(0);
            return;
        }

        string? displayCurrency;
        int displayAmount;

        if (_balancesByCurrency.Count == 1)
        {
            var kv = _balancesByCurrency.First();
            displayCurrency = kv.Key;
            displayAmount = kv.Value;
        }
        else
        {
            string? bestKey = null;
            var bestValue = int.MinValue;

            foreach (var (key, value) in _balancesByCurrency)
                if (bestKey == null ||
                    value > bestValue ||
                    value == bestValue && string.CompareOrdinal(key, bestKey) < 0)
                {
                    bestKey = key;
                    bestValue = value;
                }

            displayCurrency = bestKey;
            displayAmount = _balancesByCurrency.Values.Sum();
        }

        BalanceInfo.SetMarkup($"[font size=14][color=yellow]{displayAmount}[/color][/font]");
        if (_currencyIcon != null && !string.IsNullOrEmpty(displayCurrency))
        {
            if (_proto.TryIndex<StackPrototype>(displayCurrency, out var stackProto) &&
                _proto.TryIndex<EntityPrototype>(stackProto.Spawn, out var entProto))
            {
                var icon = _sprites.GetPrototypeIcon(entProto).Default;
                _currencyIcon.Texture = icon;
            }
        }
    }

    public void SetBalancesByCurrency(Dictionary<string, int> balances)
    {
        _balancesByCurrency.Clear();

        foreach (var (cur, amt) in balances)
        {
            if (string.IsNullOrWhiteSpace(cur))
                continue;

            _balancesByCurrency[cur] = amt;
        }

        UpdateBalanceHeader();
    }


    public void SetMassSellTotals(Dictionary<string, int> totals)
    {
        _massSellTotals.Clear();
        foreach (var (cur, amt) in totals)
            _massSellTotals[cur] = amt;
        MassSellPulledCrateButton.Text = Loc.GetString("nc-store-mass-sell-button");
        MassSellPulledCrateButton.ClipText = true;

        if (_massSellTotals.Count == 0)
        {
            MassSellPulledCrateButton.ToolTip = Loc.GetString("nc-store-mass-sell-tooltip");
            MassSellPulledCrateButton.Disabled = true;
            return;
        }

        MassSellPulledCrateButton.Disabled = false;

        var parts = _massSellTotals
            .Where(p => p.Value > 0 && !string.IsNullOrWhiteSpace(p.Key))
            .Select(p => Loc.GetString(
                "nc-store-currency-format",
                ("amount", p.Value),
                ("currency", CurrencyName(p.Key))))
            .ToList();

        var full = parts.Count > 0 ? string.Join(", ", parts) : "—";

        MassSellPulledCrateButton.ToolTip = Loc.GetString("nc-store-mass-sell-tooltip-with-reward", ("reward", full));
    }

    private void CaptureTabsIfNeeded()
    {
        if (_tabsCaptured)
            return;

        _tabsCaptured = true;

        _tabBuy = TabBuy;
        _tabSell = TabSell;
        _tabContracts = TabContracts;
    }


    private void EnsureTab(Control? tab, bool shouldExist)
    {
        if (Tabs == null || tab == null)
            return;

        var exists = Tabs.Children.Contains(tab);

        if (shouldExist && !exists)
            Tabs.AddChild(tab);
        else if (!shouldExist && exists)
            Tabs.RemoveChild(tab);
    }


    private void ApplyTabsVisibility()
    {
        if (Tabs == null)
            return;

        CaptureTabsIfNeeded();

        EnsureTab(_tabBuy, _hasBuyTab);
        EnsureTab(_tabSell, _hasSellTab);
        EnsureTab(_tabContracts, _hasContractsTab);

        var count = Tabs.ChildCount;
        if (count <= 0)
            return;

        var curIndex = Tabs.CurrentTab;
        if (curIndex < 0 || curIndex >= count)
            Tabs.CurrentTab = 0;
    }


    public void PopulateCatalog(
        List<StoreListingStaticData> listings,
        bool hasBuyTab,
        bool hasSellTab,
        bool hasContractsTab
    )
    {
        _hasBuyTab = hasBuyTab;
        _hasSellTab = hasSellTab;
        _hasContractsTab = hasContractsTab;

        ApplyTabsVisibility();
        UpdateHeaderVisibility();

        _catalog.Clear();
        _staticById.Clear();

        foreach (var s in listings)
        {
            if (string.IsNullOrWhiteSpace(s.Id) || string.IsNullOrWhiteSpace(s.ProductEntity))
                continue;

            _catalog.Add(s);
            _staticById[s.Id] = s;
        }

        _buyGrid.PrepareSearchIndex(_catalog.Select(x => x.ProductEntity));
        _sellGrid.PrepareSearchIndex(_catalog.Select(x => x.ProductEntity));
        RebuildCategoriesFromCatalog();

        _buyGrid.ResetPaging();
        _sellGrid.ResetPaging();
        RefreshListings();
    }

    private void UpdateHeaderVisibility()
    {
        if (_headerBar == null)
            return;
        _headerBar.Visible = _hasBuyTab || _hasSellTab;
    }

    private void RebuildCategoriesFromCatalog()
    {
        _buyCats.Clear();
        _sellCats.Clear();

        _buyCats.AddRange(
            _catalog.Where(i => i.Mode == StoreMode.Buy).Select(i => i.Category).Distinct().OrderBy(c => c));
        _sellCats.AddRange(
            _catalog.Where(i => i.Mode == StoreMode.Sell).Select(i => i.Category).Distinct().OrderBy(c => c));
        if (!_buyCats.Contains(_buyCat))
            _buyCat = string.Empty;
        if (!_sellCats.Contains(_sellCat))
            _sellCat = string.Empty;

        BuildCategoryButtons();
    }

    private void UpdateVirtualSellCategories()
    {
        var hasReady = _items.Any(i => i is { Mode: StoreMode.Sell, Category: CatIdReady, });
        var hasCrate = _items.Any(i => i is { Mode: StoreMode.Sell, Category: CatIdCrate, });

        _sellCats.Remove(CatIdReady);
        _sellCats.Remove(CatIdCrate);

        var insertIndex = 0;
        if (hasReady)
            _sellCats.Insert(insertIndex++, CatIdReady);

        if (hasCrate)
            _sellCats.Insert(insertIndex, CatIdCrate);

        if (!_sellCats.Contains(_sellCat))
            _sellCat = string.Empty;

        BuildCategoryButtons();
    }

    public void ApplyDynamicState(
        Dictionary<string, int> balancesByCurrency,
        Dictionary<string, int> remainingById,
        Dictionary<string, int> ownedById,
        Dictionary<string, int> crateUnitsById,
        Dictionary<string, int> massTotals,
        bool hasBuyTab,
        bool hasSellTab,
        bool hasContractsTab,
        List<ContractClientData> contracts
    )
    {
        _hasBuyTab = hasBuyTab;
        _hasSellTab = hasSellTab;
        _hasContractsTab = hasContractsTab;
        ApplyTabsVisibility();
        UpdateHeaderVisibility();

        SetBalancesByCurrency(balancesByCurrency);

        _remainingById.Clear();
        foreach (var (k, v) in remainingById)
            _remainingById[k] = v;

        _ownedById.Clear();
        foreach (var (k, v) in ownedById)
            _ownedById[k] = v;

        _crateUnitsById.Clear();
        foreach (var (k, v) in crateUnitsById)
            _crateUnitsById[k] = v;

        SetMassSellTotals(massTotals);
        PopulateContracts(contracts);

        RebuildItemsFromCatalogAndDynamic();
        UpdateVirtualSellCategories();
        RefreshListings();
    }

    private void RebuildItemsFromCatalogAndDynamic()
    {
        _items.Clear();

        foreach (var s in _catalog)
        {
            var remaining = _remainingById.GetValueOrDefault(s.Id, -1);
            var owned = _ownedById.GetValueOrDefault(s.Id, 0);

            _items.Add(
                new(
                    s.Id,
                    s.ProductEntity,
                    s.BasePrice,
                    s.Category,
                    s.CurrencyId,
                    s.Mode,
                    owned,
                    remaining));
        }

        var ready = _items
            .Where(d => d is { Mode: StoreMode.Sell, Owned: > 0, } && d.Remaining != 0)
            .Select(d => new StoreListingData(
                d.Id + "__ready",
                d.ProductEntity,
                d.Price,
                CatIdReady,
                d.CurrencyId,
                d.Mode,
                d.Owned,
                d.Remaining))
            .ToList();

        if (ready.Count > 0)
            _items.AddRange(ready);

        if (_crateUnitsById.Count > 0)
        {
            foreach (var s in _catalog.Where(x => x.Mode == StoreMode.Sell))
            {
                if (!_crateUnitsById.TryGetValue(s.Id, out var take) || take <= 0)
                    continue;

                var remaining = _remainingById.GetValueOrDefault(s.Id, 0);

                _items.Add(
                    new(
                        s.Id + "__crate",
                        s.ProductEntity,
                        s.BasePrice,
                        CatIdCrate,
                        s.CurrencyId,
                        StoreMode.Sell,
                        take,
                        remaining));
            }
        }

        var ids = _items.Select(i => i.Id).ToHashSet();
        _buyGrid.SyncAvailableIds(ids);
        _sellGrid.SyncAvailableIds(ids);
    }


    public void Populate(List<StoreListingData> list)
    {
        _items.Clear();
        _items.AddRange(list);

        _buyGrid.PrepareSearchIndex(_items.Select(x => x.ProductEntity));
        _sellGrid.PrepareSearchIndex(_items.Select(x => x.ProductEntity));

        var ids = _items.Select(i => i.Id).ToHashSet();
        _buyGrid.SyncAvailableIds(ids);
        _sellGrid.SyncAvailableIds(ids);

        _buyCats.Clear();
        _sellCats.Clear();

        _buyCats.AddRange(
            list.Where(i => i.Mode == StoreMode.Buy)
                .Select(i => i.Category)
                .Distinct()
                .OrderBy(c => c));

        _sellCats.AddRange(
            list.Where(i => i.Mode == StoreMode.Sell)
                .Select(i => i.Category)
                .Distinct()
                .OrderBy(c => c));
        if (_items.Any(i => i is { Mode: StoreMode.Sell, Category: CatIdReady, }))
        {
            _sellCats.Remove(CatIdReady);
            _sellCats.Insert(0, CatIdReady);
        }

        if (!_buyCats.Contains(_buyCat))
            _buyCat = string.Empty;
        if (!_sellCats.Contains(_sellCat))
            _sellCat = string.Empty;

        BuildCategoryButtons();
        _buyGrid.ResetPaging();
        _sellGrid.ResetPaging();
        RefreshListings();
    }

    public void PopulateContracts(List<ContractClientData>? list)
    {
        var contractList = ContractList;
        if (contractList == null)
            return;

        contractList.RemoveAllChildren();

        if (list == null || list.Count == 0)
        {
            contractList.AddChild(
                new Label
                {
                    Text = Loc.GetString("nc-store-contracts-empty"),
                    HorizontalAlignment = HAlignment.Center,
                    Margin = new(0, 8, 0, 0)
                });

            ApplyTabsVisibility();
            return;
        }

        var ordered = list
            .OrderBy(x => x.Difficulty switch
            {
                "Easy" => 0,
                "Medium" => 1,
                "Hard" => 2,
                _ => 99
            })
            .ThenBy(x => x.Name)
            .ThenBy(x => x.Id)
            .ToList();

        foreach (var c in ordered)
        {
            var card = new NcContractCard(c, _proto, _sprites);
            card.OnClaim += id => OnContractClaim?.Invoke(id);
            contractList.AddChild(card);
        }

        ApplyTabsVisibility();
    }

    private void RefreshListings()
    {
        var hasSearch = !string.IsNullOrWhiteSpace(_search);

        var buyCount = _buyGrid.Refresh(
            _items,
            _buyCat,
            _searchLower,
            GetBalanceForCurrency,
            (d, qty) => OnBuyPressed?.Invoke(d, qty));

        var sellCount = _sellGrid.Refresh(
            _items,
            _sellCat,
            _searchLower,
            _ => int.MaxValue,
            (d, qty) => OnSellPressed?.Invoke(d, qty));

        BuyCategoryHeader.Visible = !string.IsNullOrEmpty(_buyCat) || hasSearch;
        SellCategoryHeader.Visible = !string.IsNullOrEmpty(_sellCat) || hasSearch;

        if (BuyCategoryHeader.Visible)
        {
            BuyCategoryHeader.Text = !string.IsNullOrEmpty(_buyCat)
                ? GetCategoryDisplayName(_buyCat)
                : Loc.GetString("nc-store-search-results-buy", ("count", buyCount));
        }
        else
            BuyCategoryHeader.Text = string.Empty;

        if (SellCategoryHeader.Visible)
        {
            SellCategoryHeader.Text = !string.IsNullOrEmpty(_sellCat)
                ? GetCategoryDisplayName(_sellCat)
                : Loc.GetString("nc-store-search-results-sell", ("count", sellCount));
        }
        else
            SellCategoryHeader.Text = string.Empty;
    }

    private void BuildCategoryButtons()
    {
        SyncCategoryButtons(
            _buyCats,
            BuyCategoryListContainer,
            _buyCatButtons,
            _buyCat,
            cat =>
            {
                _buyCat = _buyCat == cat ? string.Empty : cat;
                UpdateCatVisuals(_buyCatButtons, _buyCat);

                _sellGrid.ResetPaging();
                RefreshListings();
            });

        SyncCategoryButtons(
            _sellCats,
            SellCategoryListContainer,
            _sellCatButtons,
            _sellCat,
            cat =>
            {
                _sellCat = _sellCat == cat ? string.Empty : cat;

                UpdateCatVisuals(_sellCatButtons, _sellCat);

                _sellGrid.ResetPaging();
                RefreshListings();
            });
    }


    private void UpdateCatVisuals(Dictionary<string, Button> buttons, string selectedCat)
    {
        foreach (var (cat, btn) in buttons)
        {
            var isSelected = cat == selectedCat;
            if (btn.Pressed != isSelected)
                btn.Pressed = isSelected;

            btn.ModulateSelfOverride = isSelected ? CatSelected : CatIdle;
        }
    }

    private Button CreateCategoryButton(string catId, Action<string> onClick)
    {
        var btn = new Button
        {
            Text = GetCategoryDisplayName(catId),
            ToggleMode = true,
            HorizontalExpand = true,
            ToolTip = GetCategoryToolTip(catId),
            ModulateSelfOverride = CatIdle
        };

        btn.OnPressed += _ => onClick(catId);
        btn.OnMouseEntered += _ =>
        {
            btn.ModulateSelfOverride = btn.Pressed
                ? Brighten(CatSelected, 1.2f)
                : Brighten(CatIdle, 1.2f);
        };

        btn.OnMouseExited += _ => { btn.ModulateSelfOverride = btn.Pressed ? CatSelected : CatIdle; };

        return btn;
    }

    private void SyncCategoryButtons(
        List<string> neededCats,
        Control parent,
        Dictionary<string, Button> registry,
        string selectedCat,
        Action<string> onClick
    )
    {
        var neededSet = neededCats.ToHashSet();
        var toRemove = registry.Keys.Where(k => !neededSet.Contains(k)).ToList();

        foreach (var key in toRemove)
        {
            var btn = registry[key];
            parent.RemoveChild(btn);
            registry.Remove(key);
        }

        foreach (var cat in neededCats)
        {
            if (registry.ContainsKey(cat))
                continue;

            var btn = CreateCategoryButton(cat, onClick);
            registry[cat] = btn;
            parent.AddChild(btn);
        }

        foreach (var cat in neededCats)
        {
            if (!registry.TryGetValue(cat, out var btn))
                continue;

            parent.RemoveChild(btn);
            parent.AddChild(btn);
        }

        foreach (var (cat, btn) in registry)
        {
            var isSelected = cat == selectedCat;
            if (btn.Pressed != isSelected)
            {
                btn.Pressed = isSelected;
                btn.ModulateSelfOverride = isSelected ? CatSelected : CatIdle;
            }
        }
    }

    private string CurrencyName(string? currencyId)
    {
        if (string.IsNullOrWhiteSpace(currencyId))
            return string.Empty;

        if (_proto.TryIndex<StackPrototype>(currencyId, out var stackProto) &&
            _proto.TryIndex<EntityPrototype>(stackProto.Spawn, out var currencyEnt))
            return currencyEnt.Name;

        return currencyId;
    }

    private static Color Brighten(Color c, float f) =>
        new(MathF.Min(c.R * f, 1f), MathF.Min(c.G * f, 1f), MathF.Min(c.B * f, 1f), c.A);

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        _disposed = true;
        _buyGrid.ClearCaches();
        _sellGrid.ClearCaches();
        _staticById.Clear();
        _catalog.Clear();
        _items.Clear();

        base.Dispose(disposing);
    }
}
