using System.Linq;
using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Trade;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;


namespace Content.Client._NC.Trade;


[GenerateTypedNameReferences]
public sealed partial class NcStoreMenu : FancyWindow
{
    private const int SearchDebounceMs = 120;
    private const int PageSize = 96;
    private const string CrateCategory = "Готово к продаже в ящике";

    private static readonly Color CatSelected = new(0xD9, 0xA4, 0x41);
    private static readonly Color CatIdle = new(0x7C, 0x66, 0x24);
    private readonly Dictionary<string, int> _balancesByCurrency = new();

    private readonly Dictionary<string, (NcStoreListingControl Ctrl, int Sig)> _buyCache = new();
    private readonly Dictionary<string, Button> _buyCatButtons = new();
    private readonly List<string> _buyCats = new();
    private readonly List<StoreListingData> _items = new();

    private readonly Dictionary<string, int> _massSellTotals = new();
    private readonly IPrototypeManager _proto;

    private readonly Dictionary<string, int> _qtyCache = new();
    private readonly Dictionary<string, string> _searchIndex = new();
    private readonly Dictionary<string, (NcStoreListingControl Ctrl, int Sig)> _sellCache = new();
    private readonly Dictionary<string, Button> _sellCatButtons = new();
    private readonly List<string> _sellCats = new();
    private readonly SpriteSystem _sprites;
    private int _balance;


    private string _buyCat = string.Empty;

    private bool _disposed;
    private bool _hasBuyTab;
    private bool _hasContractsTab;
    private bool _hasSellTab;

    private int _pageBuy = 1;
    private int _pageSell = 1;

    private string _search = string.Empty;
    private string _searchLower = string.Empty;
    private int _searchToken;
    private string _sellCat = string.Empty;
    private Control? _tabBuy;
    private Control? _tabContracts;
    private bool _tabsCaptured;
    private Control? _tabSell;

    public Action<string>? OnContractClaim;

    public NcStoreMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprites = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
        _proto = IoCManager.Resolve<IPrototypeManager>();

        SearchBar.OnTextChanged += _ =>
        {
            if (_disposed)
                return;

            _search = SearchBar.Text.Trim();
            _searchLower = _search.ToLowerInvariant();
            var token = ++_searchToken;

            Timer.Spawn(
                TimeSpan.FromMilliseconds(SearchDebounceMs),
                () =>
                {
                    if (token != _searchToken)
                        return;

                    if (_disposed)
                        return;

                    ResetPaging();
                    OnSearchChanged?.Invoke(_search);
                    RefreshListings();
                });
        };

        BalanceLabel.StyleClasses.Add(StyleNano.StyleClassLabelHeadingBigger);
        BalanceInfo.SetMarkup("[font size=14][color=yellow]0[/color][/font]");

        MassSellPulledCrateButton.Disabled = true;
        MassSellPulledCrateButton.ClipText = true; // один раз, тут
        MassSellPulledCrateButton.Text = "Продать содержимое";
        MassSellPulledCrateButton.ToolTip =
            "Для массовой продажи необходимо:\n• Ящик должен быть ЗАКРЫТ\n• Вы должны его тянуть";
        MassSellPulledCrateButton.OnPressed += _ => OnMassSellPulledCrate?.Invoke();
    }

    public event Action<string>? OnSearchChanged;
    public event Action<StoreListingData, int>? OnBuyPressed;
    public event Action<StoreListingData, int>? OnSellPressed;
    public event Action? OnMassSellPulledCrate;


    public void SetBalance(int balance)
    {
        _balance = balance;
        BalanceLabel.Text = balance.ToString();
        BalanceInfo.SetMarkup($"[font size=14][color=yellow]{balance}[/color][/font]");
    }

    private int GetBalanceForCurrency(string currencyId)
    {
        if (string.IsNullOrWhiteSpace(currencyId))
            return 0;

        return _balancesByCurrency.TryGetValue(currencyId, out var v) ? v : 0;
    }

    public void SetBalancesByCurrency(Dictionary<string, int> balances)
    {
        _balancesByCurrency.Clear();

        foreach (var (cur, amt) in balances)
        {
            if (string.IsNullOrWhiteSpace(cur))
                continue;

            _balancesByCurrency[cur] = amt;
        }
    }

    public void SetMassSellTotals(Dictionary<string, int> totals)
    {
        _massSellTotals.Clear();
        foreach (var (cur, amt) in totals)
            _massSellTotals[cur] = amt;
        MassSellPulledCrateButton.Text = "Продать содержимое";
        MassSellPulledCrateButton.ClipText = true;

        if (_massSellTotals.Count == 0)
        {
            MassSellPulledCrateButton.ToolTip =
                "Для массовой продажи необходимо:\n• Ящик должен быть ЗАКРЫТ\n• Вы должны его тянуть";
            MassSellPulledCrateButton.Disabled = true;
            return;
        }

        MassSellPulledCrateButton.Disabled = false;

        var parts = _massSellTotals
            .Where(p => p.Value > 0 && !string.IsNullOrWhiteSpace(p.Key))
            .Select(p => $"{p.Value} {CurrencyName(p.Key)}")
            .ToList();

        var full = parts.Count > 0 ? string.Join(", ", parts) : "—";

        MassSellPulledCrateButton.ToolTip =
            "Для массовой продажи необходимо:\n• Ящик должен быть ЗАКРЫТ\n• Вы должны его тянуть\n\n" +
            $"Получите: {full}";
    }

    private void CaptureTabsIfNeeded()
    {
        if (_tabsCaptured)
            return;

        _tabsCaptured = true;

        _tabBuy = Покупка;
        _tabSell = Продажа;
        _tabContracts = Контракты;
    }


    private void EnsureTab(Control? tab, bool shouldExist)
    {
        if (Tabs == null || tab == null)
            return;

        var exists = Tabs.Children.Contains(tab);

        if (shouldExist && !exists)
            Tabs.AddChild(tab);
        else if (!shouldExist && exists)
            Tabs.RemoveChild(tab);
    }


    private void ApplyTabsVisibility()
    {
        if (Tabs == null)
            return;

        CaptureTabsIfNeeded();

        EnsureTab(_tabBuy, _hasBuyTab);
        EnsureTab(_tabSell, _hasSellTab);
        EnsureTab(_tabContracts, _hasContractsTab);

        var count = Tabs.ChildCount;
        if (count <= 0)
            return;

        var curIndex = Tabs.CurrentTab;
        if (curIndex < 0 || curIndex >= count)
            Tabs.CurrentTab = 0;
    }


    public void ApplyState(
        int balance,
        Dictionary<string, int> balancesByCurrency,
        List<StoreListingData> list,
        Dictionary<string, int> massTotals,
        bool hasBuyTab,
        bool hasSellTab,
        bool hasContractsTab
    )
    {
        _hasBuyTab = hasBuyTab;
        _hasSellTab = hasSellTab;
        _hasContractsTab = hasContractsTab;

        ApplyTabsVisibility();


        SetBalance(balance);
        SetBalancesByCurrency(balancesByCurrency);
        SetMassSellTotals(massTotals);
        Populate(list);
    }


    public void Populate(List<StoreListingData> list)
    {
        _items.Clear();
        _items.AddRange(list);

        RebuildSearchIndex();

        var ids = _items.Select(i => i.Id).ToHashSet();
        foreach (var key in _qtyCache.Keys.Where(k => !ids.Contains(k)).ToList())
            _qtyCache.Remove(key);

        foreach (var key in _buyCache.Keys.Where(k => !ids.Contains(k)).ToList())
            _buyCache.Remove(key);
        foreach (var key in _sellCache.Keys.Where(k => !ids.Contains(k)).ToList())
            _sellCache.Remove(key);

        _buyCats.Clear();
        _sellCats.Clear();


        _buyCats.AddRange(
            list.Where(i => i.Mode == StoreMode.Buy)
                .Select(i => i.Category)
                .Distinct()
                .OrderBy(c => c));

        _sellCats.AddRange(
            list.Where(i => i.Mode == StoreMode.Sell)
                .Select(i => i.Category)
                .Distinct()
                .OrderBy(c => c));

        const string readyCat = "Готово к продаже";
        if (_items.Any(i => i.Mode == StoreMode.Sell && i.Category == readyCat))
        {
            _sellCats.Remove(readyCat);
            _sellCats.Insert(0, readyCat);
        }

        if (!_buyCats.Contains(_buyCat))
            _buyCat = string.Empty;
        if (!_sellCats.Contains(_sellCat))
            _sellCat = string.Empty;

        BuildCategoryButtons();
        ResetPaging();
        RefreshListings();
    }

    private void RebuildSearchIndex()
    {
        _searchIndex.Clear();

        foreach (var protoId in _items.Select(i => i.ProductEntity).Distinct())
        {
            if (string.IsNullOrWhiteSpace(protoId))
                continue;

            if (!_proto.TryIndex<EntityPrototype>(protoId, out var p))
                continue;

            var name = p.Name;
            var desc = p.Description;
            _searchIndex[protoId] = (name + "\n" + desc).ToLowerInvariant();
        }
    }

    public void PopulateContracts(List<ContractClientData>? list)
    {
        var contractList = ContractList;
        if (contractList == null)
            return;

        contractList.RemoveAllChildren();

        // Пусто / нет контрактов
        if (list == null || list.Count == 0)
        {
            contractList.AddChild(
                new Label
                {
                    Text = "Контрактов пока нет. Загляните позже.",
                    HorizontalAlignment = HAlignment.Center,
                    Margin = new(0, 8, 0, 0)
                });

            // ВАЖНО: нормализуем вкладки и тут тоже (один раз)
            ApplyTabsVisibility();
            return;
        }

        var ordered = list
            .OrderBy(x => x.Difficulty switch
            {
                "Easy" => 0,
                "Medium" => 1,
                "Hard" => 2,
                _ => 99
            })
            .ThenBy(x => x.Completed ? 1 : 0)
            .ToList();

        foreach (var c in ordered)
        {
            // --- Карточка: слева полоска сложности на всю высоту, справа контент ---
            var cardRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new(4, 0, 4, 8)
            };

            var diffStrip = new PanelContainer
            {
                MinSize = new(4, 0),
                VerticalExpand = true,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = DifficultyColor(c.Difficulty, c.Completed)
                },
                Margin = new(0, 0, 6, 0)
            };
            cardRow.AddChild(diffStrip);

            var panel = new PanelContainer
            {
                HorizontalExpand = true,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = new(0.06f, 0.06f, 0.07f, 0.98f),
                    BorderColor = DifficultyColor(c.Difficulty, c.Completed),
                    BorderThickness = new(2),
                    ContentMarginLeftOverride = 8,
                    ContentMarginRightOverride = 8,
                    ContentMarginTopOverride = 6,
                    ContentMarginBottomOverride = 6
                }
            };
            cardRow.AddChild(panel);

            var root = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true
            };
            panel.AddChild(root);

            // --- Заголовок ---
            var header = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new(0, 0, 0, 4)
            };

            var titleText = string.IsNullOrWhiteSpace(c.Name)
                ? $"{DifficultyName(c.Difficulty)} контракт"
                : c.Name;

            var titleLabel = new Label
            {
                Text = titleText,
                Margin = new(0, 0, 6, 0)
            };
            titleLabel.StyleClasses.Add("LabelHeading");
            header.AddChild(titleLabel);

            // Спейсер — всё “служебное” уходит вправо
            header.AddChild(new() { HorizontalExpand = true, });

            // --- Бейдж одноразового контракта (видимый и аккуратный) ---
            if (!c.Repeatable)
            {
                const string oneTimeTip =
                    "Единичная заявка.\n" +
                    "Этот терминал принимает её один раз за смену.\n" +
                    "После новой смены заявка появится снова.";

                var badge = new PanelContainer
                {
                    VerticalAlignment = VAlignment.Center,
                    Margin = new(0, 1, 6, 0),
                    MouseFilter = MouseFilterMode.Stop,
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = new(0.12f, 0.12f, 0.14f),
                        BorderColor = new(0f, 0f, 0f, 0.7f),
                        BorderThickness = new(1),
                        ContentMarginLeftOverride = 8,
                        ContentMarginRightOverride = 8,
                        ContentMarginTopOverride = 2,
                        ContentMarginBottomOverride = 2
                    },
                    ToolTip = oneTimeTip
                };

                var badgeText = new Label
                {
                    Text = "Разовый",
                    VerticalAlignment = VAlignment.Center,
                    ToolTip = oneTimeTip,
                    MouseFilter = MouseFilterMode.Stop
                };
                badgeText.StyleClasses.Add("LabelSubText");

                badge.AddChild(badgeText);
                header.AddChild(badge);
            }

            root.AddChild(header);

            // --- Описание ---
            if (!string.IsNullOrWhiteSpace(c.Description))
            {
                var desc = new Label
                {
                    Text = c.Description,
                    Margin = new(0, 0, 0, 4)
                };
                desc.StyleClasses.Add("LabelSubText");
                root.AddChild(desc);
            }

            // --- Цели ---
            var hasTargets = c.Targets.Count > 0;

            if (hasTargets)
            {
                root.AddChild(
                    new Label
                    {
                        Text = "Цели:",
                        Margin = new(0, 0, 0, 2)
                    });

                foreach (var t in c.Targets)
                {
                    EntityPrototype? targetProto = null;
                    if (!string.IsNullOrWhiteSpace(t.TargetItem))
                        _proto.TryIndex(t.TargetItem, out targetProto);

                    var targetRow = new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Horizontal,
                        Margin = new(0, 0, 0, 2)
                    };

                    Texture? targetTex = null;
                    if (targetProto != null)
                    {
                        var icon = _sprites.GetPrototypeIcon(targetProto.ID);
                        targetTex = icon.Default;
                    }

                    if (targetTex != null)
                    {
                        targetRow.AddChild(
                            new TextureRect
                            {
                                Texture = targetTex,
                                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                                MinSize = new(24, 24),
                                Margin = new(0, 0, 4, 0)
                            });
                    }

                    var targetName = targetProto?.Name ?? t.TargetItem;
                    targetRow.AddChild(
                        new Label
                        {
                            Text = $"• {targetName} ×{t.Required} (у вас {t.Progress})"
                        });

                    root.AddChild(targetRow);

                    if (!string.IsNullOrWhiteSpace(targetProto?.Description))
                    {
                        var itemDesc = new Label
                        {
                            Text = targetProto.Description,
                            Margin = new(28, 0, 0, 2)
                        };
                        itemDesc.StyleClasses.Add("LabelSubText");
                        root.AddChild(itemDesc);
                    }
                }
            }
            else
            {
                EntityPrototype? targetProto = null;
                if (!string.IsNullOrWhiteSpace(c.TargetItem))
                    _proto.TryIndex(c.TargetItem, out targetProto);

                var targetRow = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Margin = new(0, 0, 0, 2)
                };

                Texture? targetTex = null;
                if (targetProto != null)
                {
                    var icon = _sprites.GetPrototypeIcon(targetProto.ID);
                    targetTex = icon.Default;
                }

                if (targetTex != null)
                {
                    targetRow.AddChild(
                        new TextureRect
                        {
                            Texture = targetTex,
                            Stretch = TextureRect.StretchMode.KeepAspectCentered,
                            MinSize = new(24, 24),
                            Margin = new(0, 0, 4, 0)
                        });
                }

                var targetName = targetProto?.Name ?? c.TargetItem;
                targetRow.AddChild(
                    new Label
                    {
                        Text = $"Цель: {targetName} ×{c.Required}"
                    });

                root.AddChild(targetRow);

                if (!string.IsNullOrWhiteSpace(targetProto?.Description))
                {
                    var itemDesc = new Label
                    {
                        Text = targetProto.Description,
                        Margin = new(0, 0, 0, 4)
                    };
                    itemDesc.StyleClasses.Add("LabelSubText");
                    root.AddChild(itemDesc);
                }
            }

            // --- Прогресс ---
            if (!c.Completed)
            {
                var max = c.Required <= 0 ? 1 : c.Required;
                var val = Math.Clamp(c.Progress, 0, max);

                root.AddChild(
                    new Label
                    {
                        Text = $"Прогресс: {c.Progress} / {c.Required}",
                        Margin = new(0, 2, 0, 2)
                    });

                root.AddChild(
                    new ProgressBar
                    {
                        MinValue = 0,
                        MaxValue = max,
                        Value = val,
                        HorizontalExpand = true,
                        MinSize = new(0, 14),
                        Margin = new(0, 0, 0, 4)
                    });
            }

            // --- Низ карточки: награды слева + действия справа ---
            var bottomWrap = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new(0, 6, 0, 0)
            };

            // Левая часть: награды в панели
            var rewardsPanel = new PanelContainer
            {
                HorizontalExpand = true,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = new(0.05f, 0.05f, 0.06f, 0.6f),
                    BorderColor = new(0f, 0f, 0f, 0.55f),
                    BorderThickness = new(1),
                    ContentMarginLeftOverride = 8,
                    ContentMarginRightOverride = 8,
                    ContentMarginTopOverride = 6,
                    ContentMarginBottomOverride = 6
                }
            };

            var rewardsCol = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true
            };
            rewardsPanel.AddChild(rewardsCol);

            var rewardsHeader = new Label { Text = "Награда", Margin = new(0, 0, 0, 3), };
            rewardsHeader.StyleClasses.Add("LabelHeading");
            rewardsCol.AddChild(rewardsHeader);

            // Валюты (много) или fallback
            if (c.RewardCurrencies is { Count: > 0, } currencies)
            {
                var parts = new List<string>();
                foreach (var kv in currencies)
                {
                    var curId = kv.Key;
                    var amount = kv.Value;
                    if (amount <= 0 || string.IsNullOrWhiteSpace(curId))
                        continue;

                    var name = CurrencyName(curId);
                    if (string.IsNullOrWhiteSpace(name))
                        name = curId;

                    parts.Add($"{amount} {name}");
                }

                if (parts.Count > 0)
                {
                    var curLine = new Label { Text = string.Join(", ", parts), };
                    curLine.StyleClasses.Add("LabelSubText");
                    rewardsCol.AddChild(curLine);
                }
            }
            else if (c.Reward > 0 && !string.IsNullOrWhiteSpace(c.RewardCurrency))
            {
                Texture? currencyTex = null;
                if (_proto.TryIndex<StackPrototype>(c.RewardCurrency, out var stackProto) &&
                    _proto.TryIndex<EntityPrototype>(stackProto.Spawn, out var currencyEnt))
                {
                    var icon = _sprites.GetPrototypeIcon(currencyEnt.ID);
                    currencyTex = icon.Default;
                }

                var line = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Margin = new(0, 0, 0, 2)
                };

                if (currencyTex != null)
                {
                    line.AddChild(
                        new TextureRect
                        {
                            Texture = currencyTex,
                            Stretch = TextureRect.StretchMode.KeepAspectCentered,
                            MinSize = new(16, 16),
                            Margin = new(0, 0, 4, 0)
                        });
                }

                var currencyName = CurrencyName(c.RewardCurrency);
                var curText = string.IsNullOrEmpty(currencyName)
                    ? $"{c.Reward}"
                    : $"{c.Reward} {currencyName}";

                var curLine = new Label { Text = curText, };
                curLine.StyleClasses.Add("LabelSubText");

                line.AddChild(curLine);
                rewardsCol.AddChild(line);
            }

            // Предметы
            var anyItems = c.RewardItems is { Count: > 0, } ||
                !string.IsNullOrWhiteSpace(c.RewardItem) && c.RewardItemCount > 0;

            if (anyItems)
            {
                rewardsCol.AddChild(new() { MinSize = new(0, 4), });

                var itemsHeader = new Label { Text = "Предметы", Margin = new(0, 2, 0, 2), };
                itemsHeader.StyleClasses.Add("LabelHeading");
                rewardsCol.AddChild(itemsHeader);
            }

            if (c.RewardItems is { Count: > 0, } items)
            {
                foreach (var kv in items)
                {
                    var id = kv.Key;
                    var count = kv.Value;
                    if (count <= 0 || string.IsNullOrWhiteSpace(id))
                        continue;

                    _proto.TryIndex<EntityPrototype>(id, out var proto);

                    var line = new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Horizontal,
                        Margin = new(0, 0, 0, 2)
                    };

                    Texture? tex = null;
                    if (proto != null)
                    {
                        var icon = _sprites.GetPrototypeIcon(proto.ID);
                        tex = icon.Default;
                    }

                    if (tex != null)
                    {
                        line.AddChild(
                            new TextureRect
                            {
                                Texture = tex,
                                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                                MinSize = new(20, 20),
                                Margin = new(0, 0, 4, 0)
                            });
                    }

                    var name = proto?.Name ?? id;
                    line.AddChild(new Label { Text = $"{name} ×{count}", });

                    rewardsCol.AddChild(line);
                }
            }
            else if (!string.IsNullOrWhiteSpace(c.RewardItem) && c.RewardItemCount > 0)
            {
                _proto.TryIndex<EntityPrototype>(c.RewardItem, out var rewardProto);

                var line = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Margin = new(0, 0, 0, 2)
                };

                Texture? rewardTex = null;
                if (rewardProto != null)
                {
                    var icon = _sprites.GetPrototypeIcon(rewardProto.ID);
                    rewardTex = icon.Default;
                }

                if (rewardTex != null)
                {
                    line.AddChild(
                        new TextureRect
                        {
                            Texture = rewardTex,
                            Stretch = TextureRect.StretchMode.KeepAspectCentered,
                            MinSize = new(20, 20),
                            Margin = new(0, 0, 4, 0)
                        });
                }

                var rewardName = rewardProto?.Name ?? c.RewardItem;
                line.AddChild(new Label { Text = $"{rewardName} ×{c.RewardItemCount}", });

                rewardsCol.AddChild(line);
            }

            bottomWrap.AddChild(rewardsPanel);

            // Правая часть: действия (фиксированная ширина)
            var actionCol = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                MinSize = new(180, 0),
                Margin = new(8, 0, 0, 0)
            };

            var actionHint = new Label
            {
                Text = c.Completed ? "Можно сдать" : "Не выполнено",
                Margin = new(0, 0, 0, 4)
            };
            actionHint.StyleClasses.Add("LabelSubText");
            actionCol.AddChild(actionHint);

            actionCol.AddChild(new() { VerticalExpand = true, });

            var canClaim = c.Completed;

            var btn = new Button
            {
                Text = canClaim ? "Сдать" : $"Сдать ({c.Progress}/{c.Required})",
                Disabled = !canClaim,
                HorizontalExpand = true,
                MinSize = new(0, 32)
            };

            btn.ToolTip = canClaim
                ? !c.Repeatable
                    ? "Закрыть единичную заявку и получить награду.\nТерминал примет её один раз за смену."
                    : "Закрыть контракт и получить награду."
                : "Контракт ещё не выполнен.";

            btn.OnPressed += _ =>
            {
                if (!canClaim)
                    return;

                OnContractClaim?.Invoke(c.Id);
            };

            actionCol.AddChild(btn);
            bottomWrap.AddChild(actionCol);

            root.AddChild(bottomWrap);

            contractList.AddChild(cardRow);
        }

        // ВАЖНО: один раз после построения всего списка
        ApplyTabsVisibility();
    }


    private void RefreshListings()
    {
        var hasSearch = !string.IsNullOrWhiteSpace(_search);
        var buyFiltered = Filtered(StoreMode.Buy, _buyCat).ToList();
        var sellFiltered = Filtered(StoreMode.Sell, _sellCat).ToList();

        var buyCount = buyFiltered.Count;
        var sellCount = sellFiltered.Count;

        BuyCategoryHeader.Visible = !string.IsNullOrEmpty(_buyCat) || hasSearch;
        SellCategoryHeader.Visible = !string.IsNullOrEmpty(_sellCat) || hasSearch;

        if (BuyCategoryHeader.Visible)
        {
            BuyCategoryHeader.Text = !string.IsNullOrEmpty(_buyCat)
                ? _buyCat
                : $"Результаты поиска ({buyCount})";
        }
        else
            BuyCategoryHeader.Text = string.Empty;

        if (SellCategoryHeader.Visible)
        {
            SellCategoryHeader.Text = !string.IsNullOrEmpty(_sellCat)
                ? _sellCat
                : $"Результаты поиска ({sellCount})";
        }
        else
            SellCategoryHeader.Text = string.Empty;

        FillPaneFull(
            BuyListingsContainer,
            StoreMode.Buy,
            _buyCat,
            buyFiltered,
            (d, qty) => OnBuyPressed?.Invoke(d, qty));

        FillPaneFull(
            SellListingsContainer,
            StoreMode.Sell,
            _sellCat,
            sellFiltered,
            (d, qty) => OnSellPressed?.Invoke(d, qty));
    }

    private IEnumerable<StoreListingData> Filtered(StoreMode mode, string cat)
    {
        var q = _items.Where(i => i.Mode == mode);

        var hasCat = !string.IsNullOrEmpty(cat);
        var hasSearch = !string.IsNullOrWhiteSpace(_searchLower);

        if (!hasCat && !hasSearch)
            return Enumerable.Empty<StoreListingData>();

        if (hasCat)
            q = q.Where(i => i.Category == cat);

        if (hasSearch)
            q = q.Where(i => MatchesSearch(i.ProductEntity));

        return q;
    }

    private void FillPaneFull(
        Control pane,
        StoreMode mode,
        string cat,
        List<StoreListingData> filtered,
        Action<StoreListingData, int> emit
    )
    {
        pane.Children.Clear();

        var hasCat = !string.IsNullOrEmpty(cat);
        var hasSearch = !string.IsNullOrWhiteSpace(_searchLower);

        if (!hasCat && !hasSearch)
        {
            pane.AddChild(new Label { Text = "Выберите категорию.", });
            return;
        }

        if (filtered.Count == 0)
        {
            string message;

            if (!string.IsNullOrEmpty(cat))
                message = "По вашему запросу в этой категории ничего не найдено.";
            else
                message = "По вашему запросу ничего не найдено.";

            pane.AddChild(new Label { Text = message, });
            return;
        }

        var page = mode == StoreMode.Buy ? _pageBuy : _pageSell;
        var take = Math.Min(filtered.Count, PageSize * page);

        AddListingRange(pane, mode, filtered, 0, take, emit);

        AddOrUpdateMoreButton(pane, mode, filtered.Count, take, cat, emit);
    }


    private void AppendNextPage(Control pane, StoreMode mode, string cat, Action<StoreListingData, int> emit)
    {
        var filtered = Filtered(mode, cat).ToList();
        var page = mode == StoreMode.Buy ? _pageBuy : _pageSell;
        var take = Math.Min(filtered.Count, PageSize * page);

        var already = 0;
        foreach (var ch in pane.Children)
            if (ch is NcStoreListingControl)
                already++;

        var toAddStart = already;
        var toAddEnd = Math.Min(take, filtered.Count);

        if (toAddStart < toAddEnd)
            AddListingRange(pane, mode, filtered, toAddStart, toAddEnd, emit);

        RemoveMoreButtons(pane);
        AddOrUpdateMoreButton(pane, mode, filtered.Count, take, cat, emit);
    }

    private void AddListingRange(
        Control pane,
        StoreMode mode,
        List<StoreListingData> source,
        int startExclusive,
        int endExclusive,
        Action<StoreListingData, int> emit
    )
    {
        var cache = mode == StoreMode.Buy ? _buyCache : _sellCache;

        for (var i = startExclusive; i < endExclusive; i++)
        {
            var it = source[i];

            var balanceHint = mode == StoreMode.Buy
                ? GetBalanceForCurrency(it.CurrencyId)
                : int.MaxValue;

            var sig = Sig(it, balanceHint);

            NcStoreListingControl ctrl;
            if (cache.TryGetValue(it.Id, out var tuple) && tuple.Sig == sig)
                ctrl = tuple.Ctrl;
            else
            {
                var initQty = _qtyCache.TryGetValue(it.Id, out var saved) ? saved : 1;

                var actionsEnabled = true;

                ctrl = new(it, _sprites, balanceHint, initQty, actionsEnabled);
                ctrl.OnQtyChanged += newQty => _qtyCache[it.Id] = newQty;

                switch (mode)
                {
                    case StoreMode.Buy:
                        ctrl.OnBuyPressed += qty => emit(it, qty);
                        break;
                    case StoreMode.Sell:
                        ctrl.OnSellPressed += qty => emit(it, qty);
                        break;
                }

                cache[it.Id] = (ctrl, sig);
            }

            pane.AddChild(ctrl);

            if (i < endExclusive - 1)
            {
                pane.AddChild(
                    new PanelContainer
                    {
                        MinSize = new Vector2i(0, 1),
                        StyleClasses = { "LowDivider", }
                    });
            }
        }
    }


    private static void RemoveMoreButtons(Control pane)
    {
        foreach (var ch in pane.Children.ToList())
            if (ch is Button b && b.Text != null &&
                b.Text.StartsWith("Показать ещё (", StringComparison.Ordinal))
                pane.RemoveChild(b);
    }

    private void AddOrUpdateMoreButton(
        Control pane,
        StoreMode mode,
        int totalCount,
        int shown,
        string cat,
        Action<StoreListingData, int> emit
    )
    {
        if (shown >= totalCount)
            return;

        var left = totalCount - shown;

        var more = new Button
        {
            Text = $"Показать ещё ({left})",
            HorizontalExpand = true,
            Margin = new(0, 8, 0, 8)
        };

        more.OnPressed += _ =>
        {
            if (mode == StoreMode.Buy)
                _pageBuy++;
            else
                _pageSell++;

            AppendNextPage(pane, mode, cat, emit);
        };

        pane.AddChild(more);
    }

    private void BuildCategoryButtons()
    {
        _buyCatButtons.Clear();
        _sellCatButtons.Clear();

        MakeButtons(
            _buyCats,
            BuyCategoryListContainer,
            _buyCat,
            _buyCatButtons,
            cat =>
            {
                _buyCat = _buyCat == cat ? string.Empty : cat;
                UpdateCatVisuals(_buyCatButtons, _buyCat);
                ResetPaging();
                RefreshListings();
            });

        MakeButtons(
            _sellCats,
            SellCategoryListContainer,
            _sellCat,
            _sellCatButtons,
            cat =>
            {
                _sellCat = _sellCat == cat ? string.Empty : cat;
                UpdateCatVisuals(_sellCatButtons, _sellCat);
                ResetPaging();
                RefreshListings();
            });

        UpdateCatVisuals(_buyCatButtons, _buyCat);
        UpdateCatVisuals(_sellCatButtons, _sellCat);
    }

    private static void MakeButtons(
        IEnumerable<string> cats,
        Control parent,
        string current,
        Dictionary<string, Button> registry,
        Action<string> onClick
    )
    {
        parent.Children.Clear();

        foreach (var c in cats)
        {
            var catId = c;

            var display = c;
            if (c == "Готово к продаже")
                display = "Готово";
            else if (c == CrateCategory)
                display = "В ящике";

            var selected = catId == current;

            var btn = new Button
            {
                Text = display,
                ToggleMode = true,
                HorizontalExpand = true,
                Pressed = selected,
                ModulateSelfOverride = selected ? CatSelected : CatIdle,
                ToolTip = c
            };

            btn.OnMouseEntered += _ =>
                btn.ModulateSelfOverride =
                    btn.Pressed ? Brighten(CatSelected, 1.2f) : Brighten(CatIdle, 1.2f);
            btn.OnMouseExited += _ =>
                btn.ModulateSelfOverride = btn.Pressed ? CatSelected : CatIdle;

            btn.OnPressed += _ => onClick(catId);

            parent.AddChild(btn);
            registry[catId] = btn;
        }
    }


    private string CurrencyName(string? currencyId)
    {
        if (string.IsNullOrWhiteSpace(currencyId))
            return string.Empty;

        if (_proto.TryIndex<StackPrototype>(currencyId, out var stackProto) &&
            _proto.TryIndex<EntityPrototype>(stackProto.Spawn, out var currencyEnt))
            return currencyEnt.Name;

        return currencyId;
    }

    private Color DifficultyColor(string diff, bool completed)
    {
        var baseColor = diff switch
        {
            "Easy" => Color.FromHex("#4CAF50"),
            "Medium" => Color.FromHex("#FFC107"),
            "Hard" => Color.FromHex("#F44336"),
            _ => Color.FromHex("#9E9E9E")
        };

        return completed ? Brighten(baseColor, 0.7f) : baseColor;
    }

    private string DifficultyName(string diff) =>
        diff switch
        {
            "Easy" => "Лёгкий",
            "Medium" => "Средний",
            "Hard" => "Тяжёлый",
            _ => diff
        };

    private static void UpdateCatVisuals(Dictionary<string, Button> map, string current)
    {
        foreach (var (name, btn) in map)
        {
            var selected = name == current;
            btn.Pressed = selected;
            btn.ModulateSelfOverride = selected ? CatSelected : CatIdle;
        }
    }

    private static Color Brighten(Color c, float f) =>
        new(MathF.Min(c.R * f, 1f), MathF.Min(c.G * f, 1f), MathF.Min(c.B * f, 1f), c.A);

    private void ResetPaging()
    {
        _pageBuy = 1;
        _pageSell = 1;
    }

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        _disposed = true;
        base.Dispose(disposing);
    }

    private static int Sig(StoreListingData d, int balance)
    {
        return d.Mode == StoreMode.Buy
            ? HashCode.Combine(d.Id, d.ProductEntity, d.Category, d.Price, d.Remaining, d.Owned, d.CurrencyId, balance)
            : HashCode.Combine(d.Id, d.ProductEntity, d.Category, d.Price, d.Remaining, d.Owned, d.CurrencyId);
    }

    private bool MatchesSearch(string protoId)
    {
        if (string.IsNullOrWhiteSpace(protoId))
            return false;

        if (string.IsNullOrWhiteSpace(_searchLower))
            return true;

        if (_searchIndex.TryGetValue(protoId, out var hay))
            return hay.Contains(_searchLower, StringComparison.Ordinal);

        if (!_proto.TryIndex<EntityPrototype>(protoId, out var p))
            return false;

        var name = p.Name;
        var desc = p.Description;
        var combined = (name + "\n" + desc).ToLowerInvariant();
        _searchIndex[protoId] = combined;
        return combined.Contains(_searchLower, StringComparison.Ordinal);
    }
}
