using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PipBoyColorSettings : BoxContainer
{
    public event Action<bool>? OnColorSelected;

    public PipBoyColorSettings()
    {
        RobustXamlLoader.Load(this);
        ColorButton.OnPressed += _ => Colors.Visible = !Colors.Visible;
        GreenButton.OnPressed += _ => OnColorSelected?.Invoke(true);
        AmberButton.OnPressed += _ => OnColorSelected?.Invoke(false);
    }

    public void SetColor(bool green)
    {
        GreenButton.Pressed = green;
        AmberButton.Pressed = !green;
    }
}
