using Content.Client._NC.Sponsor.UI; // Forge-Change
using Content.Client.Message;
/// Forge-Change-Start
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
/// Forge-Change-End
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.State;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
/// Forge-Change-Start
using Robust.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Robust.Shared.Configuration;
/// Forge-Change-End

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

        /// Forge-Change-Start
        [Dependency] private readonly IConfigurationManager _configuration = default!;

        /// Forge-Change-End
        private SponsorWindow? _sponsorWindow; // Forge-Change

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            /// Forge-Change-Start
            /// Forge-Change-Del
            // ApplyLobbyStyle(DefaultState);
            // ApplyLobbyStyle(RightSide);
            // Chat.ChatWindowPanel.AddStyleClass("NewVegasPanel");
            ApplyTheme();
            ThemeButton.OnPressed += _ =>
            {
                _configuration.SetCVar(CCVars.LobbyNewVegasTheme,
                    !_configuration.GetCVar(CCVars.LobbyNewVegasTheme));
                _configuration.SaveToFile();
                ApplyTheme();
            };
            /// Forge-Change-End
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
            LobbyBackground.SetMarkup(Loc.GetString("lobby-state-background-no-background-text"));

            /// Forge-Change-Start
            var uriOpener = IoCManager.Resolve<IUriOpener>();
            WikiButton.OnPressed += _ => uriOpener.OpenUri("https://station14.ru/wiki/Портал:Fallout");
            WebsiteButton.OnPressed += _ => uriOpener.OpenUri("https://site.corvaxforge.ru/");

            /// Forge-Change-End
            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            SponsorButton.OnPressed += _ => OpenSponsorWindow(); // Forge-Change
        /// Forge-Change-Start
        }

        /// Forge-Change-Del
        // private static void ApplyLobbyStyle(Control control)
        private void ApplyTheme()
        {
            var enabled = _configuration.GetCVar(CCVars.LobbyNewVegasTheme);
            ApplyLobbyStyle(DefaultState, enabled);
            ApplyLobbyStyle(RightSide, enabled);
            SetThemeClass(Chat.ChatWindowPanel, "NewVegasPanel", enabled);
            StartTime.FontColorOverride = enabled ? StyleNewVegas.Amber : Color.DarkGray;
            ThemeButton.Text = Loc.GetString(enabled
                ? "ui-lobby-theme-new-vegas"
                : "ui-lobby-theme-classic");
        }

        private static void SetThemeClass(Control control, string styleClass, bool enabled)
        {
            if (enabled)
                control.AddStyleClass(styleClass);
            else
                control.RemoveStyleClass(styleClass);
        }

        private static void ApplyLobbyStyle(Control control, bool enabled)
        {
            if (control is Button button)
            {
                /// Forge-Change-Del
                // button.AddStyleClass("NewVegasButton");
                // button.Label.AddStyleClass("NewVegasText");
                SetThemeClass(button, "NewVegasButton", enabled);
                SetThemeClass(button.Label, "NewVegasText", enabled);
            }

            if (control.HasStyleClass("LobbyThemePanel"))
            {
                SetThemeClass(control, "NewVegasPanel", enabled);
                SetThemeClass(control, "AngleRect", !enabled);
            }

            if (control is HLine line)
                line.Color = enabled ? StyleNewVegas.Amber : StyleNano.NanoGold;

            if (control is NanoHeading)
            {
                foreach (var child in control.Children)
                {
                    if (child is PanelContainer panel)
                        /// Forge-Change-Del
                        // panel.PanelOverride = StyleNewVegas.HeadingBox();
                        panel.PanelOverride = enabled ? StyleNewVegas.HeadingBox() : null;
                }
            }

            if (control is Label label &&
                (label.HasStyleClass(StyleNano.StyleClassLabelHeading) ||
                 label.HasStyleClass(StyleNano.StyleClassLabelHeadingBigger)))
                /// Forge-Change-Del
                // label.FontColorOverride = StyleNewVegas.HeadingColor;
                label.FontColorOverride = enabled ? StyleNewVegas.HeadingColor : null;

            foreach (var child in control.Children)
                /// Forge-Change-Del
                // ApplyLobbyStyle(child);
                ApplyLobbyStyle(child, enabled);
        /// Forge-Change-End
        }

        // Forge-Change: open (or focus) the sponsorship window.
        private void OpenSponsorWindow()
        {
            // A closed window is removed from its parent (IsOpen == false) but not disposed,
            // so only focus it when it is actually open; otherwise (re)create it.
            if (_sponsorWindow is { Disposed: false, IsOpen: true })
            {
                _sponsorWindow.MoveToFront();
                return;
            }

            _sponsorWindow = new SponsorWindow();
            _sponsorWindow.OpenCentered();
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;
                    RightSide.Visible = false;
                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                        RightSide.Visible = false;

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        public enum LobbyGuiState : byte
        {
            /// The default state, i.e., what's seen on launch.
            Default,
            /// The character setup state.
            CharacterSetup,
        }
    }
}
