using Content.Client._NC.Sponsor.UI; // Forge-Change
using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.State;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

        private SponsorWindow? _sponsorWindow; // Forge-Change

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            ApplyLobbyStyle(DefaultState);
            ApplyLobbyStyle(RightSide);
            Chat.ChatWindowPanel.AddStyleClass("NewVegasPanel");
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
            LobbyBackground.SetMarkup(Loc.GetString("lobby-state-background-no-background-text"));

            var uriOpener = IoCManager.Resolve<IUriOpener>();
            WikiButton.OnPressed += _ => uriOpener.OpenUri("https://station14.ru/wiki/Портал:Fallout");
            WebsiteButton.OnPressed += _ => uriOpener.OpenUri("https://site.corvaxforge.ru/");

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            SponsorButton.OnPressed += _ => OpenSponsorWindow(); // Forge-Change
        }

        private static void ApplyLobbyStyle(Control control)
        {
            if (control is Button button)
            {
                button.AddStyleClass("NewVegasButton");
                button.Label.AddStyleClass("NewVegasText");
            }

            if (control is NanoHeading)
            {
                foreach (var child in control.Children)
                {
                    if (child is PanelContainer panel)
                        panel.PanelOverride = StyleNewVegas.HeadingBox();
                }
            }

            if (control is Label label &&
                (label.HasStyleClass(StyleNano.StyleClassLabelHeading) ||
                 label.HasStyleClass(StyleNano.StyleClassLabelHeadingBigger)))
                label.FontColorOverride = StyleNewVegas.HeadingColor;

            foreach (var child in control.Children)
                ApplyLobbyStyle(child);
        }

        // Forge-Change: open (or focus) the sponsorship window.
        private void OpenSponsorWindow()
        {
            // A closed window is removed from its parent (IsOpen == false) but not disposed,
            // so only focus it when it is actually open; otherwise (re)create it.
            if (_sponsorWindow is { Disposed: false, IsOpen: true })
            {
                _sponsorWindow.MoveToFront();
                return;
            }

            _sponsorWindow = new SponsorWindow();
            _sponsorWindow.OpenCentered();
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;
                    RightSide.Visible = false;
                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                        RightSide.Visible = false;

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        public enum LobbyGuiState : byte
        {
            /// The default state, i.e., what's seen on launch.
            Default,
            /// The character setup state.
            CharacterSetup,
        }
    }
}
