# MARK: Ranger
- type: loadout
  id: LoadoutNCRRangerVest
  category: Outer
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerVest

- type: loadout
  id: LoadoutNCRRangerRedwood
  category: Outer
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
    - !type:CharacterPlaytimeRequirement # Forge-change
      tracker: NCRRanger
      min: 72000
  items:
    - N14ClothingOuterRangerRedwood # Forge-change

- type: loadout
  id: LoadoutNCRRangerCombat
  category: Outer
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
    - !type:CharacterPlaytimeRequirement # Forge-change
      tracker: NCRRanger
      min: 54000
  items:
    - N14ClothingOuterRangerArmorOld # Forge-change

- type: loadout
  id: LoadoutNCRRangerCoyote
  category: Outer
  cost: 6
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
    - !type:CharacterPlaytimeRequirement # Forge-change
      tracker: NCRRanger
      min: 144000
  items:
    - N14ClothingOuterRangerCoyote # Forge-change


- type: loadout
  id: LoadoutNCRRangerScorpion
  category: Outer
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
    - !type:CharacterPlaytimeRequirement # Forge-change
      tracker: NCRRanger
      min: 54000
  items:
    - N14ClothingOuterRangerScorpion # Forge-change

- type: loadout
  id: LoadoutNCRN14ClothingNeckCloakRanger
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingNeckCloakRanger

# Corvax-Add End

- type: loadout
  id: LoadoutNCRhatB
  category: Head
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerB

- type: loadout
  id: LoadoutNCRhatBeret
  category: Head
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatNCRBeretRecon

- type: loadout
  id: LoadoutNCRmaskDesert
  category: Mask
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingMaskDesertMask

- type: loadout
  id: LoadoutNCRuniformV1
  category: Uniform
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV1

- type: loadout
  id: LoadoutNCRuniformV2
  category: Uniform
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV2

- type: loadout
  id: LoadoutNCRuniformV3
  category: Uniform
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV3

- type: loadout
  id: LoadoutNCRuniformPants
  category: Uniform
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformDesertPants

- type: loadout
  id: LoadoutNCRuniformDesertPantsFull
  category: Uniform
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformDesertPantsFull

# - type: loadout # Дважды используется.
#   id: LoadoutNCRgloves
#   category: Hands
#   cost: 1
#   exclusive: true
#   requirements:
#     - !type:CharacterJobRequirement
#       jobs:
#         - NCRRanger
#         - NCRRangerVeteran
#   items:
#     - N14ClothingHandsGlovesNCR

# misc
- type: loadout
  id: LoadoutNCRRangerMedkit
  category: Items
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14MedkitCombatFilled

- type: loadout
  id: LoadoutNCRuniformHelmetDesert
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRangerVeteran
      min: 216000 # 60 hours veterancy unlock "First Tour"
  items:
    - N14ClothingHeadHatRangerHelmetDesert

- type: loadout
  id: LoadoutNCRuniformMaskDesert
  category: Mask
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRangerVeteran
      min: 216000 # 60 hours veterancy unlock "First Tour"
  items:
    - ClothingMaskGasRangerDesert

- type: loadout
  id: LoadoutNCRuniformCombatDesert
  category: Outer
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRangerVeteran
      min: 216000 # 60 hours veterancy unlock "First Tour"
  items:
    - N14ClothingOuterRangerCombatDesert

- type: loadout
  id: LoadoutNCRRangerEliteOld
  category: Outer
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRangerVeteran
      min: 216000 # 60 hours veterancy unlock "First Tour"
  items:
    - N14ClothingOuterRangerEliteOld

- type: loadout
  id: LoadoutNCRRangerHelmetEliteOld1
  category: Head
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRangerVeteran
      min: 216000 # 60 hours veterancy unlock "First Tour"
  items:
    - N14ClothingHeadHatRangerHelmetEliteOld
