- type: job
  id: NCRPisoner
  setPreference: true
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-ncr-prisoner
  description: job-description-ncr-prisoner
  playTimeTracker: NCRPisoner
  requirements:
    # Forge-Change-Del - !type:MinPlayersRequirement
      # Forge-Change-Del min: 55
    # Forge-Change-Del - !type:CharacterSpeciesRequirement
      # Forge-Change-Del species:
      # Forge-Change-Del - Human
      # Forge-Change-Del - Ghoul
    # Forge-Change-Del - !type:CharacterOverallTimeRequirement
      # Forge-Change-Del min: 3600
  # Forge-Change-Start
  - !type:CharacterSpeciesRequirement
    species:
    - Human
    - Ghoul
  - !type:CharacterOverallTimeRequirement
    min: 3600
  - !type:MinPlayersRequirement
    min: 55
  # Forge-Change-End
  startingGear: NCRPisonerGear
  icon: "JobIconNCRPrisoner"
  supervisors: job-supervisors-ncr-prisoners
  alwaysUseSpawner: true
  access:
  - NCR
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCRPisonerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: N14ClothingShoesBlack
    bandage: NCClothingBrasletNCRPrisoner

- type: playTimeTracker
  id: NCRPisoner

