using System;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Forge.Silicons.LawCard;

[GenerateTypedNameReferences]
public sealed partial class LawCardEntry : PanelContainer
{
    private SiliconLaw? _law;

    public event Action<SiliconLaw>? OnDelete;

    public LawCardEntry()
    {
        RobustXamlLoader.Load(this);

        LawContent.OnTextChanged += _ => _law!.LawString = Rope.Collapse(LawContent.TextRope).Trim();
        LawContent.Placeholder = new Rope.Leaf(Loc.GetString("law-card-ui-placeholder"));
        Delete.OnPressed += _ => OnDelete?.Invoke(_law!);
    }

    public void SetLaw(SiliconLaw law, int position)
    {
        _law = law;
        LawContent.TextRope = new Rope.Leaf(Loc.GetString(law.LawString));
        PositionText.Text = Loc.GetString("laws-ui-law-header", ("id", position));
    }
}
