using System;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._NC.Trade.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcCategoryButtonControl : Button
{
    private Color _selectedColor = new(0xD9, 0xA4, 0x41);
    private Color _idleColor = new(0x7C, 0x66, 0x24);

    public string CategoryId { get; private set; } = string.Empty;

    public event Action<string>? OnCategoryPressed;

    public NcCategoryButtonControl()
    {
        RobustXamlLoader.Load(this);

        OnMouseEntered += _ =>
        {
            ModulateSelfOverride = Pressed
                ? Brighten(_selectedColor, 1.2f)
                : Brighten(_idleColor, 1.2f);
        };

        OnMouseExited += _ =>
        {
            ModulateSelfOverride = Pressed ? _selectedColor : _idleColor;
        };

        OnPressed += _ =>
        {
            OnCategoryPressed?.Invoke(CategoryId);
        };

        ModulateSelfOverride = _idleColor;
    }

    public void Bind(string categoryId, string text, string? tooltip)
    {
        CategoryId = categoryId;
        Text = text;
        ToolTip = tooltip;
    }

    public void SetSelected(bool selected)
    {
        if (Pressed != selected)
            Pressed = selected;

        ModulateSelfOverride = selected ? _selectedColor : _idleColor;
    }

    public void SetThemeColors(Color idleColor, Color selectedColor)
    {
        _idleColor = idleColor;
        _selectedColor = selectedColor;
        ModulateSelfOverride = Pressed ? _selectedColor : _idleColor;
    }

    private static Color Brighten(Color c, float f) =>
        new(MathF.Min(c.R * f, 1f), MathF.Min(c.G * f, 1f), MathF.Min(c.B * f, 1f), c.A);
}
