using System;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._NC.Trade.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcCategoryButtonControl : Button
{
    private Color _selectedColor = new(0xD9, 0xA4, 0x41);
    private Color _idleColor = new(0x7C, 0x66, 0x24);
    private bool _hovered;

    public string CategoryId { get; private set; } = string.Empty;

    public event Action<string>? OnCategoryPressed;

    public NcCategoryButtonControl()
    {
        RobustXamlLoader.Load(this);

        OnMouseEntered += _ =>
        {
            _hovered = true;
            ApplyVisualState();
        };

        OnMouseExited += _ =>
        {
            _hovered = false;
            ApplyVisualState();
        };

        OnPressed += _ =>
        {
            OnCategoryPressed?.Invoke(CategoryId);
        };

        ApplyVisualState();
    }

    public void Bind(string categoryId, string text, string? tooltip)
    {
        CategoryId = categoryId;
        Text = text;
        ToolTip = tooltip;
    }

    public void SetSelected(bool selected)
    {
        if (Pressed != selected)
            Pressed = selected;

        ApplyVisualState();
    }

    public void SetThemeColors(Color idleColor, Color selectedColor)
    {
        _idleColor = idleColor;
        _selectedColor = selectedColor;
        ApplyVisualState();
    }

    private void ApplyVisualState()
    {
        var baseColor = Pressed ? _selectedColor : _idleColor;
        var fill = _hovered ? Brighten(baseColor, 1.12f) : baseColor;
        var border = Brighten(baseColor, 0.82f);

        var style = new StyleBoxFlat
        {
            BackgroundColor = fill,
            BorderColor = border,
            BorderThickness = new(1)
        };
        style.SetContentMarginOverride(StyleBox.Margin.Left, 8);
        style.SetContentMarginOverride(StyleBox.Margin.Right, 8);
        style.SetContentMarginOverride(StyleBox.Margin.Top, 3);
        style.SetContentMarginOverride(StyleBox.Margin.Bottom, 3);

        StyleBoxOverride = style;
        ModulateSelfOverride = Color.White;
        Label.ModulateSelfOverride = GetReadableTextColor(fill);
    }

    private static Color Brighten(Color c, float f) =>
        new(MathF.Min(c.R * f, 1f), MathF.Min(c.G * f, 1f), MathF.Min(c.B * f, 1f), c.A);

    private static Color GetReadableTextColor(Color background)
    {
        var luminance = 0.299f * background.R + 0.587f * background.G + 0.114f * background.B;
        return luminance > 0.58f ? Color.Black : Color.White;
    }
}
