using System;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._NC.Trade.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcCategoryButtonControl : Button
{
    private static readonly Color IdleText = Color.FromHex("#B6B0A4");
    private static readonly Color HoverText = Color.FromHex("#D3CDC0");

    private Color _selectedColor = new(0xD9, 0xA4, 0x41);
    private Color _idleColor = new(0x7C, 0x66, 0x24);
    private Color _surfaceBase = Color.FromHex("#161A20");
    private bool _hovered;

    public string CategoryId { get; private set; } = string.Empty;

    public event Action<string>? OnCategoryPressed;

    public NcCategoryButtonControl()
    {
        RobustXamlLoader.Load(this);

        OnMouseEntered += _ =>
        {
            _hovered = true;
            ApplyVisualState();
        };

        OnMouseExited += _ =>
        {
            _hovered = false;
            ApplyVisualState();
        };

        OnPressed += _ =>
        {
            OnCategoryPressed?.Invoke(CategoryId);
        };

        ApplyVisualState();
    }

    public void Bind(string categoryId, string text, string? tooltip)
    {
        CategoryId = categoryId;
        TitleLabel.Text = text;
        ToolTip = tooltip;
        Text = string.Empty;
    }

    public void SetSelected(bool selected)
    {
        if (Pressed != selected)
            Pressed = selected;

        ApplyVisualState();
    }

    public void SetThemeColors(Color idleColor, Color selectedColor, Color surfaceBase)
    {
        _idleColor = idleColor;
        _selectedColor = selectedColor;
        _surfaceBase = surfaceBase;
        ApplyVisualState();
    }

    private void ApplyVisualState()
    {
        var background = GetBackgroundColor();
        var border = GetBorderColor(background);
        var accent = GetAccentColor();
        var text = GetTextColor();

        var style = new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new(1)
        };

        style.SetContentMarginOverride(StyleBox.Margin.Left, 0);
        style.SetContentMarginOverride(StyleBox.Margin.Right, 0);
        style.SetContentMarginOverride(StyleBox.Margin.Top, 0);
        style.SetContentMarginOverride(StyleBox.Margin.Bottom, 0);

        StyleBoxOverride = style;
        ModulateSelfOverride = Color.White;

        AccentBar.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = accent,
            BorderThickness = new(0)
        };

        TitleLabel.ModulateSelfOverride = text;
    }

    private Color GetBackgroundColor()
    {
        var baseSurface = GetBaseSurface();
        var hoverSurface = GetHoverSurface();
        var selectedSurface = GetSelectedSurface();

        if (Pressed)
            return Blend(selectedSurface, _selectedColor, 0.22f);

        if (_hovered)
            return Blend(hoverSurface, _idleColor, 0.14f);

        return Blend(baseSurface, _idleColor, 0.10f);
    }

    private Color GetBorderColor(Color background)
    {
        if (Pressed)
            return Blend(_selectedColor, Color.White, 0.18f);

        if (_hovered)
            return Blend(background, Color.White, 0.10f);

        return Blend(background, Color.White, 0.05f);
    }

    private Color GetAccentColor()
    {
        var baseSurface = GetBaseSurface();

        if (Pressed)
            return _selectedColor;

        if (_hovered)
            return Blend(_idleColor, Color.White, 0.12f);

        return WithAlpha(Blend(_idleColor, baseSurface, 0.35f), 0.70f);
    }

    private Color GetTextColor()
    {
        if (Pressed)
            return Blend(Color.FromHex("#ECE4D4"), _selectedColor, 0.10f);

        if (_hovered)
            return HoverText;

        return IdleText;
    }

    private Color GetBaseSurface() => Blend(_surfaceBase, _idleColor, 0.18f);

    private Color GetHoverSurface() => Blend(Blend(_surfaceBase, Color.White, 0.03f), _idleColor, 0.26f);

    private Color GetSelectedSurface() => Blend(Blend(_surfaceBase, _selectedColor, 0.18f), _selectedColor, 0.24f);

    private static Color Blend(Color a, Color b, float t)
    {
        t = Clamp01(t);

        return new Color(
            a.R + (b.R - a.R) * t,
            a.G + (b.G - a.G) * t,
            a.B + (b.B - a.B) * t,
            a.A + (b.A - a.A) * t);
    }

    private static Color WithAlpha(Color color, float alpha)
    {
        alpha = Clamp01(alpha);
        return new Color(color.R, color.G, color.B, alpha);
    }

    private static float Clamp01(float value)
    {
        if (value < 0f)
            return 0f;

        if (value > 1f)
            return 1f;

        return value;
    }
}
