using Content.Shared._NC.Trade;
using Content.Client._NC.Trade.Theme;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client._NC.Trade.Controls;


[GenerateTypedNameReferences]
public sealed partial class NcContractCard : PanelContainer
{
    private const float DescriptionHorizontalBudget = 40f;
    private const int DescriptionMaxChars = 240;
    private const int TargetIconPx = 56;
    private const int RewardIconPx = 26;
    private const float ProgressFillMinVisibleWidth = 8f;
    private readonly IPrototypeManager _proto;
    private readonly SpriteSystem _sprites;

    private ContractClientData _data;
    private float _lastDescriptionMaxWidth = -1f;
    private int _presentationHash;
    private float _progressRatio;
    private int _skipBalance;
    private int _skipCost;
    private string _skipCurrency;
    private StoreUiColorsData _uiColors = new();

    public NcContractCard(
        ContractClientData data,
        IPrototypeManager protoMan,
        SpriteSystem sprites,
        int skipCost = 0,
        string skipCurrency = "",
        int skipBalance = 0
    )
    {
        RobustXamlLoader.Load(this);

        _data = data;
        _proto = protoMan;
        _sprites = sprites;
        _skipCost = skipCost;
        _skipCurrency = skipCurrency;
        _skipBalance = skipBalance;
        _presentationHash = ComputePresentationHash(data, skipCost, skipCurrency, skipBalance);
        PrimaryActionButton.OnPressed += OnPrimaryActionPressed;

        PopulateUi();
    }

    public event Action<string>? OnClaim;
    public event Action<string>? OnTake;
    public event Action<string>? OnSkip;
    public event Action<string>? OnRequestPinpointer;

    public void ApplyUiTheme(StoreUiColorsData colors)
    {
        _uiColors = colors;
        ApplyDifficultyChrome();
        PopulateActionsSection();
    }


    private static Color Dim(Color color, float factor) =>
        new(
            color.R * factor,
            color.G * factor,
            color.B * factor,
            color.A);

    private void PopulateUi()
    {
        ApplyDifficultyChrome();
        PopulateHeader();
        PopulateDescription();
        PopulateStatus();
        PopulateStage();
        PopulateGoals();
        PopulateTurnIn();
        PopulateProgress();
        PopulateRewardsSection();
        PopulateActionsSection();
        SyncDescriptionWidth(Size.X);
    }

    private void ApplyDifficultyChrome()
    {
        var baseAccent = NcStoreUiTheme.ResolveColor(_uiColors.CategoryButtonSelected, "#4F86B7");
        var accent = _data.Completed
            ? Dim(baseAccent, 0.55f)
            : baseAccent;

        var cardBackground = NcStoreUiTheme.ResolveColor(_uiColors.ListingCardBackground, "#141A22");
        var cardBorder = NcStoreUiTheme.ResolveColor(_uiColors.ListingCardBorder, "#314052");
        var sideBackground = NcStoreUiTheme.ResolveColor(_uiColors.TabsFrameBackground, "#18202A");
        var secondaryText = NcStoreUiTheme.ResolveColor(_uiColors.TabFontInactive, "#AEBBCC");
        var primaryText = NcStoreUiTheme.ResolveColor(_uiColors.ListingTitleColor, "#DDD6C7");
        var progressTrackBg = NcStoreUiTheme.ResolveColor(_uiColors.TabsShellBackground, "#0E1319");

        AccentStrip.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = accent
        };

        CardFrame.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = cardBackground,
            BorderColor = cardBorder,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 5,
            ContentMarginBottomOverride = 5
        };

        SidePanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = sideBackground,
            BorderColor = cardBorder,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 5,
            ContentMarginBottomOverride = 5
        };

        ProgressTrack.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = progressTrackBg,
            BorderColor = cardBorder,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 1,
            ContentMarginRightOverride = 1,
            ContentMarginTopOverride = 1,
            ContentMarginBottomOverride = 1
        };

        ProgressFill.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = accent
        };

        TitleLabel.Modulate = _data.Completed
            ? Dim(primaryText, 0.85f)
            : primaryText;

        GoalsHeaderLabel.Modulate = secondaryText;
        TurnInHeaderLabel.Modulate = secondaryText;
        RewardsHeaderLabel.Modulate = secondaryText;
        ProgressLabel.Modulate = secondaryText;
        ProgressValueLabel.Modulate = NcStoreUiTheme.ResolveColor(_uiColors.TabFontActive, "#D7E1EC");
        TurnInNoteLabel.Modulate = NcStoreUiTheme.ResolveColor(_uiColors.HeaderBalanceText, "#C5D0DD");
        StageLabel.Modulate = NcStoreUiTheme.ResolveColor(_uiColors.TabFontActive, "#89B2E1");
    }

    private void PopulateHeader()
    {
        var title = BuildPrettyTitle(_data);
        TitleLabel.Text = title;
        TitleLabel.ToolTip = title;

        BadgesRow.RemoveAllChildren();

        var objectiveTypeText = ObjectiveTypeName(_data.ExecutionKind);
        var objectiveTypeTip = ObjectiveTypeTooltip(_data.ExecutionKind);
        BadgesRow.AddChild(
            BuildBadge(
                objectiveTypeText,
                objectiveTypeTip,
                Color.FromHex("#232127"),
                Color.FromHex("#8A7442")));

        if (!_data.Repeatable)
        {
            var tip = Loc.GetString("nc-store-contract-badge-single-tooltip");
            BadgesRow.AddChild(
                BuildBadge(
                    Loc.GetString("nc-store-contract-badge-single"),
                    tip,
                    Color.FromHex("#2A2627"),
                    Color.FromHex("#6B5A3A")));
        }

        if (_data.FlowStatus is ContractFlowStatus.AwaitingActivation or ContractFlowStatus.InProgress)
        {
            BadgesRow.AddChild(
                BuildBadge(
                    Loc.GetString("nc-store-contract-badge-taken"),
                    Loc.GetString("nc-store-contract-badge-taken-tooltip"),
                    Color.FromHex("#2A313B"),
                    Color.FromHex("#8A7442")));

            if (IsGhostRoleAwaitingAcceptance(_data))
            {
                BadgesRow.AddChild(
                    BuildBadge(
                        Loc.GetString("nc-store-contract-badge-awaiting-ghost-role"),
                        Loc.GetString("nc-store-contract-badge-awaiting-ghost-role-tooltip"),
                        Color.FromHex("#3A2E19"),
                        Color.FromHex("#C69A46")));
            }
            else if (IsGhostRoleActive(_data))
            {
                BadgesRow.AddChild(
                    BuildBadge(
                        Loc.GetString("nc-store-contract-badge-ghost-role-active"),
                        Loc.GetString("nc-store-contract-badge-ghost-role-active-tooltip"),
                        Color.FromHex("#243040"),
                        Color.FromHex("#8FA8C5")));
            }
        }

        if (_data.FlowStatus == ContractFlowStatus.ReadyToTurnIn)
        {
            BadgesRow.AddChild(
                BuildBadge(
                    Loc.GetString("nc-store-contract-badge-completed"),
                    Loc.GetString("nc-store-contract-badge-completed-tooltip"),
                    Color.FromHex("#243125"),
                    Color.FromHex("#8AA05D")));
        }
    }

    private void PopulateDescription()
    {
        var fullText = BuildPrettyDescription(_data);
        if (string.IsNullOrWhiteSpace(fullText))
        {
            DescriptionLabel.Visible = false;
            DescriptionLabel.ToolTip = null;
            DescriptionLabel.SetMessage(string.Empty, null, Color.FromHex("#D5CDC0"));
            return;
        }

        var displayText = BuildDisplayDescription(_data, DescriptionMaxChars);
        DescriptionLabel.Visible = true;
        DescriptionLabel.ToolTip = fullText;
        DescriptionLabel.SetMessage(displayText, null, Color.FromHex("#D5CDC0"));
    }

    private void PopulateStatus()
    {
        var ghostRoleStatus = BuildGhostRoleStatusText(_data);
        if (string.IsNullOrWhiteSpace(ghostRoleStatus))
        {
            StatusLabel.Visible = false;
            StatusLabel.Text = string.Empty;
            StatusLabel.ToolTip = null;
            return;
        }

        StatusLabel.Visible = true;
        StatusLabel.Text = ghostRoleStatus;
        StatusLabel.ToolTip = ghostRoleStatus;
        StatusLabel.Modulate = IsGhostRoleAwaitingAcceptance(_data)
            ? Color.FromHex("#D3B06A")
            : _data.FlowStatus == ContractFlowStatus.Failed
                ? Color.FromHex("#D97575")
                : Color.FromHex("#8DB7E8");
    }

    private void PopulateStage()
    {
        var hasStage = _data.ExecutionKind is ContractExecutionKind.HuntObjective
                or ContractExecutionKind.RepairObjective
                or ContractExecutionKind.GhostRoleObjective &&
            _data.Runtime.StageGoal > 1;

        StageLabel.Visible = hasStage;
        if (!hasStage)
            return;

        var stage = Math.Clamp(_data.Runtime.Stage, 0, _data.Runtime.StageGoal);
        StageLabel.Text = Loc.GetString(
            "nc-store-contract-runtime-stage",
            ("stage", stage),
            ("goal", _data.Runtime.StageGoal));
    }

    private void PopulateGoals()
    {
        GoalsHost.RemoveAllChildren();

        if (_data.Targets is { Count: > 0, })
        {
            foreach (var target in _data.Targets)
                GoalsHost.AddChild(BuildTargetRow(target.TargetItem, target.Required, target.MatchMode));
        }
        else if (!string.IsNullOrWhiteSpace(_data.TargetItem))
            GoalsHost.AddChild(BuildTargetRow(_data.TargetItem, _data.Required));
    }

    private void PopulateTurnIn()
    {
        var turnInNote = BuildTurnInNoteText(_data);
        TurnInNoteLabel.Visible = !string.IsNullOrWhiteSpace(turnInNote);
        TurnInNoteLabel.Text = turnInNote;
        TurnInNoteLabel.ToolTip = turnInNote;

        TurnInSection.Visible = ShouldShowTurnInItem(_data);
        TurnInHost.RemoveAllChildren();

        if (TurnInSection.Visible)
            TurnInHost.AddChild(BuildTargetRow(_data.TurnInItem, 1));
    }

    private void PopulateProgress()
    {
        ProgressSection.Visible = !_data.Completed;
        if (!ProgressSection.Visible)
            return;

        var max = CalculateRequiredTotal(_data);
        var val = Math.Clamp(_data.Progress, 0, max);
        _progressRatio = max > 0 ? (float) val / max : 0f;

        ProgressLabel.Text = Loc.GetString("nc-store-contract-progress-caption");
        ProgressValueLabel.Text = Loc.GetString(
            "nc-store-contract-progress-value",
            ("progress", val),
            ("required", max));
        UpdateProgressFillWidth();
    }

    private void PopulateRewardsSection()
    {
        RewardsHost.RemoveAllChildren();
        PopulateRewards(RewardsHost, _data.Rewards);
    }

    private void PopulateActionsSection()
    {
        var canTake = _data.FlowStatus == ContractFlowStatus.Available;
        var canClaim = _data.FlowStatus == ContractFlowStatus.ReadyToTurnIn;
        var canRequestPinpointer = CanRequestPinpointer(_data);

        var actionHint = BuildActionHintText(_data);
        ActionHintLabel.Text = actionHint;
        ActionHintLabel.ToolTip = actionHint;
        ActionHintLabel.Modulate = canClaim
            ? Color.FromHex("#D7E3EE")
            : Color.FromHex("#AAB7C8");

        PrimaryActionButton.Text = canTake
            ? Loc.GetString("nc-store-contract-action-take")
            : canClaim
                ? Loc.GetString("nc-store-contract-action-claim")
                : Loc.GetString(
                    "nc-store-contract-action-claim-progress",
                    ("progress", _data.Progress),
                    ("required", CalculateRequiredTotal(_data)));

        PrimaryActionButton.Disabled = !(canTake || canClaim);
        PrimaryActionButton.StyleBoxOverride = canTake
            ? BuildButtonStyle(Color.FromHex("#203248"), Color.FromHex("#4F86B7"))
            : canClaim
                ? BuildButtonStyle(Color.FromHex("#243729"), Color.FromHex("#7DA260"))
                : BuildButtonStyle(Color.FromHex("#23272D"), Color.FromHex("#475363"));

        PrimaryActionButton.ModulateSelfOverride = canTake
            ? Color.FromHex("#E5EEF8")
            : canClaim
                ? Color.FromHex("#E5EEDB")
                : Color.FromHex("#A6AFBA");

        PrimaryActionButton.ToolTip = canTake
            ? Loc.GetString("nc-store-contract-take-tooltip")
            : canClaim
                ? !_data.Repeatable
                    ? Loc.GetString("nc-store-contract-claim-tooltip-single")
                    : Loc.GetString("nc-store-contract-claim-tooltip-repeatable")
                : Loc.GetString("nc-store-contract-claim-tooltip-not-done");

        SecondaryButtonsRow.RemoveAllChildren();

        if (canRequestPinpointer)
        {
            var pointerBtn = new Button
            {
                Text = Loc.GetString("nc-store-contract-action-pinpointer"),
                HorizontalExpand = true,
                MinSize = new(0, 24),
                ToolTip = Loc.GetString("nc-store-contract-action-pinpointer-tooltip")
            };
            pointerBtn.StyleBoxOverride = BuildButtonStyle(Color.FromHex("#1F2833"), Color.FromHex("#4F86B7"));
            pointerBtn.ModulateSelfOverride = Color.FromHex("#D7E6F5");

            pointerBtn.OnPressed += _ => OnRequestPinpointer?.Invoke(_data.Id);
            SecondaryButtonsRow.AddChild(pointerBtn);
        }

        if (_skipCost > 0 && !string.IsNullOrWhiteSpace(_skipCurrency))
        {
            var skipCurrencyName = CurrencyName(_skipCurrency);
            var canSkip = _data.FlowStatus == ContractFlowStatus.Available && _skipBalance >= _skipCost;
            var skipBtn = new Button
            {
                Text = Loc.GetString(
                    "nc-store-contract-action-skip",
                    ("cost", _skipCost),
                    ("currency", skipCurrencyName)),
                HorizontalExpand = true,
                MinSize = new(0, 24),
                Disabled = !canSkip
            };

            skipBtn.StyleBoxOverride = canSkip
                ? BuildButtonStyle(Color.FromHex("#2A2C32"), Color.FromHex("#6E7E91"))
                : BuildButtonStyle(Color.FromHex("#222428"), Color.FromHex("#454C55"));
            skipBtn.ModulateSelfOverride = canSkip
                ? Color.FromHex("#D7DDEA")
                : Color.FromHex("#8A919A");

            var baseTip = Loc.GetString(
                "nc-store-contract-skip-tooltip",
                ("cost", _skipCost),
                ("currency", skipCurrencyName));
            skipBtn.ToolTip = _data.FlowStatus != ContractFlowStatus.Available
                ? Loc.GetString("nc-store-contract-skip-locked")
                : canSkip
                    ? baseTip
                    : $"{baseTip}\n{Loc.GetString("nc-store-contract-skip-failed")}";

            skipBtn.OnPressed += _ =>
            {
                if (canSkip)
                    OnSkip?.Invoke(_data.Id);
            };

            SecondaryButtonsRow.AddChild(skipBtn);
        }

        SecondaryButtonsRow.Visible = SecondaryButtonsRow.ChildCount > 0;
    }

    private void OnPrimaryActionPressed(BaseButton.ButtonEventArgs args)
    {
        var canTake = _data.FlowStatus == ContractFlowStatus.Available;
        var canClaim = _data.FlowStatus == ContractFlowStatus.ReadyToTurnIn;

        if (canTake)
        {
            OnTake?.Invoke(_data.Id);
            return;
        }

        if (canClaim)
            OnClaim?.Invoke(_data.Id);
    }

    private static PanelContainer BuildBadge(string text, string? tooltip, Color bg, Color border)
    {
        var badge = new PanelContainer
        {
            VerticalAlignment = VAlignment.Center,
            Margin = new(0, 0, 4, 0),
            MouseFilter = MouseFilterMode.Stop,
            ToolTip = tooltip,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = bg,
                BorderColor = border,
                BorderThickness = new(1),
                ContentMarginLeftOverride = 5,
                ContentMarginRightOverride = 5,
                ContentMarginTopOverride = 1,
                ContentMarginBottomOverride = 1
            }
        };

        var badgeText = new Label
        {
            Text = text,
            VerticalAlignment = VAlignment.Center,
            MouseFilter = MouseFilterMode.Ignore,
            ToolTip = tooltip
        };
        badgeText.StyleClasses.Add("LabelSubText");
        badgeText.Modulate = Color.FromHex("#D7DDEA");

        badge.AddChild(badgeText);
        return badge;
    }

    private static StyleBoxFlat BuildButtonStyle(Color background, Color border) =>
        new()
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 5,
            ContentMarginRightOverride = 5,
            ContentMarginTopOverride = 3,
            ContentMarginBottomOverride = 3
        };

    public void UpdateData(ContractClientData data, int skipCost, string skipCurrency, int skipBalance)
    {
        var presentationHash = ComputePresentationHash(data, skipCost, skipCurrency, skipBalance);
        if (_presentationHash == presentationHash)
            return;

        _presentationHash = presentationHash;
        _data = data;
        _skipCost = skipCost;
        _skipCurrency = skipCurrency;
        _skipBalance = skipBalance;
        _lastDescriptionMaxWidth = -1f;

        PopulateUi();
    }

    protected override void Resized()
    {
        base.Resized();
        SyncDescriptionWidth(Size.X);
        UpdateProgressFillWidth();
    }

    private void SyncDescriptionWidth(float candidateWidth)
    {
        if (candidateWidth <= 0 || !float.IsFinite(candidateWidth))
            return;

        var maxWidth = MathF.Max(0, candidateWidth - DescriptionHorizontalBudget);
        if (MathF.Abs(_lastDescriptionMaxWidth - maxWidth) < 0.5f)
            return;

        _lastDescriptionMaxWidth = maxWidth;
        DescriptionLabel.MaxWidth = maxWidth;
    }

    private void UpdateProgressFillWidth()
    {
        var trackWidth = ProgressTrack.Width;
        if (trackWidth <= 0 || !float.IsFinite(trackWidth))
            return;

        var fillWidth = _progressRatio <= 0f
            ? 0f
            : MathF.Max(ProgressFillMinVisibleWidth, trackWidth * _progressRatio);

        ProgressFill.MinSize = new(fillWidth, ProgressFill.MinSize.Y);
        ProgressFill.Visible = fillWidth > 0f;
    }
}
