using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NC.Trade.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcListingPriceButtonControl : Button
{
    private static readonly Color BaseBackground = Color.FromHex("#23170F");
    private static readonly Color HoverBackground = Color.FromHex("#2B1D12");
    private static readonly Color DisabledBackground = Color.FromHex("#1A1410");

    private static readonly Color BaseBorder = Color.FromHex("#8A6830");
    private static readonly Color HoverBorder = Color.FromHex("#C1913D");
    private static readonly Color DisabledBorder = Color.FromHex("#5A4931");

    private static readonly Color PrimaryText = Color.FromHex("#F0E0BE");
    private static readonly Color DisabledText = Color.FromHex("#A3947C");

    private bool _hovered;

    public NcListingPriceButtonControl()
    {
        RobustXamlLoader.Load(this);

        Text = string.Empty;
        Label.Text = string.Empty;
        Label.Visible = false;

        PriceLabel.AddStyleClass("LabelHeading");
        UnitPriceLabel.Visible = false;

        OnMouseEntered += _ =>
        {
            _hovered = true;
            ApplyVisualState();
        };

        OnMouseExited += _ =>
        {
            _hovered = false;
            ApplyVisualState();
        };

        ApplyVisualState();
    }

    public void SetCurrencyIcon(Texture? texture)
    {
        CurrencyIcon.Texture = texture;
        CurrencyIcon.Visible = texture != null;
    }

    public void SetPriceText(string text)
    {
        PriceLabel.Text = string.IsNullOrWhiteSpace(text) ? "0" : text;
    }

    public void SetUnitPriceText(string text)
    {
        UnitPriceLabel.Visible = false;
        UnitPriceLabel.Text = string.Empty;
    }

    public void RefreshVisualState()
    {
        ApplyVisualState();
    }

    private void ApplyVisualState()
    {
        var disabled = Disabled;

        var background = disabled
            ? DisabledBackground
            : _hovered ? HoverBackground : BaseBackground;

        var border = disabled
            ? DisabledBorder
            : _hovered ? HoverBorder : BaseBorder;

        var style = new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(1)
        };

        style.SetContentMarginOverride(StyleBox.Margin.Left, 0);
        style.SetContentMarginOverride(StyleBox.Margin.Top, 0);
        style.SetContentMarginOverride(StyleBox.Margin.Right, 0);
        style.SetContentMarginOverride(StyleBox.Margin.Bottom, 0);

        StyleBoxOverride = style;
        ModulateSelfOverride = Color.White;

        Label.Visible = false;
        PriceLabel.FontColorOverride = disabled ? DisabledText : PrimaryText;
        CurrencyIcon.ModulateSelfOverride = disabled ? DisabledText : Color.White;
    }
}
