using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._NC.Trade.Controls;


[GenerateTypedNameReferences]
public sealed partial class NcListingQuantityControl : BoxContainer
{
    private const int QtyMaxDigits = 6;

    private static readonly Color ButtonBackground = Color.FromHex("#1A2027");
    private static readonly Color ButtonBorder = Color.FromHex("#3C4652");
    private static readonly Color ButtonDisabledBackground = Color.FromHex("#16191E");
    private static readonly Color ButtonDisabledBorder = Color.FromHex("#2A313A");

    private static readonly Color EditBackground = Color.FromHex("#13171C");
    private static readonly Color EditBorder = Color.FromHex("#46505C");
    private static readonly Color EditDisabledBackground = Color.FromHex("#111419");
    private static readonly Color EditDisabledBorder = Color.FromHex("#2B3138");

    private static readonly Color TextEnabled = Color.FromHex("#D9D2C4");
    private static readonly Color TextDisabled = Color.FromHex("#7C7569");

    private bool _enabled = true;
    private int _max;
    private int _min;
    private bool _suppressEditChange;

    public NcListingQuantityControl()
    {
        RobustXamlLoader.Load(this);

        MinusButton.OnPressed += _ =>
        {
            if (_enabled && Value > _min)
                SetValue(Value - 1);
        };

        PlusButton.OnPressed += _ =>
        {
            if (_enabled && Value < _max)
                SetValue(Value + 1);
        };

        QtyEdit.OnTextChanged += _ =>
        {
            if (!_enabled || _suppressEditChange)
                return;

            var digits = new string(QtyEdit.Text.Where(char.IsDigit).Take(QtyMaxDigits).ToArray());
            if (digits.Length == 0)
            {
                SetEditSafe(Value.ToString());
                return;
            }

            if (!int.TryParse(digits, out var v))
                v = Value;

            var clamped = Math.Clamp(v, _min, Math.Max(_min, _max));
            var newText = clamped.ToString();

            if (QtyEdit.Text != newText)
                SetEditSafe(newText);

            SetValue(clamped);
        };

        QtyEdit.OnTextEntered += _ =>
        {
            if (_enabled)
                OnEnter?.Invoke();
        };

        ApplyVisualState();
    }

    public LineEdit Edit => QtyEdit;

    public int Value { get; private set; }

    public event Action<int>? OnValueChanged;
    public event Action? OnEnter;

    public void Configure(int minValue, int maxValue, int initialValue, bool enabled, string? disabledTooltip = null)
    {
        SetLimits(minValue, maxValue);
        SetEnabled(enabled, disabledTooltip);
        SetValue(initialValue, false);
    }

    public void SetLimits(int minValue, int maxValue)
    {
        _min = minValue;
        _max = Math.Max(minValue, maxValue);

        var clamped = Math.Clamp(Value, _min, _max);
        if (clamped != Value)
            SetValue(clamped);
        else
            UpdateButtonsState();
    }

    public void SetEnabled(bool enabled, string? disabledTooltip = null)
    {
        _enabled = enabled;
        MinusButton.Disabled = !enabled;
        PlusButton.Disabled = !enabled;
        QtyEdit.Editable = enabled;

        if (!enabled && disabledTooltip != null)
        {
            MinusButton.ToolTip = disabledTooltip;
            PlusButton.ToolTip = disabledTooltip;
            QtyEdit.ToolTip = disabledTooltip;
        }
        else
        {
            MinusButton.ToolTip = null;
            PlusButton.ToolTip = null;
            QtyEdit.ToolTip = null;
        }

        UpdateButtonsState();
        ApplyVisualState();
    }

    public void SetValue(int value, bool notify = true)
    {
        var clamped = Math.Clamp(value, _min, _max);

        if (clamped == Value && QtyEdit.Text == clamped.ToString())
        {
            UpdateButtonsState();
            ApplyVisualState();
            return;
        }

        Value = clamped;
        QtyLabel.Text = Value.ToString();

        var text = Value.ToString();
        if (QtyEdit.Text != text)
            SetEditSafe(text);

        UpdateButtonsState();
        ApplyVisualState();

        if (notify)
            OnValueChanged?.Invoke(Value);
    }

    public bool IsEditing(IUserInterfaceManager ui) => ui.KeyboardFocused == QtyEdit;

    private void UpdateButtonsState()
    {
        var noQty = !_enabled || _max <= 0;
        MinusButton.Disabled = noQty || Value <= _min;
        PlusButton.Disabled = noQty || Value >= _max;
        QtyEdit.Editable = !noQty;
    }

    private void SetEditSafe(string text)
    {
        _suppressEditChange = true;
        QtyEdit.Text = text;
        QtyEdit.CursorPosition = QtyEdit.Text.Length;
        _suppressEditChange = false;
    }

    private void ApplyVisualState()
    {
        ApplyButtonStyle(MinusButton);
        ApplyButtonStyle(PlusButton);

        QtyEdit.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = QtyEdit.Editable ? EditBackground : EditDisabledBackground,
            BorderColor = QtyEdit.Editable ? EditBorder : EditDisabledBorder,
            BorderThickness = new(1)
        };

        QtyEdit.ModulateSelfOverride = QtyEdit.Editable ? TextEnabled : TextDisabled;
    }

    private static void ApplyButtonStyle(Button button)
    {
        var disabled = button.Disabled;

        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = disabled ? ButtonDisabledBackground : ButtonBackground,
            BorderColor = disabled ? ButtonDisabledBorder : ButtonBorder,
            BorderThickness = new(1)
        };

        button.ModulateSelfOverride = disabled ? TextDisabled : TextEnabled;
    }
}
