using System.Linq;
using Content.Shared._NC.Trade;
using Content.Client._NC.Trade.Theme;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._NC.Trade.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcListingGrid : BoxContainer
{
    private const int PageSize = 96;

    private readonly record struct ListingSig(
        string Id,
        string ProductEntity,
        string Category,
        int Price,
        string CurrencyId,
        StoreMode Mode,
        int UnitsPerPurchase,
        string DisplayName,
        string Description,
        ulong BarterSig);

    private readonly Dictionary<string, (NcStoreListingControl Ctrl, ListingSig Sig)> _cache = new();
    private readonly Dictionary<string, StoreListingData> _itemById = new();
    private readonly Dictionary<string, int> _qtyCache = new();

    private readonly StoreMode _mode;
    private readonly IPrototypeManager _proto;
    private readonly SpriteSystem _sprites;
    private readonly IEntityManager _entMan;

    private readonly List<StoreListingData> _scratchFiltered = new();

    private readonly List<string> _scratchKeys = new();
    private readonly HashSet<string> _scratchSeenProtos = new();
    private readonly Dictionary<string, string> _searchIndex = new();

    private IReadOnlyList<StoreListingData> _allItems = Array.Empty<StoreListingData>();
    private Func<string, int> _balanceResolver = _ => int.MaxValue;
    private Action<StoreListingData, int> _emit = (_, _) => { };

    private int _page = 1;
    private string _searchLower = string.Empty;
    private string _selectedCategory = string.Empty;

    public event Action<IReadOnlyList<string>>? VisibleIdsChanged;
    private readonly List<string> _visibleIdsScratch = new();
    private StoreUiColorsData _uiColors = new();

    public NcListingGrid(StoreMode mode, IPrototypeManager proto, SpriteSystem sprites)
    {
        _mode = mode;
        _proto = proto;
        _sprites = sprites;
        _entMan = IoCManager.Resolve<IEntityManager>();

        RobustXamlLoader.Load(this);

        MoreButton.OnPressed += _ =>
        {
            _page++;
            RefreshInternal();
        };
    }

    public void ResetPaging() => _page = 1;

    public void ClearCaches()
    {
        _searchIndex.Clear();
        _cache.Clear();
        _qtyCache.Clear();
    }

    public void ApplyUiTheme(StoreUiColorsData colors)
    {
        _uiColors = colors;

        MessageLabel.ModulateSelfOverride = NcStoreUiTheme.ResolveColor(_uiColors.TabFontInactive, "#B9AE95");
        MessagePanel.PanelOverride = NcStoreUiTheme.Flat(
            NcStoreUiTheme.ResolveColor(_uiColors.TabInactiveBackground, "#2C2E35"),
            NcStoreUiTheme.ResolveColor(_uiColors.TabInactiveBorder, "#665C4E"));

        foreach (var (ctrl, _) in _cache.Values)
            ctrl.ApplyUiTheme(_uiColors);
    }

    public void SyncAvailableIds(IReadOnlyCollection<string> ids)
    {
        _scratchKeys.Clear();
        foreach (var key in _qtyCache.Keys)
            if (!ids.Contains(key))
                _scratchKeys.Add(key);

        for (var i = 0; i < _scratchKeys.Count; i++)
            _qtyCache.Remove(_scratchKeys[i]);

        _scratchKeys.Clear();
        foreach (var key in _cache.Keys)
            if (!ids.Contains(key))
                _scratchKeys.Add(key);

        for (var i = 0; i < _scratchKeys.Count; i++)
            _cache.Remove(_scratchKeys[i]);
    }

    public void PrepareSearchIndex(IEnumerable<string> productEntities)
    {
        _searchIndex.Clear();
        _scratchSeenProtos.Clear();

        foreach (var protoId in productEntities)
        {
            if (string.IsNullOrWhiteSpace(protoId))
                continue;

            if (!_scratchSeenProtos.Add(protoId))
                continue;

            AddToSearchIndex(protoId);
        }
    }

    public int Refresh(
        IReadOnlyList<StoreListingData> allItems,
        string? selectedCategory,
        string? searchLower,
        Func<string, int> balanceResolver,
        Action<StoreListingData, int> emit)
    {
        _allItems = allItems;
        _selectedCategory = selectedCategory ?? string.Empty;
        _searchLower = (searchLower ?? string.Empty).Trim().ToLowerInvariant();
        _balanceResolver = balanceResolver;
        _emit = emit;

        _itemById.Clear();
        for (var i = 0; i < allItems.Count; i++)
        {
            var it = allItems[i];
            if (it.Mode != _mode)
                continue;
            if (string.IsNullOrWhiteSpace(it.Id))
                continue;

            _itemById[it.Id] = it;
        }

        return RefreshInternal();
    }

    public void UpdateDynamicOnly(Func<string, int> balanceResolver)
    {
        _balanceResolver = balanceResolver;

        foreach (var child in ItemsHost.Children)
        {
            if (child is not NcStoreListingControl ctrl)
                continue;

            if (!_itemById.TryGetValue(ctrl.UiId, out var it))
                continue;

            var balanceHint = _mode == StoreMode.Buy
                ? _balanceResolver(it.CurrencyId)
                : int.MaxValue;

            ctrl.UpdateDynamicData(balanceHint, it.Remaining, it.Owned);
        }
    }

    private void ClearItemsHost()
    {
        while (ItemsHost.ChildCount > 0)
            ItemsHost.GetChild(0).Orphan();
    }

    private int RefreshInternal()
    {
        var hasCat = !string.IsNullOrEmpty(_selectedCategory);
        var hasSearch = !string.IsNullOrWhiteSpace(_searchLower);

        _scratchFiltered.Clear();

        if (_allItems.Count != 0)
        {
            foreach (var it in _allItems)
            {
                if (it.Mode != _mode)
                    continue;

                if (hasCat && it.Category != _selectedCategory)
                    continue;

                if (hasSearch && !MatchesSearch(it))
                    continue;

                _scratchFiltered.Add(it);
            }
        }

        if (_page < 1)
            _page = 1;

        MessagePanel.Visible = false;
        MoreButton.Visible = false;

        if (!hasCat && !hasSearch)
        {
            ClearItemsHost();
            MessageLabel.Text = Loc.GetString("nc-store-select-category");
            MessagePanel.Visible = true;
            NotifyVisibleIdsChanged();
            return 0;
        }

        if (_scratchFiltered.Count == 0)
        {
            ClearItemsHost();
            MessageLabel.Text = Loc.GetString(hasCat ? "nc-store-empty-category-search" : "nc-store-empty-search");
            MessagePanel.Visible = true;
            NotifyVisibleIdsChanged();
            return 0;
        }

        var total = _scratchFiltered.Count;
        var take = Math.Min(total, PageSize * _page);

        ClearItemsHost();
        AddListingRange(_scratchFiltered, 0, take);
        UpdateMoreButton(total, take);

        NotifyVisibleIdsChanged();
        return total;
    }

    private void NotifyVisibleIdsChanged()
    {
        if (VisibleIdsChanged == null)
            return;

        _visibleIdsScratch.Clear();

        foreach (var child in ItemsHost.Children)
        {
            if (child is NcStoreListingControl ctrl)
                _visibleIdsScratch.Add(ctrl.UiId);
        }

        VisibleIdsChanged(_visibleIdsScratch);
    }

    private void AddListingRange(List<StoreListingData> source, int startInclusive, int endExclusive)
    {
        for (var i = startInclusive; i < endExclusive; i++)
        {
            var it = source[i];

            var balanceHint = _mode == StoreMode.Buy
                ? _balanceResolver(it.CurrencyId)
                : int.MaxValue;

            var sig = MakeSig(it);

            if (!_cache.TryGetValue(it.Id, out var tuple) || tuple.Sig != sig)
            {
                var initQty = _qtyCache.GetValueOrDefault(it.Id, 1);
                var actionsEnabled = true;

                var created = new NcStoreListingControl(it, _sprites, _entMan, balanceHint, initQty, actionsEnabled);

                _cache[it.Id] = (created, sig);
                tuple = (created, sig);
            }

            var ctrl = tuple.Ctrl;
            ctrl.ApplyUiTheme(_uiColors);

            ctrl.BindActions(
                _mode == StoreMode.Barter ? qty => _emit(it, qty) : null,
                _mode == StoreMode.Buy ? qty => _emit(it, qty) : null,
                _mode == StoreMode.Sell ? qty => _emit(it, qty) : null,
                newQty => _qtyCache[it.Id] = newQty);

            ctrl.UpdateDynamicData(balanceHint, it.Remaining, it.Owned);

            if (ctrl.Parent != null)
                ctrl.Orphan();

            ItemsHost.AddChild(ctrl);
        }
    }

    private void UpdateMoreButton(int totalCount, int shown)
    {
        if (shown >= totalCount)
        {
            MoreButton.Visible = false;
            return;
        }

        var left = totalCount - shown;
        MoreButton.Text = Loc.GetString("nc-store-show-more", ("count", left));
        MoreButton.Visible = true;
    }

    private static ListingSig MakeSig(StoreListingData d) => new(
        d.Id,
        d.ProductEntity,
        d.Category,
        d.Price,
        d.CurrencyId,
        d.Mode,
        d.UnitsPerPurchase,
        d.DisplayName,
        d.Description,
        ComputeBarterSig(d));



    private static ulong ComputeBarterSig(StoreListingData d)
    {
        unchecked
        {
            var h = 14695981039346656037UL;
            for (var i = 0; i < d.BarterCost.Count; i++)
            {
                var c = d.BarterCost[i];
                h = MixStableString(h, c.Prototype);
                h = MixStableString(h, c.Group);
                h = MixStableString(h, c.Currency);
                h = MixStableInt(h, c.Count);
            }

            for (var i = 0; i < d.BarterReceive.Count; i++)
            {
                var r = d.BarterReceive[i];
                h = MixStableString(h, r.Prototype);
                h = MixStableString(h, r.Currency);
                h = MixStableInt(h, r.Count);
            }

            for (var i = 0; i < d.BarterReceivePools.Count; i++)
            {
                var r = d.BarterReceivePools[i];
                h = MixStableString(h, r.Pool);
                h = MixStableInt(h, r.Rolls.Min);
                h = MixStableInt(h, r.Rolls.Max);
                h = MixStableInt(h, BitConverter.SingleToInt32Bits(r.Chance));
            }

            return h;
        }
    }

    private static ulong MixStableString(ulong hash, string? value)
    {
        unchecked
        {
            if (value == null)
                return MixStableInt(hash, -1);

            var h = hash;
            for (var i = 0; i < value.Length; i++)
                h = (h ^ (uint) value[i]) * 1099511628211UL;

            return MixStableInt(h, value.Length);
        }
    }

    private static ulong MixStableInt(ulong hash, int value)
    {
        unchecked
        {
            var h = hash;
            h = (h ^ (uint) (value & 0xFF)) * 1099511628211UL;
            h = (h ^ (uint) ((value >> 8) & 0xFF)) * 1099511628211UL;
            h = (h ^ (uint) ((value >> 16) & 0xFF)) * 1099511628211UL;
            h = (h ^ (uint) ((value >> 24) & 0xFF)) * 1099511628211UL;
            return h;
        }
    }

    private void AddToSearchIndex(string protoId)
    {
        if (_searchIndex.ContainsKey(protoId))
            return;

        if (_proto.TryIndex<EntityPrototype>(protoId, out var p))
        {
            _searchIndex[protoId] = (p.Name + "\n" + p.Description).ToLowerInvariant();
            return;
        }

        if (!_proto.TryIndex<NcMatcherPrototype>(protoId, out var matcher))
            return;

        var parts = new List<string>(matcher.Items.Count + 2)
        {
            matcher.Name
        };

        if (!string.IsNullOrWhiteSpace(matcher.Description))
            parts.Add(matcher.Description);

        for (var i = 0; i < matcher.Items.Count; i++)
        {
            var itemProtoId = matcher.Items[i];
            if (string.IsNullOrWhiteSpace(itemProtoId))
                continue;

            if (_proto.TryIndex<EntityPrototype>(itemProtoId, out var itemProto))
                parts.Add(itemProto.Name);
            else
                parts.Add(itemProtoId);
        }

        _searchIndex[protoId] = string.Join("\n", parts).ToLowerInvariant();
    }

    private bool MatchesSearch(StoreListingData listing)
    {
        if (string.IsNullOrWhiteSpace(_searchLower))
            return true;

        var hay = BuildListingSearchText(listing);
        return !string.IsNullOrWhiteSpace(hay) && hay.Contains(_searchLower, StringComparison.Ordinal);
    }

    private string BuildListingSearchText(StoreListingData listing)
    {
        var parts = new List<string>(8 + listing.BarterCost.Count + listing.BarterReceive.Count + listing.BarterReceivePools.Count);

        AddSearchPart(parts, listing.Id);
        AddSearchPart(parts, listing.ListingId);
        AddSearchPart(parts, listing.ProductEntity);
        AddSearchPart(parts, listing.DisplayName);
        AddSearchPart(parts, listing.Description);
        AddSearchPart(parts, listing.Category);
        AddPrototypeSearchPart(parts, listing.ProductEntity);

        if (listing.Mode == StoreMode.Barter)
        {
            AddSearchPart(parts, Loc.GetString("nc-store-tab-barter"));
            AddSearchPart(parts, Loc.GetString("nc-store-barter-button"));

            for (var i = 0; i < listing.BarterCost.Count; i++)
                AddBarterCostSearchPart(parts, listing.BarterCost[i]);

            for (var i = 0; i < listing.BarterReceive.Count; i++)
                AddBarterReceiveSearchPart(parts, listing.BarterReceive[i]);

            for (var i = 0; i < listing.BarterReceivePools.Count; i++)
                AddBarterReceivePoolSearchPart(parts, listing.BarterReceivePools[i]);
        }

        return string.Join('\n', parts).ToLowerInvariant();
    }

    private void AddBarterCostSearchPart(List<string> parts, NcBarterCostEntry entry)
    {
        AddPrototypeSearchPart(parts, entry.Prototype);
        AddItemGroupSearchPart(parts, entry.Group);
        AddCurrencySearchPart(parts, entry.Currency);
    }

    private void AddBarterReceiveSearchPart(List<string> parts, NcBarterReceiveEntry entry)
    {
        AddPrototypeSearchPart(parts, entry.Prototype);
        AddCurrencySearchPart(parts, entry.Currency);
    }

    private void AddBarterReceivePoolSearchPart(List<string> parts, NcBarterReceivePoolEntry entry)
    {
        AddSearchPart(parts, entry.Pool);
        AddSearchPart(parts, Loc.GetString("nc-store-barter-random-receive"));

        if (string.IsNullOrWhiteSpace(entry.Pool))
            return;

        if (_proto.TryIndex<NcSupplyRewardPoolPrototype>(entry.Pool, out var supplyPool))
        {
            for (var i = 0; i < supplyPool.Entries.Count; i++)
            {
                var reward = supplyPool.Entries[i];

                if (reward.Type == StoreRewardType.Item)
                    AddPrototypeSearchPart(parts, reward.Prototype);
                else if (reward.Type == StoreRewardType.Currency)
                    AddCurrencySearchPart(parts, reward.Currency);
            }

            return;
        }

    }

    private void AddPrototypeSearchPart(List<string> parts, string protoId)
    {
        if (string.IsNullOrWhiteSpace(protoId))
            return;

        AddSearchPart(parts, protoId);

        if (!_searchIndex.TryGetValue(protoId, out var hay))
        {
            AddToSearchIndex(protoId);
            _searchIndex.TryGetValue(protoId, out hay);
        }

        AddSearchPart(parts, hay);
    }

    private void AddItemGroupSearchPart(List<string> parts, string groupId)
    {
        if (string.IsNullOrWhiteSpace(groupId))
            return;

        AddSearchPart(parts, groupId);

        if (!_proto.TryIndex<NcItemGroupPrototype>(groupId, out var group))
            return;

        AddSearchPart(parts, group.Name);
        AddSearchPart(parts, group.Description);
        AddSearchPart(parts, group.Icon);

        for (var i = 0; i < group.Tags.Count; i++)
            AddSearchPart(parts, group.Tags[i]);

        for (var i = 0; i < group.Prototypes.Count; i++)
            AddPrototypeSearchPart(parts, group.Prototypes[i]);
    }

    private void AddCurrencySearchPart(List<string> parts, string currencyId)
    {
        if (string.IsNullOrWhiteSpace(currencyId))
            return;

        AddSearchPart(parts, currencyId);

        if (!_proto.TryIndex<StackPrototype>(currencyId, out var stack))
            return;

        AddSearchPart(parts, stack.Spawn);
        AddPrototypeSearchPart(parts, stack.Spawn);
    }

    private static void AddSearchPart(List<string> parts, string? value)
    {
        if (!string.IsNullOrWhiteSpace(value))
            parts.Add(value);
    }

}
