using System;
using System.Collections.Generic;
using Content.Shared._NC.Trade;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._NC.Trade.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcStoreListingsView : PanelContainer
{
    private readonly List<string> _visibleIds = new();

    private NcListingGrid? _grid;
    private StoreMode _mode;

    private Func<string, string> _categoryDisplayName = static id => id;
    private string _searchLower = string.Empty;

    private IReadOnlyList<StoreListingData> _items = Array.Empty<StoreListingData>();
    private Func<string, int> _getBalanceForCurrency = static _ => 0;
    private Action<StoreListingData, int>? _onPressed;
    private StoreUiColorsData _uiColors = new();

    public string SelectedCategory { get; private set; } = string.Empty;

    public event Action<IReadOnlyList<string>>? VisibleIdsChanged;
    public event Action<string>? SelectedCategoryChanged;

    public NcStoreListingsView()
    {
        RobustXamlLoader.Load(this);
        ApplyUiTheme(_uiColors);
    }

    public void Initialize(
        StoreMode mode,
        IPrototypeManager proto,
        SpriteSystem sprites,
        string tabHeading,
        bool showMassSellButton)
    {
        _mode = mode;
        TabHeading.Text = tabHeading;

        MassSellRow.Visible = showMassSellButton;

        _grid = new NcListingGrid(mode, proto, sprites)
        {
            HorizontalExpand = true
        };
        _grid.ApplyUiTheme(_uiColors);

        _grid.VisibleIdsChanged += ids =>
        {
            _visibleIds.Clear();
            _visibleIds.AddRange(ids);
            VisibleIdsChanged?.Invoke(_visibleIds);
        };

        Pane.SetContent(_grid);
        // Important UX rule for the store: switching category must never inherit scroll
        // from a previous category. The pane owns this policy.
        Pane.RememberScrollPerKey = false;

        CategoryBar.OnSelectedChanged += catId =>
        {
            SelectedCategory = catId;
            Pane.SetKey(catId);
            _grid.ResetPaging();
            Refresh();
            SelectedCategoryChanged?.Invoke(SelectedCategory);
        };
    }

    public void ConfigureCategories(Func<string, string> displayName, Func<string, string> toolTip)
    {
        _categoryDisplayName = displayName;
        CategoryBar.Configure(displayName, toolTip);
    }

    public void SetCategories(IReadOnlyList<string> categories)
    {
        CategoryBar.SetCategories(categories, SelectedCategory);
        SelectedCategory = CategoryBar.Selected;
        Pane.SetKey(SelectedCategory);
        Refresh();
    }

    public void SetSearch(string searchLower)
    {
        _searchLower = searchLower ?? string.Empty;
        _grid?.ResetPaging();
        Refresh();
    }

    public void BindListingsData(
        IReadOnlyList<StoreListingData> items,
        Func<string, int> getBalanceForCurrency,
        Action<StoreListingData, int> onPressed)
    {
        _items = items;
        _getBalanceForCurrency = getBalanceForCurrency;
        _onPressed = onPressed;
        Refresh();
    }

    public void PrepareSearchIndex(List<string> productProtos) => _grid?.PrepareSearchIndex(productProtos);

    public void SyncAvailableIds(HashSet<string> availableIds) => _grid?.SyncAvailableIds(availableIds);

    public void UpdateDynamicOnly(Func<string, int> getBalanceForCurrency) => _grid?.UpdateDynamicOnly(getBalanceForCurrency);

    public void ClearCaches() => _grid?.ClearCaches();

    public Button MassSellButtonControl => MassSellButton;

    public void ApplyUiTheme(StoreUiColorsData colors)
    {
        _uiColors = colors;

        CategoriesPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = ThemeColor(_uiColors.CategoriesPanelBackground, "#161A20"),
            BorderColor = ThemeColor(_uiColors.TabsFrameBorder, "#323944"),
            BorderThickness = new Thickness(1)
        };

        CategoriesDivider.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = ThemeColor(_uiColors.CategoriesDivider, "#2E3640")
        };

        CategoryHeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = ThemeColor(_uiColors.TabInactiveBackground, "#20252D"),
            BorderColor = ThemeColor(_uiColors.TabInactiveBorder, "#414955"),
            BorderThickness = new Thickness(1)
        };

        CategoryHeader.ModulateSelfOverride = ThemeColor(_uiColors.TabFontActive, "#E4D5B2");
        TabHeading.ModulateSelfOverride = ThemeColor(_uiColors.TabFontInactive, "#A9A18F");

        UpdateCategoryHeaderStyle(isSelectedCategory: !string.IsNullOrEmpty(SelectedCategory));

        CategoryBar.SetThemeColors(
            ThemeColor(_uiColors.CategoryButtonIdle, "#7C6624"),
            ThemeColor(_uiColors.CategoryButtonSelected, "#D9A441"));

        _grid?.ApplyUiTheme(_uiColors);
    }

    private void Refresh()
    {
        if (_grid == null)
            return;

        var hasSearch = !string.IsNullOrWhiteSpace(_searchLower);

        var count = _grid.Refresh(
            _items,
            SelectedCategory,
            _searchLower,
            _mode == StoreMode.Buy ? _getBalanceForCurrency : static _ => int.MaxValue,
            (d, qty) => _onPressed?.Invoke(d, qty));

        CategoryHeader.Visible = !string.IsNullOrEmpty(SelectedCategory) || hasSearch;
        CategoryHeaderPanel.Visible = CategoryHeader.Visible;

        if (!CategoryHeader.Visible)
        {
            CategoryHeader.Text = string.Empty;
            return;
        }

        if (!string.IsNullOrEmpty(SelectedCategory))
        {
            CategoryHeader.Text = _categoryDisplayName(SelectedCategory);
            UpdateCategoryHeaderStyle(isSelectedCategory: true);
            return;
        }

        CategoryHeader.Text = _mode == StoreMode.Buy
            ? Loc.GetString("nc-store-search-results-buy", ("count", count))
            : Loc.GetString("nc-store-search-results-sell", ("count", count));
        UpdateCategoryHeaderStyle(isSelectedCategory: false);
    }

    private void UpdateCategoryHeaderStyle(bool isSelectedCategory)
    {
        var background = isSelectedCategory
            ? ThemeColor(_uiColors.TabActiveBackground, "#6B5730")
            : ThemeColor(_uiColors.TabInactiveBackground, "#2C2E35");
        var border = isSelectedCategory
            ? ThemeColor(_uiColors.TabActiveBorder, "#D4B06A")
            : ThemeColor(_uiColors.TabInactiveBorder, "#665C4E");
        var text = isSelectedCategory
            ? ThemeColor(_uiColors.TabFontActive, "#F0D49A")
            : ThemeColor(_uiColors.TabFontInactive, "#B9AE95");

        CategoryHeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new(1)
        };
        CategoryHeader.ModulateSelfOverride = text;
    }

    private static Color ThemeColor(string? value, string fallback)
    {
        if (!string.IsNullOrWhiteSpace(value))
        {
            try
            {
                return Color.FromHex(value);
            }
            catch
            {
                // Invalid YAML color should not break UI rendering.
            }
        }

        return Color.FromHex(fallback);
    }
}
