using System.Linq;
using System.Numerics;
using Content.Shared._NC.Trade;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;


namespace Content.Client._NC.Trade.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcStoreListingControl : PanelContainer
{
    private const int TextMax = 420;
    private const int QtyMaxDigits = 6;
    private const int MaxTotalDisplay = 999_999;
    private const int DescMaxChars = 220;

    private readonly bool _actionsEnabled;
    private readonly IUserInterfaceManager _ui = IoCManager.Resolve<IUserInterfaceManager>();

    private int _maxQty;
    private int _qty;
    private StoreListingData _staticData;
    private bool _suppressQtyEditChange;

    public NcStoreListingControl(
        StoreListingData data,
        SpriteSystem sprites,
        IEntityManager entMan,
        int balanceHint = int.MaxValue,
        int initialQty = 1,
        bool actionsEnabled = true
    )
    {
        RobustXamlLoader.Load(this);

        _staticData = data;
        _actionsEnabled = actionsEnabled;

        var pm = IoCManager.Resolve<IPrototypeManager>();
        pm.TryIndex<EntityPrototype>(data.ProductEntity, out var proto);

        TitleLabel.Text = proto?.Name ?? data.ProductEntity;
        TitleLabel.ToolTip = proto?.Name ?? data.ProductEntity;

        if (data.Mode == StoreMode.Buy && data.UnitsPerPurchase > 1)
        {
            TitleLabel.Text = $"{TitleLabel.Text} ×{data.UnitsPerPurchase}";
            TitleLabel.ToolTip = TitleLabel.Text;
        }


        if (proto != null)
        {
            IconView.SetPrototype(proto.ID);
            NcUiIconFit.Fit(IconView, sprites, proto.ID, targetPx: 96, paddingPx: 8);
        }
        else
            IconSlotBackground.Visible = false;
        SetDescription(proto);

        SetupPriceButton(data, sprites, pm);

        SetupQtyLogic(data, balanceHint, initialQty);

        UpdateLabelsAndVisibility(data);
    }

    public Action<int>? OnBuyPressed { get; set; }
    public Action<int>? OnSellPressed { get; set; }
    public Action<int>? OnQtyChanged { get; set; }

    public string UiId => _staticData.Id;
    public string ListingId => _staticData.ListingId;
    public StoreListingFlavor Flavor => _staticData.Flavor;
    private int MinAllowed => _maxQty <= 0 ? 0 : 1;

    private void SetDescription(EntityPrototype? proto)
    {
        var full = proto?.Description ?? string.Empty;
        if (string.IsNullOrWhiteSpace(full))
        {
            DescriptionLabel.Visible = false;
            return;
        }

        var trimmed = TrimToChars(full, DescMaxChars);
        var msg = new FormattedMessage();
        msg.AddText(trimmed);

        DescriptionLabel.SetMessage(msg);
        DescriptionLabel.ToolTip = full;
        DescriptionLabel.MaxWidth = TextMax;
    }

    private void SetupPriceButton(StoreListingData data, SpriteSystem sprites, IPrototypeManager pm)
    {
        if (!string.IsNullOrEmpty(data.CurrencyId) &&
            pm.TryIndex<StackPrototype>(data.CurrencyId, out var stack) &&
            pm.TryIndex<EntityPrototype>(stack.Spawn, out var ent) &&
            sprites.GetPrototypeIcon(ent.ID).Default is { } currencyTex)
        {
            PriceCurrencyIcon.Texture = currencyTex;
            PriceCurrencyIcon.Visible = true;
        }
        else
            PriceCurrencyIcon.Visible = false;

        if (!_actionsEnabled)
            PriceButton.ToolTip = Loc.GetString("nc-store-only-mass-sell");

        PriceButton.OnPressed += _ =>
        {
            if (!_actionsEnabled || _maxQty <= 0 || _qty <= 0)
                return;

            switch (data.Mode)
            {
                case StoreMode.Buy:
                    OnBuyPressed?.Invoke(_qty);
                    break;
                case StoreMode.Sell:
                    OnSellPressed?.Invoke(_qty);
                    break;
            }
        };
    }

    private void SetupQtyLogic(StoreListingData data, int balanceHint, int initialQty)
    {
        CalculateMaxQty(data, balanceHint);
        _qty = Math.Clamp(initialQty, MinAllowed, Math.Max(MinAllowed, _maxQty));

        QtyLabel.Text = _qty.ToString();
        QtyEdit.Text = _qty.ToString();

        var noQty = _maxQty <= 0 || !_actionsEnabled;
        MinusButton.Disabled = noQty;
        PlusButton.Disabled = noQty;
        QtyEdit.Editable = !noQty;

        if (!_actionsEnabled)
        {
            MinusButton.ToolTip = Loc.GetString("nc-store-only-mass-sell");
            PlusButton.ToolTip = Loc.GetString("nc-store-only-mass-sell");
            QtyEdit.ToolTip = Loc.GetString("nc-store-only-mass-sell");
        }

        MinusButton.OnPressed += _ =>
        {
            if (_actionsEnabled && _qty > MinAllowed)
                SetQty(_qty - 1);
        };

        PlusButton.OnPressed += _ =>
        {
            if (_actionsEnabled && _qty < _maxQty)
                SetQty(_qty + 1);
        };

        QtyEdit.OnTextChanged += _ =>
        {
            if (!_actionsEnabled || _suppressQtyEditChange)
                return;

            var digits = new string(QtyEdit.Text.Where(char.IsDigit).Take(QtyMaxDigits).ToArray());
            if (digits.Length == 0)
            {
                SetQtyEditSafe(_qty.ToString());
                return;
            }

            if (!int.TryParse(digits, out var v))
                v = _qty;

            var clamped = Math.Clamp(v, MinAllowed, Math.Max(MinAllowed, _maxQty));
            var newText = clamped.ToString();

            if (QtyEdit.Text != newText)
                SetQtyEditSafe(newText);

            SetQty(clamped);
        };

        QtyEdit.OnTextEntered += _ =>
        {
            if (!_actionsEnabled || _maxQty <= 0 || _qty <= 0)
                return;

            if (data.Mode == StoreMode.Buy)
                OnBuyPressed?.Invoke(_qty);
            else if (data.Mode == StoreMode.Sell)
                OnSellPressed?.Invoke(_qty);
        };
    }

    private void SetQtyEditSafe(string text)
    {
        _suppressQtyEditChange = true;
        QtyEdit.Text = text;
        QtyEdit.CursorPosition = QtyEdit.Text.Length;
        _suppressQtyEditChange = false;
    }

    private void CalculateMaxQty(StoreListingData data, int balanceHint)
    {
        var remainingCap = data.Remaining >= 0 ? data.Remaining : int.MaxValue;
        var ownedCap = data.Mode == StoreMode.Sell ? data.Owned : int.MaxValue;
        var moneyCap = data.Mode == StoreMode.Buy && data.Price > 0
            ? balanceHint / data.Price
            : int.MaxValue;

        _maxQty = Math.Min(remainingCap, Math.Min(ownedCap, moneyCap));
    }

    public void UpdateIdentity(StoreListingData newData) => _staticData = newData;

    public void UpdateDynamicData(int playerBalance, int remainingStock, int playerOwned)
    {
        _staticData.Remaining = remainingStock;
        _staticData.Owned = playerOwned;

        CalculateMaxQty(_staticData, playerBalance);

        var minAllowed = _maxQty <= 0 ? 0 : 1;
        var clamped = Math.Clamp(_qty, minAllowed, Math.Max(minAllowed, _maxQty));

        if (clamped != _qty)
        {
            _qty = clamped;
            QtyLabel.Text = _qty.ToString();

            if (QtyEdit.Text != _qty.ToString() && _ui.KeyboardFocused != QtyEdit)
                SetQtyEditSafe(_qty.ToString());
            OnQtyChanged?.Invoke(_qty);
        }

        UpdateButtonsState(minAllowed);
        UpdateLabelsAndVisibility(_staticData);
    }

    private void UpdateButtonsState(int minAllowed)
    {
        var noQty = _maxQty <= 0 || !_actionsEnabled;
        MinusButton.Disabled = noQty || _qty <= minAllowed;
        PlusButton.Disabled = noQty || _qty >= _maxQty;
        QtyEdit.Editable = !noQty;

        var disablePrice = !_actionsEnabled || noQty ||
            _staticData.Remaining == 0 ||
            _staticData.Mode == StoreMode.Sell && _staticData.Owned <= 0;

        PriceButton.Disabled = disablePrice;
    }

    private void UpdateLabelsAndVisibility(StoreListingData data)
    {
        if (data.Remaining != 0)
        {
            PriceButton.Visible = true;
            NoStockLabel.Visible = false;
            UpdateTotalPrice(data);
        }
        else
        {
            PriceButton.Visible = false;
            NoStockLabel.Visible = true;
            NoStockLabel.Text = data.Mode == StoreMode.Buy
                ? Loc.GetString("nc-store-no-stock")
                : Loc.GetString("nc-store-buying-finished");
        }

        if (data.Remaining >= 0)
        {
            RemainingLabel.Visible = true;
            RemainingLabel.Text = data.Mode == StoreMode.Buy
                ? Loc.GetString("nc-store-remaining", ("count", data.Remaining))
                : Loc.GetString("nc-store-will-buy", ("count", data.Remaining));
        }
        else
            RemainingLabel.Visible = false;

        OwnedLabel.Visible = data.Owned > 0;
        if (data.Owned > 0)
            OwnedLabel.Text = Loc.GetString("nc-store-owned", ("count", data.Owned));
    }

    private void SetQty(int v)
    {
        var newQty = Math.Clamp(v, MinAllowed, Math.Max(MinAllowed, _maxQty));
        QtyEdit.Modulate = Color.White;

        if (newQty == _qty && QtyEdit.Text == newQty.ToString())
            return;

        _qty = newQty;
        QtyLabel.Text = _qty.ToString();
        var text = _qty.ToString();

        if (QtyEdit.Text != text)
            SetQtyEditSafe(text);

        UpdateButtonsState(MinAllowed);
        UpdateTotalPrice(_staticData);
        OnQtyChanged?.Invoke(_qty);
    }

    private void UpdateTotalPrice(StoreListingData data)
    {
        var value = _qty <= 0 ? data.Price : (long) data.Price * _qty;
        PriceLabel.Text = value > MaxTotalDisplay ? $"{MaxTotalDisplay}+" : value.ToString();
    }

    private static string TrimToChars(string text, int max)
    {
        if (max <= 0 || string.IsNullOrEmpty(text) || text.Length <= max)
            return text;

        var cut = Math.Max(0, max - 1);
        var span = text.AsSpan(0, cut);
        var lastSpace = span.LastIndexOf(' ');
        var end = lastSpace > 0 ? lastSpace : cut;

        return text.Substring(0, end) + "…";
    }
}
