using Content.Client.Store.Ui;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Warfront;
using Content.Shared._Forge.Warfront.FactionShop;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Forge.Warfront.FactionShop.UI;

[GenerateTypedNameReferences]
public sealed partial class FactionShopWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private IEntityManager _entity = default!;

    public event Action<EntProtoId>? BuyRequested;

    public FactionShopWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(FactionShopBoundUserInterfaceState state)
    {
        BalanceLabel.Text = Loc.GetString("faction-shop-balance-display",
            ("amount", state.Balance),
            ("faction", FactionName(state.Faction)));

        ListingsContainer.Children.Clear();

        var spriteSys = _entity.EntitySysManager.GetEntitySystem<SpriteSystem>();

        foreach (var (product, cost) in state.AvailableListings)
        {
            if (!_proto.HasIndex<EntityPrototype>(product))
                continue;

            var listingData = new ListingData
            {
                ProductEntity = product,
            };
            var data = new ListingDataWithCostModifiers(listingData);
            var hasBalance = cost <= state.Balance;
            var price = Loc.GetString("faction-shop-price-display", ("amount", cost));

            var texture = spriteSys.GetPrototypeIcon(product).Default;

            var row = new StoreListingControl(data, price, string.Empty, hasBalance, texture);
            row.StoreItemBuyButton.OnButtonDown += _ => BuyRequested?.Invoke(product);

            ListingsContainer.AddChild(row);
        }
    }

    private static string FactionName(WarfrontFaction faction)
    {
        return faction switch
        {
            WarfrontFaction.NCR => Loc.GetString("capture-point-faction-ncr"),
            WarfrontFaction.Legion => Loc.GetString("capture-point-faction-legion"),
            _ => faction.ToString(),
        };
    }
}
