using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.FixedPoint;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Silicons;

/// <summary>
/// Forge-Change: the law card editor window. Compact list of editable laws with add/remove,
/// and the action buttons pinned at the bottom.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LawCardWindow : FancyWindow
{
    private List<SiliconLaw> _laws = new();

    public LawCardWindow()
    {
        RobustXamlLoader.Load(this);

        NewLawButton.OnPressed += _ => AddNewLaw();
    }

    public void SetLaws(List<SiliconLaw> laws)
    {
        _laws = laws;
        Refresh();
    }

    private void AddNewLaw()
    {
        _laws.Add(new SiliconLaw { Order = FixedPoint2.New(_laws.Count + 1) });
        Refresh();
    }

    private void DeleteLaw(SiliconLaw law)
    {
        _laws.Remove(law);
        Refresh();
    }

    private void Refresh()
    {
        LawContainer.RemoveAllChildren();
        var position = 1;
        foreach (var law in _laws.OrderBy(l => l.Order))
        {
            var entry = new LawCardEntry();
            entry.SetLaw(law, position);
            entry.OnDelete += DeleteLaw;
            LawContainer.AddChild(entry);
            position++;
        }
    }

    /// <summary>Returns the current laws, renumbered sequentially from 1.</summary>
    public List<SiliconLaw> GetLaws()
    {
        var ordered = _laws.OrderBy(l => l.Order).ToList();
        for (var i = 0; i < ordered.Count; i++)
            ordered[i].Order = FixedPoint2.New(i + 1);
        return ordered;
    }
}
